### ISSUE TITLE
網易雲音樂 Android v8+ 使用自動 Proxy 首次啟動後無法運作

### ISSUE THREAD

**Issue by keeno1982** [1715173329/UnblockNeteaseMusic#100]
用IP加端口号是可以的，但是用自动代理配置的pac文件就不行，是pac文件失效了吗？

**Comment by pan93412** [comment]
我能正常運作。這是我的設定，你可以參考看看。

<img width="621" alt="截圖 2021-08-06 下午3 42 19" src="https://user-images.githubusercontent.com/28441561/128475138-8571731d-128c-47b6-a992-e6019d6b52aa.png">

**Comment by keeno1982** [comment]
你这是mac吗，我是小米9安卓手机

**Comment by pan93412** [comment]
> 你这是mac吗，我是小米9安卓手机
> 能把你的pac文件发出来看看吗，我的服务器用的是lean的openwrt路由，你的看起来像是本地的服务

Android 的話你是設在 WLAN 裡面嗎？我沒在 Android 用過 UnblockNeteaseMusic。

<img width="794" alt="截圖 2021-08-06 下午3 58 34" src="https://user-images.githubusercontent.com/28441561/128477134-98770b6f-f39d-4d92-bc38-dc9d375dac41.png">

**Comment by keeno1982** [comment]
是的，你说的WLAN就是WIFI吧，看了你这份多了两个host，host == '103.126.92.133' || host == '103.126.92.132'。不过我加进去也同样无效，不知道是不是小米手机本身就有host，导致绕不过去

另外个问题，PC端的VIP音乐是不是也解锁不了，只能1分钟试听？

**Comment by pan93412** [comment]
理論上應該全部解鎖。重開用戶端或是檢查 Proxy 設定是否正確？

**Comment by 1715173329** [comment]
我们拥有一个专为路由器设计的全功能 LuCI，无需局域网设备手动设置
https://github.com/immortalwrt/luci-app-unblockneteasemusic

**Comment by llllcccjjj** [comment]
小米8安卓的测试最新的网易云音乐初次安装可以，后续失败。换7.0的版本就可以了

**Comment by 1715173329** [comment]
不支持网易云音乐 8.0+ 版本

**Comment by llllcccjjj** [comment]
ios 8.0+没问题 ，安卓8.0+只有第一次可以

**Comment by keeno1982** [comment]
> 
> 
> 我们拥有一个专为 OpenWrt 系统设计的全功能 LuCI 插件，无需局域网设备手动设置
> https://github.com/immortalwrt/luci-app-unblockneteasemusic

刚才试了一下，放到Lean的openwrt源码里面一起编译，安装后看不到界面入口？怎么回事

**Comment by pan93412** [comment]
我改掉 Issue Title 了。謝謝你們的回報～ ❤️

**Comment by keeno1982** [comment]
@1715173329 可以用了，太感谢了，只是不知道如何用pac自动代理了，在外面其它网络下只能走手动IP+端口

**Comment by SpeedPartner** [comment]
安卓我建议用magisk的本地代理版本

**Comment by 1715173329** [comment]
> @1715173329 可以用了，太感谢了，只是不知道如何用pac自动代理了，在外面其它网络下只能走手动IP+端口

luci 中请尝试打开“进阶设置”并勾选“部署到公网”

**Comment by keeno1982** [comment]
> 
> 
> 安卓我建议用magisk的本地代理版本

magisk有点麻烦，有的网银会识别机器已root不让你用，虽然有插件可以避免识别。另外微信也会被锁，后面我就不敢用了

**Comment by keeno1982** [comment]
> 
> 
> > @1715173329 可以用了，太感谢了，只是不知道如何用pac自动代理了，在外面其它网络下只能走手动IP+端口
> 
> luci 中请尝试打开“进阶设置”并勾选“部署到公网”

感谢，可行！

**Comment by keeno1982** [comment]
> 
> 
> > @1715173329 可以用了，太感谢了，只是不知道如何用pac自动代理了，在外面其它网络下只能走手动IP+端口
> 
> luci 中请尝试打开“进阶设置”并勾选“部署到公网”

发现个问题，如果勾选部署到公网，反而局域网就失效了，难道鱼与熊掌不能兼得？

**Comment by 1715173329** [comment]
> 发现个问题，如果勾选部署到公网，反而局域网就失效了，难道鱼与熊掌不能兼得？

多看看说明吧

**Comment by llllcccjjj** [comment]
> > 安卓我建议用magisk的本地代理版本
> 
> magisk有点麻烦，有的网银会识别机器已root不让你用，虽然有插件可以避免识别。另外微信也会被锁，后面我就不敢用了

我安卓都是用clash的，多个端win mac都这个，还是挺好用的

**Comment by SpeedPartner** [comment]
> > > 安卓我建议用magisk的本地代理版本
> > 
> > 
> > magisk有点麻烦，有的网银会识别机器已root不让你用，虽然有插件可以避免识别。另外微信也会被锁，后面我就不敢用了
> 
> 我安卓都是用clash的，多个端win mac都这个，还是挺好用的

我是搭在路由器OpenWRT上，WINDOWS走插件，IOS在外面用小火箭，由于endpoint得设置https，不兼容安卓，所以安卓上只能配置本地代理

**Comment by Stonewalling** [comment]
> > > > 安卓我建议用magisk的本地代理版本
> > > 
> > > 
> > > magisk有点麻烦，有的网银会识别机器已root不让你用，虽然有插件可以避免识别。另外微信也会被锁，后面我就不敢用了
> > 
> > 
> > 我安卓都是用clash的，多个端win mac都这个，还是挺好用的
> 
> 我是搭在路由器OpenWRT上，WINDOWS走插件，IOS在外面用小火箭，由于endpoint得设置https，不兼容安卓，所以安卓上只能配置本地代理

大佬，小火箭怎么设置这个啊

**Comment by DrKoschei** [comment]
> 安卓我建议用magisk的本地代理版本

magisk版哪里下载

**Comment by 1715173329** [comment]
猫猫的大喇叭β已经更新了哦，可以试试看~
根据她的测试目前是可以正常工作的
https://github.com/nining377/dolby_beta/releases/tag/v3.0.0
