### ISSUE TITLE
开启后无法签到

### ISSUE THREAD

**Issue by luoxingran** [1715173329/UnblockNeteaseMusic#101]
签到会提示连接服务器失败，咋解决

**Comment by tnnevol** [comment]
签到接口是不是需要更新一下

**Comment by 1715173329** [comment]
信任证书了吗？Android 6.0 正常工作。

**Comment by pan93412** [comment]
> 信任证书了吗？Android 网易云音乐 6.0 版本正常工作。

我的 Mac 和 Web 版本也是一樣噴出這個錯誤。Web 我有看了一下 Network，回傳：

  1) 需要掃碼登入（但實際上不需要）
  2) 簽到時噴 403

**Comment by tnnevol** [comment]
> 信任证书了吗？Android 网易云音乐 6.0 版本正常工作。

我是windows 客户端，用的是网易云的代理工具，应该不需要信任证书。应该是接口出了问题

**Comment by luoxingran** [comment]
所有版本都是用过了会出现403

**Comment by pan93412** [comment]
我最近測試之後發現可以簽到了～ 你們試試看新的 commit？

**Comment by tnnevol** [comment]
> 我最近測試之後發現可以簽到了～ 你們試試看新的 commit？

是的，修复后没毛病了

**Comment by cyao2q** [comment]
网易的问题 已经好了

**Comment by pan93412** [comment]
那我先 close 了，有問題歡迎再提出～
