### ISSUE TITLE
能不能加入解锁音效和动效的功能？

### ISSUE THREAD

**Issue by byludy** [1715173329/UnblockNeteaseMusic#103]
https://github.com/nondanee/UnblockNeteaseMusic/pull/446/files

这边测试还是有效的

**Comment by pan93412** [comment]
好呀，我有空合併。

**Comment by pan93412** [comment]
https://github.com/1715173329/UnblockNeteaseMusic/commit/13887d0995c271df34ac38f6be85b403e66c42cd

已加入，測試可用～
