### ISSUE TITLE
酷我音源的 告白气球 变更为付费歌曲 播放失败

### ISSUE THREAD

**Issue by codexss** [1715173329/UnblockNeteaseMusic#104]
貌似不会自动切换到其他音源
![04D87C80-3645-4C6B-ABFA-F14905E2841B](https://user-images.githubusercontent.com/5959201/129467028-f08507a2-5ce1-4039-9938-8da82ee74e34.png)

**Comment by codexss** [comment]
酷我音源匹配到的连接访问过去之后是403，手动指定migu后可以获取正确的音源。

**Comment by 1715173329** [comment]
> 酷我音源匹配到的连接访问过去之后是403，手动指定migu后可以获取正确的音源。

 目前只能保证获取到数据，但无法保证数据的可靠性。

**Comment by pan93412** [comment]
已經修正囉～你能幫我測試看看這個版本嗎：

https://github.com/1715173329/UnblockNeteaseMusic/runs/3378401477

需要先登入 GitHub 帳戶，然後照著圖片操作。如果你不用預編譯版，也能直接 `git pull`。

<img width="1552" alt="截圖 2021-08-20 上午11 49 27" src="https://user-images.githubusercontent.com/28441561/130176324-b2b6219e-c065-4437-a742-b8a069505489.png">

**Comment by codexss** [comment]
似乎可以正常工作了，谢谢
