### ISSUE TITLE
手机端用杜比大喇叭β运行脚本报错

### ISSUE THREAD

**Issue by HackerLinXL** [1715173329/UnblockNeteaseMusic#107]
运行失败，错误为：TypeError："true" is not a function，之前的包没这个问题，这次更新后首次出现

**Comment by 1715173329** [comment]
不太清楚大喇叭内部是怎么运作的，请教一下猫姐吧。

Cc: @nining377

**Comment by pan93412** [comment]
> 运行失败，错误为：TypeError："true" is not a function，之前的包没这个问题，这次更新后首次出现

是 enhanced 的最新版本，還是最新的 Release 呢？如果可以，希望你能幫我把整個錯誤都截圖下來。謝謝！

**Comment by HackerLinXL** [comment]
> > 运行失败，错误为：TypeError："true" is not a function，之前的包没这个问题，这次更新后首次出现
> 
> 是 enhanced 的最新版本，還是最新的 Release 呢？如果可以，希望你能幫我把整個錯誤都截圖下來。謝謝！

是enhanced的最新版本，就是大佬你最新修改的那个
![Screenshot_2021-08-16-23-47-10-695_com netease cloudmusic](https://user-images.githubusercontent.com/86948949/129591902-1167b207-9bca-4f5b-b7b3-17072079f7bd.jpg)
点击一首歌会这样
![Uploading Screenshot_2021-08-16-23-47-30-964_com.netease.cloudmusic.jpg…]()

**Comment by 1715173329** [comment]
请使用 Node.js 10+ 版本

**Comment by pan93412** [comment]
> 请使用 Node.js 10+ 版本

`TypeError："true" is not a function` 很有可能是網易雲音樂自己的 Node.js runtime 出錯。這部分有待確認。我不用手機版所以不太好定位原因 orz

@1715173329 你有 android 版 neteasemusic 嗎？可以幫我 check 一下嗎 orz

**Comment by 1715173329** [comment]
> `TypeError："true" is not a function` 很有可能是網易雲音樂自己的 Node.js runtime 出錯。

这个应该是杜比大喇叭的 error log，并非网易云音乐本身。
大概需要 nodejs 的运行日志才能判断问题。

**Comment by pan93412** [comment]
> > `TypeError："true" is not a function` 很有可能是網易雲音樂自己的 Node.js runtime 出錯。
> 
> 这个应该是杜比大喇叭的 error log，并非网易云音乐本身。
> 大概需要 nodejs 的运行日志才能判断问题。

真的欸，我沒看到第二張圖wwww

@HackerLinXL 你試試看這個？我是用 Node.js v16，正常運作：

https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-x64.tar.xz

BTW 你手機是 Intel Atom？發現到你用的是 x64 而不是常見的 armv8。

**Comment by 1715173329** [comment]
https://github.com/nining377/dolby_beta/blob/a1b240955ab17e45037bcb0bc44c31f66a979570/app/src/main/java/com/raincat/dolby_beta/hook/UnblockMusicHook.java#L227

错误是这一行导致的，因为最近重新格式化了代码，这里不能这么写了。
```patch
diff --git a/app/src/main/java/com/raincat/dolby_beta/hook/UnblockMusicHook.java b/app/src/main/java/com/raincat/dolby_beta/hook/UnblockMusicHook.java
index 9214cce..f7cbea4 100644
--- a/app/src/main/java/com/raincat/dolby_beta/hook/UnblockMusicHook.java
+++ b/app/src/main/java/com/raincat/dolby_beta/hook/UnblockMusicHook.java
@@ -224,9 +224,9 @@ public class UnblockMusicHook {
         for (int i = 0; i < scriptList.size(); i++) {
             if (scriptList.get(i).contains("item.code") && scriptList.get(i).contains("item.freeTrialInfo")) {
                 if (Setting.isForceEnabled())
-                    scriptList.set(i, "\t\tif ((item.code != 200 || item.freeTrialInfo || item.br <= 128000) && (target == 0 || item.id == target)) {");
+                    scriptList.set(i, "\t\t(item.code != 200 || item.freeTrialInfo || item.br <= 128000) &&");
                 else
-                    scriptList.set(i, "\t\tif ((item.code != 200 || item.freeTrialInfo) && (target == 0 || item.id == target)) {");
+                    scriptList.set(i, "\t\t(item.code != 200 || item.freeTrialInfo) &&");
                 break;
             }
         }
```

**Comment by HackerLinXL** [comment]
> > > `TypeError："true" is not a function` 很有可能是網易雲音樂自己的 Node.js runtime 出錯。
> > 
> > 
> > 这个应该是杜比大喇叭的 error log，并非网易云音乐本身。
> > 大概需要 nodejs 的运行日志才能判断问题。
> 
> 真的欸，我沒看到第二張圖wwww
> 
> @HackerLinXL 你試試看這個？我是用 Node.js v16，正常運作：
> 
> https://nodejs.org/dist/v16.6.2/node-v16.6.2-linux-x64.tar.xz
> 
> BTW 你手機是 Intel Atom？發現到你用的是 x64 而不是常見的 armv8。

不是，我手机是小米6

**Comment by HackerLinXL** [comment]
杜比大喇叭β更新2.1.1后已可以正常使用，感谢@pan93412 @1715173329 @nining377 几位大佬的贡献！十分感谢！
