### ISSUE TITLE
能不能自动编译最新文件

### ISSUE THREAD

**Issue by byludy** [1715173329/UnblockNeteaseMusic#108]
能不能自动编译最新文件  这样比较方便

**Comment by pan93412** [comment]
真的很抱歉 orz 忘記處理你的 issue

目前是卡在我不確定有沒有除了 GitHub Releases 之外的 binary 上傳管道。先標 `help wanted`

**Comment by 1715173329** [comment]
> 真的很抱歉 orz 忘記處理你的 issue
> 
> 目前是卡在我不確定有沒有除了 GitHub Releases 之外的 binary 上傳管道。先標 `help wanted`

可以通过 GitHub Actions Artifacts 上传。

**Comment by pan93412** [comment]
> > 真的很抱歉 orz 忘記處理你的 issue
> > 
> > 目前是卡在我不確定有沒有除了 GitHub Releases 之外的 binary 上傳管道。先標 `help wanted`
> 
> 可以通过 GitHub Actions Artifacts 上传。

Archifact 不是只有 Actions 自己可以 fetch？

**Comment by 1715173329** [comment]
> Archifact 不是只有 Actions 自己可以 fetch？

是，但我们也正在使用 actions 打包二进制文件呀

**Comment by pan93412** [comment]
> > Archifact 不是只有 Actions 自己可以 fetch？
> 
> 是，但我们也正在使用 actions 打包二进制文件呀

我們現在是把 binary 傳到最新的 Release 喔，不是儲存在 Actions 裡面。

**Comment by 1715173329** [comment]
> 我們現在是把 binary 傳到最新的 Release 喔，不是儲存在 Actions 裡面。

刚才理解错了你的意思。
Archifacts 的文件只要登录了 GitHub 便可以下载。

**Comment by pan93412** [comment]
> > 我們現在是把 binary 傳到最新的 Release 喔，不是儲存在 Actions 裡面。
> 
> 刚才理解错了你的意思。
> Archifacts 的文件只要登录了 GitHub 便可以下载。

emmmm 那你把現在的 Action 複製一份，然後把 push to release 改成 push to archifact？
