### ISSUE TITLE
can not load some songs in strict mode

### ISSUE THREAD

**Issue by GrayXu** [1715173329/UnblockNeteaseMusic#109]
strict mode下无法加载某些歌曲，关闭strict mode后正常。  
客户端版本 2.9.1 (Build:199099) (Patch:1:ae2fbe6). 
8dd9d22
例子 LIKEY-TWICE, log:
```
HTTP Server running @ http://0.0.0.0:10000
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
MITM > music.163.com
[515647526] LIKEY
http://other.player.nf01.sycdn.kuwo.cn/a6c7454c85740cb4cc9f0c8d66d4bd97/611e3bc6/resource/n2/42/76/900613952.mp3
MITM > music.163.com
MITM > music.163.com
```

不开strict端口老是被扫。。

**Comment by pan93412** [comment]
我自己日常使用的 UnblockNeteaseMusic 就是 strict 模式。

<img width="1114" alt="截圖 2021-08-19 下午7 28 19" src="https://user-images.githubusercontent.com/28441561/130061063-46d2763e-7b30-4fa9-b16c-05e14b1d774b.png">

這個是我的設定參數，你可以參考看看～

<img width="842" alt="截圖 2021-08-19 下午7 28 28" src="https://user-images.githubusercontent.com/28441561/130061081-a8b50d07-bfcd-4d14-8025-b593118536b5.png">

我這裡輸出的 Log：

<img width="842" alt="截圖 2021-08-19 下午7 28 48" src="https://user-images.githubusercontent.com/28441561/130061113-2615b150-a7e6-4de9-b1be-b08eec9b2874.png">

---

我這裡測試時，發現之前沒播放過的音樂需要關掉 NeteaseMusic 重開才能正常播放。你試試看完全關閉 NeteaseMusic 後重新打開並播放 TWICE - LIKEY，應該就能運作囉～

**Comment by GrayXu** [comment]
@pan93412 感谢回复👍！参考你的配置，我没有传入运行参数`-e https://music.163.com`，增加后工作正常。
