### ISSUE TITLE
建议发布镜像到 docker hub

### ISSUE THREAD

**Issue by gqbre** [1715173329/UnblockNeteaseMusic#110]
众所周知原项目停止维护了，docker hub 上的镜像停留在了一年前。
群晖用户翘首企盼.. 十分感谢

**Comment by pan93412** [comment]
好～

**Comment by pan93412** [comment]
@1715173329 你要不要註冊一個 Docker Hub 帳戶？還是直接用我自己的（？

**Comment by 1715173329** [comment]
> @1715173329 你要不要註冊一個 Docker Hub 帳戶？還是直接用我自己的（？

用你的吧，我不太懂 docker
麻烦你了❤️

**Comment by whosydd** [comment]
https://hub.docker.com/repository/docker/whosydd/unblock-netease-music
fork该仓库直接构建的，未做任何修改，当前版本0.26.1，可以先用着

@pan93412 话说我也在等docker镜像，刚想提issue。。。

**Comment by pan93412** [comment]
Hi all @whosydd @gqbre :)

現在已經會自動 push 到 [pan93412/unblock-netease-music-enhanced](https://hub.docker.com/repository/docker/pan93412/unblock-netease-music-enhanced) 了，詳細資訊可以看一下上面的 commit。

CI 的自動編譯是這樣分：

  - 一般提交會 push 到 `develop`
  - 有 tagged 就上 `released` 和對應的 tag name

此外，Docker Image 現在也支援以下四個平台：

  - `linux/amd64`
  - `linux/arm64`
  - `linux/arm/v6`
  - `linux/arm/v7`.

有什麼問題歡迎再提出唷！:P

**Comment by pan93412** [comment]
https://github.com/1715173329/UnblockNeteaseMusic/commit/346d423d332c7c9a20ab5663cabba025697a84b4

這裡也加上你們的名字了。謝謝～～
