### ISSUE TITLE
ios端口能放不能下

### ISSUE THREAD

**Issue by phk1042791021** [1715173329/UnblockNeteaseMusic#112]
卡在正在计算文件大小
Error: connect ETIMEDOUT 45.114.11.238:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '45.114.11.238',
  port: 443
}
播放正常
已信任证书，设置了endpoint，hd版下载正常

**Comment by pan93412** [comment]
> 卡在正在计算文件大小
> Error: connect ETIMEDOUT 45.114.11.238:443
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
> errno: -60,
> code: 'ETIMEDOUT',
> syscall: 'connect',
> address: '45.114.11.238',
> port: 443
> }
> 播放正常
> 已信任证书，设置了endpoint，hd版下载正常

我的 macOS 版本也能下載。先標成 `help wanted`

**Comment by kksxsyj** [comment]
老哥怎么设置endpoint？

**Comment by pan93412** [comment]
用 `-e` 選項：

```
usage: unblockneteasemusic [-v] [-p port] [-a address] [-u url] [-f host]
                           [-o source [source ...]] [-t token] [-e url] [-s]
                           [-h]

  -e url, --endpoint url          將虛擬的 endpoint 更換程公開主機
```

**Comment by kksxsyj** [comment]
> 用 `-e` 选项：
> 
> ```
> usage: unblockneteasemusic [-v] [-p port] [-a address] [-u url] [-f host]
>                            [-o source [source ...]] [-t token] [-e url] [-s]
>                            [-h]
> 
>   -e url, --endpoint url          将虚拟的 endpoint 更换成公开主机
> ```
> 
> 范例：
> 
> ```
> node app.js -e 1.1.1.1
> ```

> 用 `-e` 选项：
> 
> ```
> usage: unblockneteasemusic [-v] [-p port] [-a address] [-u url] [-f host]
>                            [-o source [source ...]] [-t token] [-e url] [-s]
>                            [-h]
> 
>   -e url, --endpoint url          将虚拟的 endpoint 更换成公开主机
> ```
> 
> 范例：
> 
> ```
> node app.js -e 1.1.1.1
> ```

好的好的，感谢感谢

**Comment by phk1042791021** [comment]
> > 卡在正在计算文件大小
> > Error: connect ETIMEDOUT 45.114.11.238:443
> > at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
> > errno: -60,
> > code: 'ETIMEDOUT',
> > syscall: 'connect',
> > address: '45.114.11.238',
> > port: 443
> > }
> > 播放正常
> > 已信任证书，设置了endpoint，hd版下载正常
> 
> 我的 macOS 版本也能下載。先標成 `help wanted`

TUNNEL > localhost:8081
MITM > clientlog3.music.163.com (ssl)
TUNNEL > localhost:8081
MITM > clientlog3.music.163.com (ssl)
TUNNEL > localhost:8081
MITM > clientlog3.music.163.com (ssl)
TUNNEL > localhost:8081
TUNNEL > localhost:8081
TUNNEL > localhost:8081
MITM > clientlog3.music.163.com (ssl)
TUNNEL > localhost:8081
MITM > clientlog3.music.163.com (ssl)
TUNNEL > localhost:8081
MITM > sl.sycdn.kuwo.cn 
大佬，我又看了一下记录，log中tunnel一直是localhost，我看了一下别人的log似乎都是music.163.com:443之类的，
8081是默认启动的https端口，如果代理中直接设置链接的端口为8081，那就直接不生效了，歌曲都是灰色的

**Comment by pan93412** [comment]
> > > 卡在正在计算文件大小
> > > Error: connect ETIMEDOUT 45.114.11.238:443
> > > at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
> > > errno: -60,
> > > code: 'ETIMEDOUT',
> > > syscall: 'connect',
> > > address: '45.114.11.238',
> > > port: 443
> > > }
> > > 播放正常
> > > 已信任证书，设置了endpoint，hd版下载正常
> > 
> > 
> > 我的 macOS 版本也能下載。先標成 `help wanted`
> 
> TUNNEL > localhost:8081
> MITM > clientlog3.music.163.com (ssl)
> TUNNEL > localhost:8081
> MITM > clientlog3.music.163.com (ssl)
> TUNNEL > localhost:8081
> MITM > clientlog3.music.163.com (ssl)
> TUNNEL > localhost:8081
> TUNNEL > localhost:8081
> TUNNEL > localhost:8081
> MITM > clientlog3.music.163.com (ssl)
> TUNNEL > localhost:8081
> MITM > clientlog3.music.163.com (ssl)
> TUNNEL > localhost:8081
> MITM > sl.sycdn.kuwo.cn
> 大佬，我又看了一下记录，log中tunnel一直是localhost，我看了一下别人的log似乎都是music.163.com:443之类的，
> 8081是默认启动的https端口，如果代理中直接设置链接的端口为8081，那就直接不生效了，歌曲都是灰色的

試試看  https://github.com/1715173329/UnblockNeteaseMusic/issues/109#issuecomment-901837663 的解決方法？

**Comment by phk1042791021** [comment]
我是用的就是这个启动命令，不行

> #109 (comment)

还行不是，还试了几个老版本都是一样的问题，看日志明明获取到了歌曲文件，直接复制进浏览器也可以下载，但网易云里就是卡在待下载或者正在获取文件大小
下载相比播放多了MITM > clientlog3.music.163.com (ssl)

**Comment by pan93412** [comment]
> 我是用的就是这个启动命令，不行
> 
> > #109 (comment)
> 
> 还行不是，还试了几个老版本都是一样的问题，看日志明明获取到了歌曲文件，直接复制进浏览器也可以下载，但网易云里就是卡在待下载或者正在获取文件大小
> 下载相比播放多了MITM > clientlog3.music.163.com (ssl)

喔喔喔喔，原來是下載的問題。下載的話我自己問題也不少，你可以試試看取消目前的下載任務之後重新下載，如果還是不行就是重開。

但既然你都收到 MP3 網址了，其實直接下載也不是不行（

**Comment by phk1042791021** [comment]
恩恩。我先放弃了，ios也暂时没想到什么曲线救国的方案，只能让他缓存一边，不清缓存的话倒是可以听。

**Comment by 1715173329** [comment]
iOS 网易云音乐版本号 8.2.21，目前已经可以正常下载。
