### ISSUE TITLE
部分歌曲似乎无法替换

### ISSUE THREAD

**Issue by a6513375** [1715173329/UnblockNeteaseMusic#113]
![歌曲](https://user-images.githubusercontent.com/52791712/130238562-6c3c9e38-0517-4b65-b5a8-573780703c60.png)

![代理设置正常](https://user-images.githubusercontent.com/52791712/130238570-8edad830-407d-4d4e-8a94-c07ee6768bd1.png)

如图 代理正确设置 但是似乎部分歌曲（如 http://music.163.com/song?id=725692&userid=1421465659 ）无法替换

**Comment by 1715173329** [comment]
那说明在默认音源中找不到匹配歌曲。
这类音乐网易云音乐自身有版权，你可以追加使用 pyncmd 音源。

**Comment by pan93412** [comment]
> 那说明在默认音源中找不到匹配歌曲。
> 这类音乐网易云音乐自身有版权，你可以追加使用 pyncmd 音源。

pyncmd 又復活了喔？

**Comment by 1715173329** [comment]
> pyncmd 又復活了喔？

嗯（

**Comment by a6513375** [comment]
> > pyncmd 又復活了喔？
> 
> 嗯（

pyncmd是啥（？

**Comment by 1715173329** [comment]
> pyncmd是啥（？

由 https://github.com/greats3an/pyncmd 项目提供的示例接口。

**Comment by pan93412** [comment]
pyncmd 就是好心人提供的網易雲音樂黑膠帳號。你可以用 `-o`（自訂音源）指定，比如：

```bash
node app.js -o pyncmd kugou kuwo migu youtube
```

因為自訂音源會覆蓋預設設定，假如你還想要使用我們預設精選的音源，
也要把我們預設採用的音源加上去唷！（上面的指令就已經幫你加好了）

**Comment by a6513375** [comment]
> pyncmd 就是好心人提供的網易雲音樂黑膠帳號。你可以用 `-o`（自訂音源）指定，比如：
> 
> ```shell
> node app.js -o pyncmd kugou kuwo migu youtube
> ```
> 
> 因為自訂音源會覆蓋預設設定，假如你還想要使用我們預設精選的音源，
> 也要記得把那些音源加上去唷！（上面的指令就已經幫你加好了）

ok 谢谢

**Comment by pan93412** [comment]
音樂能否替換很大取決於選擇的音源，屬於 `wontfix` 的問題。先關了，如果有類似問題歡迎繼續討論 :)

關於 pyncmd 相關討論請移駕至 #116。
