### ISSUE TITLE
pyncmd音源似乎无法正常使用

### ISSUE THREAD

**Issue by a6513375** [1715173329/UnblockNeteaseMusic#116]
启动命令行为node app.js -o pyncmd kugou kuwo migu youtube
版本为目前最新code

使用此命令行启动后pyncmd音源不生效
我修改了处理pyncmd音源的代码
似乎部分代码为被执行 

修改的代码
![截图](https://user-images.githubusercontent.com/52791712/130302561-0d698ed7-ed1e-45e4-90b8-a46f18fb2672.png)
实际运行结果
![截图](https://user-images.githubusercontent.com/52791712/130302684-9ba2149f-55ff-4702-b68c-a64b42e113a4.png)

**Comment by pan93412** [comment]
pyncmd 老實說我也不知道怎麼回事⋯⋯我自己也用不了 @1715173329

**Comment by a6513375** [comment]
> pyncmd 老實說我也不知道怎麼回事⋯⋯我自己也用不了 @1715173329

奇怪了 我把Https换成Http就正常了

![}6`0S4198BX(EUM~UD O)FB](https://user-images.githubusercontent.com/52791712/130317114-65c66dcb-f2f5-4b43-acc4-80585d34a63b.png)

似乎request在处理https时会出现问题？

**Comment by pan93412** [comment]
#117 merged. Closed now.
