### ISSUE TITLE
在网易云中添加代理后，重启软件显示无网络

### ISSUE THREAD

**Issue by scholesjiang** [1715173329/UnblockNeteaseMusic#1164]
### Bug 描述

用windows，docker和openwrt三种方式都试了下，搭建服务后，在网易云程序中设置代理服务器和端口，点测试显示可用，但是点确定重启软件后，显示无网络，无法搜索和播放任何歌曲，请问是我设置的问题么？

### 日志内容

这个不太会弄

### 网易云音乐版本号

2.10.11

### 操作系统

windows

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by jxLYH6134** [comment]
这看起来很像证书没有正确配置的样子。
请检查你的CA 证书是否安装在了“受信任的根证书颁发机构”内
![image](https://github.com/UnblockNeteaseMusic/server/assets/48689047/5b47b8b1-1b02-4bf6-887c-431fd61b58cf)

**Comment by jxLYH6134** [comment]
> 这看起来很像证书没有正确配置的样子。 请检查你的CA 证书是否安装在了“受信任的根证书颁发机构”内 ![image](https://user-images.githubusercontent.com/48689047/253052593-5b47b8b1-1b02-4bf6-887c-431fd61b58cf.png)

在正确安装证书的情况下，在浏览器打开网易云音乐网站将不会提示不安全链接。并且证书由UnblockNeteaseMusic Root签发而不是DigiCert
![image](https://github.com/UnblockNeteaseMusic/server/assets/48689047/dd502808-52f0-442e-9841-40d11a8fa2c8)

**Comment by Leonshay** [comment]
我的也是这样，但是我试了网页是可以正常用的只是客户端用不了

**Comment by xietian19981121** [comment]
我之前也这样，更新版本之后就好了；旧版好像有问题

**Comment by Inkarro** [comment]
[安裝 UNM 的 HTTPS 憑證](https://github.com/UnblockNeteaseMusic/server/discussions/426)

**Comment by ilyng** [comment]
亲测安装完证书之后可以访问了。这应该不算bug
