### ISSUE TITLE
如何更改程序的语言 

### ISSUE THREAD

**Issue by saman-magnus** [1715173329/UnblockNeteaseMusic#1167]
### 需求描述

How to change the language of the program
如何更改程序的语言

### 预期行为

我正在尝试将程序语言更改为波斯语。 请帮忙
I am trying to change the program language to Farsi.
 please help

### 网易云音乐版本号

lastversion

### 操作系统

ubuntu server

**Comment by pan93412** [comment]
UNM only provides an English version. We don't have plans to internationalize the program at this time. Sorry :(
