### ISSUE TITLE
提示typeerror

### ISSUE THREAD

**Issue by mario6714** [1715173329/UnblockNeteaseMusic#1168]
### Bug 描述

typeerror:cannot read properties of undefined(reading 'list')

### 复现步骤

只需打开网易应用程序

### 日志内容

typeerror:cannot read properties of undefined(reading 'list')

### 网易云音乐版本号

8.8.45

### 操作系统

Windows and Android

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
您的日志是按长度收费吗？

**Comment by mario6714** [comment]
> 

Something like this?

![imagen](https://github.com/UnblockNeteaseMusic/server/assets/32179719/c713cb96-81a2-4b68-af59-633d5d8688d3)

![imagen](https://github.com/UnblockNeteaseMusic/server/assets/32179719/2b707b6b-035c-41de-8ea0-f75d3a5b4ab3)

**Comment by milo1023** [comment]
message: 'CSRF token Invalid!',

**Comment by 1715173329** [comment]
去 actions 里面下最新的构建版本即可

EDIT：又改了 api

**Comment by 1715173329** [comment]
Fixed in latest release.

**Comment by mario6714** [comment]
Thanks
