### ISSUE TITLE
本地 VIP 支持网易云V3.0 beta

### ISSUE THREAD

**Issue by aliencaocao** [1715173329/UnblockNeteaseMusic#1170]
### 需求描述

目前测试歌曲解锁功能正常，但是vip功能貌似挂了，我本来是黑胶vip，开了解锁svip，V2.10.10可以正常解锁svip但是V3.0不行了

### 网易云音乐版本号

V3.0.0 beta build 201589

### 操作系统

Win 10

**Comment by 1715173329** [comment]
#1175

**Comment by aldev814** [comment]
更新到最新版本，测试依然无法实现本地svip。是否是我少开启了某个选项？

版本号也是V3.0.0 beta build 201589；系统Win11

server已经更新到仓库最新commit

环境变量只设置了ENABLE_LOCAL_VIP="svip"

参数为这个-p 52100:52101 -o bilibili kuwo kugou -a localhost -e https://music.163.com

![屏幕截图 2023-07-22 101048](https://github.com/UnblockNeteaseMusic/server/assets/6133401/cf1517ee-1fde-4f80-8388-fcb751f02457)

**Comment by artiga033** [comment]
> server已经更新到仓库最新commit

`enhance` branch的commit还没有更新bundle文件，可以先用`ci/build-precompiled`这个分支

**Comment by aldev814** [comment]
> > server已经更新到仓库最新commit
> 
> `enhance` branch的commit还没有更新bundle文件，可以先用`ci/build-precompiled`这个分支

感谢，已经可以正常使用了
