### ISSUE TITLE
系统服务状态下自定义端口不可用

### ISSUE THREAD

**Issue by axelpln** [1715173329/UnblockNeteaseMusic#1171]
### Bug 描述

当UNM以系统服务运行时，nw.js中的自定义端口不可用，服务只会以默认的8080端口运行，卸载重装服务也无济于事
`const Service = require('node-windows').Service;

const svc = new Service({
	name: 'Unblock Netease Cloud Music',
	description: '点亮网易云音乐灰色歌曲',
	script: './app.js', // 入口文件路径
	scriptOptions: '-p 4529:4530', // 可选参数示例: 自定义端口并开启HTTPS
	scriptOptions: '-o pyncmd kuwo kugou migu', // 可选参数
	wait: '1', // 程序崩溃后重启时间间隔
	grow: '0.25', // 重启等待时间成长值，第一次1秒，第二次1.25秒。。。
	maxRestarts: '40', // 60秒内最大重启次数
	env: [
		{
			name: 'ENABLE_FLAC',
		 	value: 'true',
		},
		{
			name: 'DISABLE_UPGRADE_CHECK',
		 	value: 'true',
		},
		{
			name: 'BLOCK_ADS',
		 	value: 'true',
		},
		{
			name: 'ENABLE_LOCAL_VIP',
			value: 'true',
		},
		{
			name: 'FOLLOW_SOURCE_ORDER',
		 	value: 'true',
		},
		// {
		// 	name: 'QQ_COOKIE',
		// 	value: 'uin=<your_uin>; qm_keyst=<your_qm_keyst>',
		// },
	],
});

// 监听
svc.on('install', () => {
	svc.start();
	console.log('Installation completed.');
});
svc.on('uninstall', () => console.log('Uninstallation completed.'));

// 卸载
if (svc.exists) return svc.uninstall();

// 安装
svc.install();
`
顺带一提，修改nw.js中的内容需要重新安装一遍服务吗？

### 预期行为

更改端口使用参数能够有效

### 日志内容

INFO: (app) HTTP Server running @ http://0.0.0.0:8080
INFO: (app) HTTPS Server running @ http://0.0.0.0:8081
DEBUG: (server) TUNNEL
    url: "web.push.126.net:6003"
DEBUG: (server) TUNNEL
    url: "localhost:8081"

### 网易云音乐版本号

PC 2.10.11

### 操作系统

Windows 11 22H2

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
上面的 scriptOptions 被下面的覆盖了吧，你写在一行看看呢

**Comment by axelpln** [comment]
> 上面的 scriptOptions 被下面的覆盖了吧，你写在一行看看呢

我把端口参数加载音源参数后面然后再重装一遍服务就可以了（直接修改 \daemon\unblockneteasecloudmusic.xml 也可以，才发现服务端运行不依赖nw.js）
