### ISSUE TITLE
[酷我音源] 提示typeerror

### ISSUE THREAD

**Issue by mario6714** [1715173329/UnblockNeteaseMusic#1173]
### Bug 描述

ERROR: (provider/match) Cannot read properties of undefined (reading 'list')

### 复现步骤

 TypeError: Cannot read properties of undefined (reading 'list')

### 日志内容

INFO: (app) HTTP Server running @ http://0.0.0.0:8080
INFO: (app) HTTPS Server running @ http://0.0.0.0:8081
DEBUG: (server) TUNNEL
    url: "st.music.163.com:443"
DEBUG: (server) TUNNEL
    url: "acstatic-dun.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "raw.githubusercontent.com:443"
DEBUG: (server) TUNNEL
    url: "cdn.jsdelivr.net:443"
DEBUG: (server) TUNNEL
    url: "betterncm.microblock.cc:443"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "ac.dun.163.com:443"
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (hook) unblockLyricsEffects() has been triggered.
DEBUG: (server) TUNNEL
    url: "web.push.126.net:6003"
DEBUG: (server) TUNNEL
    url: "p3.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p4.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p4.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p3.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p4.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p3.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p3.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "p1.music.126.net:443"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/find"
DEBUG: (cache) 19292984 did not hit. Storing the execution result...
    logKey: 19292984
    cacheStorageId: "provider/find"
DEBUG: (request) Start requesting https://music.163.com/api/song/detail?ids=[19292984]
DEBUG: (provider/match) Getting the audio...
    source: "kuwo"
    info: {
      "name": "Love Story",
      "id": 19292984,
      "alias": [],
      "duration": 236251,
      "album": {
        "name": "Fearless",
        "id": 1770438
      },
      "artists": [
        {
          "name": "Taylor Swift",
          "id": 44266
        }
      ],
      "keyword": "Love Story - Taylor Swift"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/kuwo"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/kuwo"
DEBUG: (request) Start requesting http://www.kuwo.cn/api/www/search/searchMusicBykeyWord?key=Love%20Story%20Taylor%20Swift&pn=1&rn=30
DEBUG: (provider/match) Getting the audio...
    source: "kugou"
    info: {
      "name": "Love Story",
      "id": 19292984,
      "alias": [],
      "duration": 236251,
      "album": {
        "name": "Fearless",
        "id": 1770438
      },
      "artists": [
        {
          "name": "Taylor Swift",
          "id": 44266
        }
      ],
      "keyword": "Love Story - Taylor Swift"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/kugou"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/kugou"
DEBUG: (request) Start requesting http://mobilecdn.kugou.com/api/v3/search/song?keyword=Love%20Story%20-%20Taylor%20Swift&page=1&pagesize=10
DEBUG: (provider/match) Getting the audio...
    source: "migu"
    info: {
      "name": "Love Story",
      "id": 19292984,
      "alias": [],
      "duration": 236251,
      "album": {
        "name": "Fearless",
        "id": 1770438
      },
      "artists": [
        {
          "name": "Taylor Swift",
          "id": 44266
        }
      ],
      "keyword": "Love Story - Taylor Swift"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/migu"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/migu"
DEBUG: (request) Start requesting https://m.music.migu.cn/migu/remoting/scr_search_tag?keyword=Love%20Story%20-%20Taylor%20Swift&type=2&rows=20&pgc=1
DEBUG: (provider/match) Getting the audio...
    source: "pyncmd"
    info: {
      "name": "Love Story",
      "id": 19292984,
      "alias": [],
      "duration": 236251,
      "album": {
        "name": "Fearless",
        "id": 1770438
      },
      "artists": [
        {
          "name": "Taylor Swift",
          "id": 44266
        }
      ],
      "keyword": "Love Story - Taylor Swift"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/pyncmd"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/pyncmd"
DEBUG: (request) Start requesting http://76.76.21.21/api/pyncm?module=track&method=GetTrackAudio&song_ids=19292984&bitrate=999000
ERROR: (provider/match) Cannot read properties of undefined (reading 'list')
    TypeError: Cannot read properties of undefined (reading 'list')
        at C:\snapshot\server\precompiled\app.js
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async u.cache (C:\snapshot\server\precompiled\app.js)
        at async m (C:\snapshot\server\precompiled\app.js)
        at async Promise.any (index 0)
        at async b (C:\snapshot\server\precompiled\app.js)
        at async Promise.all (index 0)
DEBUG: (server) TUNNEL
    url: "localhost:8081"
DEBUG: (request) Start requesting http://trackercdn.kugou.com/i/v2/?key=a410883e7eb404c27f3c8953f736b11d&hash=4084865526fb1f0a0044b51d80d26a36&appid=1005&pid=2&cmd=25&behavior=play&album_id=13721135
DEBUG: (request) Start requesting http://trackercdn.kugou.com/i/v2/?key=2a308def450f00e56a73d083855e6258&hash=e414d69c74cca08701dddd41dabdbe52&appid=1005&pid=2&cmd=25&behavior=play&album_id=13721135
DEBUG: (request) Start requesting http://trackercdn.kugou.com/i/v2/?key=6e90c8ac6ccbc9a89c348074b5c3ffe7&hash=5584885dbcde1e8cdf7350047bf2a2e6&appid=1005&pid=2&cmd=25&behavior=play&album_id=13721135
DEBUG: (request) Start requesting https://app.c.nf.migu.cn/MIGUM2.0/strategy/listen-url/v2.4?netType=01&resourceType=2&songId=1134318420&toneFlag=ZQ24
DEBUG: (request) Start requesting https://app.c.nf.migu.cn/MIGUM2.0/strategy/listen-url/v2.4?netType=01&resourceType=2&songId=1134318420&toneFlag=SQ
DEBUG: (request) Start requesting https://app.c.nf.migu.cn/MIGUM2.0/strategy/listen-url/v2.4?netType=01&resourceType=2&songId=1134318420&toneFlag=HQ
DEBUG: (request) Start requesting https://app.c.nf.migu.cn/MIGUM2.0/strategy/listen-url/v2.4?netType=01&resourceType=2&songId=1134318420&toneFlag=PQ
DEBUG: (request) Start requesting http://m701.music.126.net/20230718132022/ac4be276e9068c3920fc3856328e797f/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/14096645023/e0b7/d29b/4d84/72fd1731a63dc6514c462adad71cd524.mp3
DEBUG: (provider/match) The matched song is:
    size: 9452191
    br: 320000
    url: "http://m701.music.126.net/20230718132022/ac4be276e9068c3920fc3856328e797f/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/14096645023/e0b7/d29b/4d84/72fd1731a63dc6514c462adad71cd524.mp3"
    md5: "72fd1731a63dc6514c462adad71cd524"
DEBUG: (provider/match) The audio matched!
    source: "pyncmd"
    info: {
      "name": "Love Story",
      "id": 19292984,
      "alias": [],
      "duration": 236251,
      "album": {
        "name": "Fearless",
        "id": 1770438
      },
      "artists": [
        {
          "name": "Taylor Swift",
          "id": 44266
        }
      ],
      "keyword": "Love Story - Taylor Swift"
    }
DEBUG: (provider/match) The data to replace:
    audioInfo: {
      "name": "Love Story",
      "id": 19292984,
      "alias": [],
      "duration": 236251,
      "album": {
        "name": "Fearless",
        "id": 1770438
      },
      "artists": [
        {
          "name": "Taylor Swift",
          "id": 44266
        }
      ],
      "keyword": "Love Story - Taylor Swift"
    }
    audioData: {
      "size": 9452191,
      "br": 320000,
      "url": "http://m701.music.126.net/20230718132022/ac4be276e9068c3920fc3856328e797f/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/14096645023/e0b7/d29b/4d84/72fd1731a63dc6514c462adad71cd524.mp3",
      "md5": "72fd1731a63dc6514c462adad71cd524"
    }
INFO: (provider/match) Replaced: [19292984] Love Story
    audioId: 19292984
    songName: "Love Story"
    url: "http://m701.music.126.net/20230718132022/ac4be276e9068c3920fc3856328e797f/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/14096645023/e0b7/d29b/4d84/72fd1731a63dc6514c462adad71cd524.mp3"
DEBUG: (server) TUNNEL
    url: "localhost:8081"

### 网易云音乐歌曲链接

https://music.163.com/song?id=19292984&userid=114163009

### 网易云音乐版本号

2.10.11

### 操作系统

Windows and Android

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
你这不是已经获取到了可以播放的音源？就不必管了。

酷我又改了搜索 api 的 csrf 算法，这只能表明酷我不愿意再让其他程序引用，或许本项目已经遭到了不必要的关注。你可以自己尝试去抓一组可用的 Hm_token 和 Cross 组合填入。

且用且珍惜吧。

**Comment by mario6714** [comment]
Thanks
