### ISSUE TITLE
大佬能弄一下xp模块吗

### ISSUE THREAD

**Issue by bingcha12138** [1715173329/UnblockNeteaseMusic#1183]
### 需求描述

目前只有大佬你的UnblockNeteaseMusic还在更新，安卓上面的早就不更新，最近也失效了。大佬能弄一下xp模块吗？

**Comment by Khada-Jhin8** [comment]
用杜比大喇叭设置自定义音源

**Comment by bingcha12138** [comment]
> 用杜比大喇叭设置自定义音源

大喇叭在哪里设置？我没看到

**Comment by mario6714** [comment]
> > 用杜比大喇叭设置自定义音源
> 
> 大喇叭在哪里设置？我没看到

https://github.com/nining377/dolby_beta

https://github.com/nining377/dolby_beta/actions/runs/5663381961

https://github.com/nining377/dolby_beta/pull/342
