### ISSUE TITLE
自建音源功能

### ISSUE THREAD

**Issue by fmwww** [1715173329/UnblockNeteaseMusic#1193]
### 需求描述

现在好多音源都不能用了，我觉得是时候添加自建音源功能了。具体功能描述如下

1. 带有配置界面，可以通过代理一个特殊的域名访问配置页面，例如unblock-music.com
2. 代理可以记录下所有灰色歌曲，配置界面可以显示这些灰色歌曲的列表（可能需要结合数据库或者直接写入本地文件）
3. 可以对每一首灰色歌曲配置音源，也可以设置指定的歌曲url链接，亦或者是本地音乐文件（也可以自己上传本地歌曲）

如果能实现这些我觉得基本可以摆脱音源不够用的困扰了，我这边可以帮忙实现前端页面，如果有需要的话可以联系我

**Comment by yrx2324** [comment]
网易云音乐云盘是不是差不多功能

**Comment by fmwww** [comment]
> 网易云音乐云盘是不是差不多功能

不一样，可能使用上来说差不多，但是底层的逻辑是不一样的，一个是基于已有歌曲的修改，一个是相当于创建新的歌曲，肯定是会有差别的

**Comment by SpikeOXO** [comment]
能否考虑自建webdav 作为音源，例如 alist 通过网易云客户端请求到中间代理，中间代理在重定向到 alist

**Comment by 1715173329** [comment]
音源部分参阅 pyncmd 就行了，至于请求那套 api 就需要自行实现了。
