### ISSUE TITLE
音乐云盘上传失败

### ISSUE THREAD

**Issue by aliencaocao** [1715173329/UnblockNeteaseMusic#1201]
### Bug 描述

使用代理时，无法上传音乐云盘，docker console里没有任何错误、警告，都是正常的`DEBUG: (hook) unblockLyricsEffects() has been triggered.`
![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/335d2af8-284e-41ca-9dd2-ac67cc9ea6f3)

重试秒失败

### 启动命令及环境变量

`docker run -d -e ENABLE_FLAC=true -e ENABLE_LOCAL_VIP=svip -e BLOCK_ADS=true -e SELECT_MAX_BR=true -e LOG_LEVEL=debug -p 5888:5888 -p 5889:5889 pan93412/unblock-netease-music-enhanced -p 5888:5889`

### 日志内容

都是正常的`DEBUG: (hook) unblockLyricsEffects() has been triggered.`

### 网易云音乐版本号

3.0.0 build 201795

### 操作系统

Win 10

### 其他信息

其他功能正常

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
没修好，好像不是这个问题，有空再看看

**Comment by aliencaocao** [comment]
回头我看看能不能抓包

**Comment by 1715173329** [comment]
fixed by b04c9887965890fc43bfd787d88f2f4851e16eee
