### ISSUE TITLE
疑似酷我API失效

### ISSUE THREAD

**Issue by FoLeaf** [1715173329/UnblockNeteaseMusic#1202]
### Bug 描述

配置好酷我cookie后前往网易云播放CVIP音乐 只可以试听

### 启动命令及环境变量

ENABLE_FLAC=true
ENABLE_LOCAL_VIP=true
KUWO_COOKIE=Hm_lvt_cdb524f42f0ce19b169a8071123a4797=1692028577; Secret=50816c889fcc66324ca4a2019bf87df37654182b541e7474bb285ecc479f1b2902acae48

### 日志内容

INFO: (app) HTTP Server running @ http://0.0.0.0:6666
INFO: (app) HTTPS Server running @ http://0.0.0.0:7777
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

### 网易云音乐版本号

201795

### 操作系统

win11 22h2专业版

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
你抓的 cookie 不对，自然无法播放。

**Comment by Khada-Jhin8** [comment]
> 你抓的 cookie 不对，自然无法播放。

根据描述，cookie我只能找到qq得  哈哈哈哈，其他的都找不到。

**Comment by redn3ck** [comment]
貌似确实不能用了，你cookie不对，Hm_Iuvt_cdb524f42f0cer9b268e4v7y734w5esq24这个才是有效的

**Comment by mario6714** [comment]
> 

About the error, i am not sure why but kuwo changed the cookie to like this:

Hm_lvt_cdb_value1; Hm_lvt_cdb_value2; Secret=value3

I hope this help you.

**Comment by Inkarro** [comment]
我测试了下，获取播放直连的接口并没有失效（VIP歌曲也能获取到直链）。
实际上是搜索接口失效了。搜索接口走的是WebAPI，似乎在一周前上了校验。
刚刚下了个酷我的app抓包看了下，他手机版走的搜索api没校验，待会我有空了写个修复提交上来

**Comment by Inkarro** [comment]
修好了，一会提交个PR
![image](https://github.com/UnblockNeteaseMusic/server/assets/137393706/1c14d655-e483-4c15-9ce0-399ef7a030cc)

**Comment by Inkarro** [comment]
#1207

**Comment by redn3ck** [comment]
> #1207

没能生效啊，大佬
![图片](https://github.com/UnblockNeteaseMusic/server/assets/12512242/61a2a8df-194d-4fe8-8061-e09c8d9f1eb8)

**Comment by 1715173329** [comment]
`Hm_Iuvt_cdb524f42f0cer9b268e4v7y734w5esq24=KuwoILoveYouPleaseHoldSearchAPI0; Secret=6bcc68a4b0b74b1c1ea9bd25b9f56aca698474705b032229a2376cfb6ba6215f0445f7cf`

其用且珍惜吧。

**Comment by Inkarro** [comment]
> > #1207
> 
> 没能生效啊，大佬 ![图片](https://user-images.githubusercontent.com/12512242/261182417-61a2a8df-194d-4fe8-8061-e09c8d9f1eb8.png)

运行./src/app.js，不要运行打包后的

**Comment by FoLeaf** [comment]
> `Hm_Iuvt_cdb524f42f0cer9b268e4v7y734w5esq24=KuwoILoveYouPleaseHoldSearchAPI0; Secret=6bcc68a4b0b74b1c1ea9bd25b9f56aca698474705b032229a2376cfb6ba6215f0445f7cf`
> 
> 其用且珍惜吧。

非常感谢

**Comment by redn3ck** [comment]
> 运行./src/app.js，不要运行打包后的

哪里不对？这报错查了一下缺少库？
![image](https://github.com/UnblockNeteaseMusic/server/assets/12512242/a7e5ccdb-c34f-40a4-a7bb-a8b9dc79708a)

**Comment by Inkarro** [comment]
> > 运行./src/app.js，不要运行打包后的
> 
> 哪里不对？这报错查了一下缺少库？ ![image](https://user-images.githubusercontent.com/12512242/261346930-a7e5ccdb-c34f-40a4-a7bb-a8b9dc79708a.png)

npm install pino

**Comment by 1715173329** [comment]
closed by b04c9887965890fc43bfd787d88f2f4851e16eee
