### ISSUE TITLE
安装了,使用了,现阶段问题是不支持车载版的网抑云

### ISSUE THREAD

**Issue by esf5021314** [1715173329/UnblockNeteaseMusic#1212]
### 需求描述

安装了,使用了,现阶段问题是不支持车载版的网抑云,然后还有一点就是,灰色的解锁了,但却跳到试听播放了,等试听结束后又不能听了,不知道有没有其他大佬们能解决这问题

### 网易云音乐版本号

车载版网抑云-比亚迪车机提取安装包

### 操作系统

Android 10

**Comment by 1715173329** [comment]
你需要去找网抑云公司，本项目只负责网易云。

**Comment by Inkarro** [comment]
发个安装包我抓包看看
