### ISSUE TITLE
安卓貌似用不了了

### ISSUE THREAD

**Issue by Dep0s1t** [1715173329/UnblockNeteaseMusic#122]
pull了新版后安卓clash没法用了,但是win还可以

**Comment by 1715173329** [comment]
Clash is not really related to this project.

**Comment by HinataKato** [comment]
太长不看版：Target API 在 24 以上的话，应用就只会信任系统证书而不会信任用户证书
引用自 [https://github.com/nondanee/UnblockNeteaseMusic/issues/434](https://github.com/nondanee/UnblockNeteaseMusic/issues/434)
