### ISSUE TITLE
有大佬说下怎么用node命令在windows运行吗?

### ISSUE THREAD

**Issue by YiYuan196** [1715173329/UnblockNeteaseMusic#1222]
### Bug 描述

这个怎么用node在windows上运行呢 像nondanee的可以用命令 node app.js -a 127.0.0.1 -p 80 -f IP
但是这个用node命令好像不行

### 启动命令及环境变量

求大佬教下

### 日志内容

求大佬教下

### 网易云音乐版本号

2.9.6

### 操作系统

windows

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by mario6714** [comment]
You can use this  "unblockneteasemusic-win-x64.exe " from the releases.

open a terminal (cmd) and for example use the next commands:

I use a bat file for that:

cd C:\Users\ "user" \Downloads

set LOG_LEVEL=debug
set ENABLE_FLAC=true
set ENABLE_LOCAL_VIP=true


unblockneteasemusic-win-x64 -o kuwo -e https://music.163.com -f 103.126.92.132 

[Unblockneatse_example.zip](https://github.com/UnblockNeteaseMusic/server/files/12480040/Unblockneatse_example.zip)

**Comment by 1715173329** [comment]
Move to discussion.
