### ISSUE TITLE
音乐源没用了，不像截图中的所有歌都可以听

### ISSUE THREAD

**Issue by TianYuWord** [1715173329/UnblockNeteaseMusic#1225]
### Bug 描述

音乐源没用了，不像截图中的所有歌都可以听。
服务部署在docker使用的latest版本

### 预期行为

所有歌都可以听，建议给一个定期自动更新订阅源并且给一个webUI来让用户知道那些订阅源更新了，让用户可以以自建订阅源列表，添加本地订阅源。

### 实际行为

不像截图中的所有歌都可以听

### 复现步骤

ss

### 启动命令及环境变量

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION=18.17.1
YARN_VERSION=1.22.19
SIGN_CERT=/app/server.crt
SIGN_KEY=/app/server.key
NODE_ENV=production
ENABLE_FLAC=true
ENABLE_LOCAL_VIP=svip
BLOCK_ADS=true
DISABLE_UPGRADE_CHECK=true
QQ_COOKIE=me——hide
JSON_LOG=true
LOG_LEVEL=debug

### 日志内容

2023-09-01T10:54:42.990405463Z {"level":30,"time":1693565682989,"pid":1,"hostname":"5f9ebc59d4d0","scope":"app","msg":"HTTP Server running @ http://0.0.0.0:8080"}
2023-09-01T10:54:42.990693502Z {"level":30,"time":1693565682990,"pid":1,"hostname":"5f9ebc59d4d0","scope":"app","msg":"HTTPS Server running @ http://0.0.0.0:8081"}

### 网易云音乐歌曲链接

那可太多了

### 网易云音乐版本号

8.10.61

### 操作系统

android13

### 其他信息

建议在[README.md](https://github.com/UnblockNeteaseMusic/server/blob/enhanced/README.md)文件中添加推荐的个平台对应的客户端版本号，否则客户端版本升级之后换了域名可能导致代理失效。

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by Inkarro** [comment]
下载最新ci构建试试，酷我音源修了

**Comment by TianYuWord** [comment]
今天又试了一下，是我的客户端配置问题
