### ISSUE TITLE
建议直接使用MitM进行全平台的HTTPS支持

### ISSUE THREAD

**Issue by Uber-Eins** [1715173329/UnblockNeteaseMusic#1230]
### 需求描述

如题，可以遇见的是未来HTTPS会更多的使用到各个平台的客户端上，现在我的iOS 8.6.16版本已经是10次9次不能用了，而PC端3.0似乎是直接不能用，于是我直接手动用了被我当成网关的surge直接降级网易云的HTTPS到HTTP，现在它成功工作了；所以既然都要安装证书，何不直接进行中间人攻击去降级请求达到更好的可用性呢？

### 网易云音乐版本号

8.6.15；3.0

### 操作系统

IOS 15.6.1；Windows Build 22621.1992

**Comment by LiuXiaohuanhh** [comment]
PC端  版本3.0.0. Beta (64位) (Build: 201903) Patch:4bf90ae   正常

**Comment by pan93412** [comment]
主要是目前還沒有特別了解 NCM 加密機制的工程師。你有興趣或許可以貢獻！

**Comment by Uber-Eins** [comment]
> 主要是目前還沒有特別了解 NCM 加密機制的工程師。你有興趣或許可以貢獻！

我Fork了一下并且简单的加上了MitM的功能,https://github.com/Uber-Eins/UnblockNeteaseMusic-MitM
我觉得Nodejs应该也可以实现（

**Comment by pan93412** [comment]
你那個只是把 HTTPS 降級成 HTTP 吧。現在就有了：https://github.com/UnblockNeteaseMusic/server/blob/enhanced/src/hook.js

我以為你是想直接解密 HTTPS 資料並進行操作。
