### ISSUE TITLE
IOS端播放显示“网络不给力”

### ISSUE THREAD

**Issue by UmbraCi** [1715173329/UnblockNeteaseMusic#124]
放在局域网的电脑的docker运行，启动以后有两个服务，一个8080，一个8081,直接IOS手机安卓手机还有WIN10客户端设置代理内网地址:8080，手机端用的是内网地址的WIFI高级设置里面的代理，IOS不可听可加载专辑封面，安卓和电脑正常

**Comment by 1715173329** [comment]
#102

**Comment by UmbraCi** [comment]
> #102

如何在docker启动里面加这个参数呢，我用的是win的面板，clone以后执行readme里面的docker命令以后dicker就多了一个APP，但是只有启动等按钮，没看到加参数的地方

**Comment by UmbraCi** [comment]
按照博客的教程，小火箭添加规则以后无法读取歌曲列表，WIFI代理设置可以

**Comment by 1715173329** [comment]
小火箭不属于我们的支持范围内。

**Comment by UmbraCi** [comment]
> 小火箭不属于我们的支持范围内。

所以，博主现在有在用IOS听歌吗，如何实现的

**Comment by 1715173329** [comment]
> 所以，博主现在有在用IOS听歌吗，如何实现的

https://github.com/immortalwrt/luci-app-unblockneteasemusic
