### ISSUE TITLE
单独启用pyncmd无法获取音源

### ISSUE THREAD

**Issue by M-HLSLY** [1715173329/UnblockNeteaseMusic#1242]
### Bug 描述

单独启用pyncmd时报错,但与其他音源一起启用正常获取音源

### 复现步骤

单独启用pyncmd

### 启动命令及环境变量

./unblockneteasemusic-linux-arm64 -o pyncmd -p 2635:2636 -f 115.238.119.69 -e http://music.163.com -s

env=
ENABLE_FLAC=true
ENABLE_LOCAL_VIP=svip
BLOCK_ADS=true
DISABLE_UPGRADE_CHECK=true
FOLLOW_SOURCE_ORDER=true
MIN_BR=320000
SELECT_MAX_BR=true
LOG_LEVEL=info
SEARCH_ALBUM=true

### 日志内容

INFO: (app) HTTP Server running @ http://0.0.0.0:2635
INFO: (app) HTTPS Server running @ http://0.0.0.0:2636
DEBUG: (server) TUNNEL
    url: "localhost:2636"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/find"
DEBUG: (cache) 1858857999 did not hit. Storing the execution result...
    logKey: 1858857999
    cacheStorageId: "provider/find"
DEBUG: (request) Start requesting https://music.163.com/api/song/detail?ids=[1858857999]
DEBUG: (provider/match) Getting the audio...
    source: "pyncmd"
    info: {
      "name": "到你身边",
      "id": 1858857999,
      "alias": [],
      "duration": 197803,
      "album": {
        "name": "到你身边",
        "id": 129955507
      },
      "artists": [
        {
          "name": "Atsuko",
          "id": 37124086
        },
        {
          "name": "洛天依",
          "id": 0
        }
      ],
      "keyword": "到你身边 - Atsuko / 洛天依"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/pyncmd"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/pyncmd"
DEBUG: (request) Start requesting https://pyncmd.apis.imouto.in/api/pyncm?module=track&method=GetTrackAudio&song_ids=1858857999&bitrate=999000
ERROR (SongNotAvailable): (hook) This song "?" is not available in any source
    SongNotAvailable: This song "?" is not available in any source
        at b (/snapshot/server/precompiled/app.js)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
DEBUG: (server) TUNNEL
    url: "localhost:2636"
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/find"
DEBUG: (cache) 1858857999 hit!
    logKey: 1858857999
    cacheStorageId: "provider/find"
DEBUG: (provider/match) Getting the audio...
    source: "pyncmd"
    info: {
      "name": "到你身边",
      "id": 1858857999,
      "alias": [],
      "duration": 197803,
      "album": {
        "name": "到你身边",
        "id": 129955507
      },
      "artists": [
        {
          "name": "Atsuko",
          "id": 37124086
        },
        {
          "name": "洛天依",
          "id": 0
        }
      ],
      "keyword": "到你身边 - Atsuko / 洛天依"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/pyncmd"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/pyncmd"
DEBUG: (request) Start requesting https://pyncmd.apis.imouto.in/api/pyncm?module=track&method=GetTrackAudio&song_ids=1858857999&bitrate=999000
ERROR (SongNotAvailable): (hook) This song "?" is not available in any source
    SongNotAvailable: This song "?" is not available in any source
        at b (/snapshot/server/precompiled/app.js)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/find"
DEBUG: (cache) 1423014472 did not hit. Storing the execution result...
    logKey: 1423014472
    cacheStorageId: "provider/find"
DEBUG: (request) Start requesting https://music.163.com/api/song/detail?ids=[1423014472]
DEBUG: (provider/match) Getting the audio...
    source: "pyncmd"
    info: {
      "name": "1001夜",
      "id": 1423014472,
      "alias": [],
      "duration": 210729,
      "album": {
        "name": "1001夜",
        "id": 85644394
      },
      "artists": [
        {
          "name": "KBShinya",
          "id": 1047064
        },
        {
          "name": "Hanser",
          "id": 1049179
        }
      ],
      "keyword": "1001夜 - KBShinya / Hanser"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/pyncmd"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/pyncmd"
DEBUG: (request) Start requesting https://pyncmd.apis.imouto.in/api/pyncm?module=track&method=GetTrackAudio&song_ids=1423014472&bitrate=999000
ERROR (SongNotAvailable): (hook) This song "?" is not available in any source
    SongNotAvailable: This song "?" is not available in any source
        at b (/snapshot/server/precompiled/app.js)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 0)

### 网易云音乐版本号

7.3.28(Android)

### 操作系统

Ubuntu 20.04.6 LTS

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by mario6714** [comment]
https://github.com/UnblockNeteaseMusic/server/issues/1226

**Comment by mario6714** [comment]
https://github.com/UnblockNeteaseMusic/server/pull/1237

**Comment by mario6714** [comment]
https://github.com/UnblockNeteaseMusic/server/pull/1236

just don't use alone

**Comment by 1715173329** [comment]
上游 api 不稳定，有条件的最好自己搭。
