### ISSUE TITLE
编译docker的时候如何指定-e

### ISSUE THREAD

**Issue by UmbraCi** [1715173329/UnblockNeteaseMusic#125]
docker-compose up命令构建的应用，启动时或者生成时如何添加-e的参数

**Comment by pan93412** [comment]
試試看把 `env-example` 複製一份，並命名為 `.env` 檔案。接著你就可以在填上想修改的部分了～

https://docs.docker.com/compose/environment-variables/

**Comment by pan93412** [comment]
7 天沒回應，且當解決。有問題歡迎再詢問w

**Comment by gqbre** [comment]
@UmbraCi 最简单的方式，附加到 SOURCE 里，一起作为字符串执行参数
