### ISSUE TITLE
仓库里的证书过期了

### ISSUE THREAD

**Issue by ty-peng** [1715173329/UnblockNeteaseMusic#1252]
### Bug 描述

如题

### 启动命令及环境变量

-p 

### 日志内容

如题

### 网易云音乐版本号

2.10.10

### 操作系统

Windows

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
有效期到明年三月啊

**Comment by ty-peng** [comment]
看错成 2023 了 ，无视该条

**Comment by ty-peng** [comment]
不对  好像就是 2023/04/04 到期诶
![image](https://github.com/UnblockNeteaseMusic/server/assets/20200179/fa9a2a65-251d-4973-995b-6f5d10c1831d)
![image](https://github.com/UnblockNeteaseMusic/server/assets/20200179/489b2147-e21d-440c-8783-de1016d304d0)

@1715173329

**Comment by 1715173329** [comment]
![image](https://github.com/UnblockNeteaseMusic/server/assets/22235437/45909532-84c9-45cb-a214-a8a19c50f359)
我一定是用了盗版的

**Comment by ty-peng** [comment]
我知道了，用了 github 代理，git clone https://gitclone.com/github.com/UnblockNeteaseMusic/server.git，代理没更新，大乌龙哈哈抱歉
