### ISSUE TITLE
ytdlp能搜到链接并替换（其他音源不行），iOS端无法播放，Windows端正常

### ISSUE THREAD

**Issue by EricYoung37** [1715173329/UnblockNeteaseMusic#1254]
### Bug 描述

做了以下尝试：

#### 2. 严格模式，`$node app.js -p 8080:8081 -s -e https://music.163.com`
yt-dlp能搜索到链接并替换歌曲，但是会不断搜索，在`81.70.126.110:80`（酷我）与`218.200.160.55:443`（咪咕）间反复横跳超时，最终iOS端网易云显示 “_播放失败，获取播放信息失败_”

#### 3. 仅用ytdlp+严格`$ node app.js -p 8080:8081 -s -e https://music.163.com -o ytdlp`
yt-dlp能搜索到链接并替换歌曲，分两种情况：
1. yt-dlp只搜索 = 1次，此时iOS端显示 “_播放失败，获取播放信息失败_”
![image](https://github.com/UnblockNeteaseMusic/server/assets/77303738/ff68b470-6453-442f-8354-000ae877cd77)
2. yt-dlp搜索 > 1次，此时iOS端只能播放9秒
![image](https://github.com/UnblockNeteaseMusic/server/assets/77303738/fc8b4c75-f4a9-4536-b952-1eb78d4d2ac1)

#### 5. 仅用bilibili（或仅酷狗）+严格`$ node app.js -p 8080:8081 -s -e https://music.163.com -o bilibili`（或`$ node app.js -p 8080:8081 -s -e https://music.163.com -o kugou`）
出现`ERROR: (hook)`，iOS端无法播放，显示 “_播放失败，无权限播放_”
![image](https://github.com/UnblockNeteaseMusic/server/assets/77303738/2170dba5-8127-4754-b144-4a05e5ae78b9)
![image](https://github.com/UnblockNeteaseMusic/server/assets/77303738/2bc22560-cd79-43bc-9d6a-3a1d88070200)

#### 6. 仅用酷我+严格`$ node app.js -p 8080:8081 -s -e https://music.163.com -o kuwo`
`ERROR: (provider/match) connect ETIMEDOUT`与`ERROR: (hook) All promises were rejected`交替出现，iOS显示 “_播放失败，获取播放信息失败_”
![image](https://github.com/UnblockNeteaseMusic/server/assets/77303738/a6c6a193-368f-4134-aff6-e7e35abf8c44)

#### 7. 仅用咪咕+严格`$ node app.js -p 8080:8081 -s -e https://music.163.com -o migu`，和酷我的情况差不多
![image](https://github.com/UnblockNeteaseMusic/server/assets/77303738/89722657-82c0-4c8e-a99e-ea023a044786)

### 网易云音乐版本号

2.9.5 (Windows), 2.0.93 (iOS)

### 操作系统

Windows, iOS

### 其他信息

去看了类似的Issues #775 #1043 #1200，但并未得出解决方案
yt-dlp用的PIP，试过两个版本都不行（一开始是一两个月前的yt-dlp，发现播不了又升级到了最新的yt-dlp）

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
ytdlp 只能播放 9 秒应该是 apple 平台的解码问题，在 unm 做重编码是感觉有点蛋疼。
至于其他平台，基本上也同样限制了海外 IP，比较麻烦。

**Comment by EricYoung37** [comment]
感谢大佬回答。那如果我更换运行UNM的机器，比如我用系统为Ubuntu的VPS，也没有办法更好地配合iOS吗？（感觉应该是一样的，毕竟UNM源码就在那里，编译成啥平台/或环境，跑起来后和iOS那边交互估计iOS得到的音频文件编码一样…）

**Comment by 1715173329** [comment]
是的

**Comment by EricYoung37** [comment]
好的，我再去看看Issues别人的部署案例（感觉自己未必有能力和时间去重现了哈哈哈）

**Comment by 1715173329** [comment]
最好是放国内的机子上，不然基本无解

**Comment by EricYoung37** [comment]
好吧，感谢大佬，不只是回答问题，还有维护这个项目，就两个人不容易，辛苦了。

**Comment by Kyle-Kyle** [comment]
根据yt-dlp的log: `WARNING: xxxxx: writing DASH m4a. Only some players support this container. Install ffmpeg to fix this automatically`， 应该是youtube那边的问题。
在服务器上架个RangeHTTPServer就完了

**Comment by EricYoung37** [comment]
一年之后回来更新一下，这个问题算是解决了（不过其根源的问题还将长期存在）。

根源问题：
我当时是在Windows上运行此项目，用iOS设备去访问我Windows上的node server，此时Windows解析的音源格式和iOS不兼容，因此导致了iOS上只能播放9秒解析后的音源。即此项目管理者之一所说：
> ytdlp 只能播放 9 秒应该是 apple 平台的解码问题，在 unm 做重编码是感觉有点蛋疼。 至于其他平台，基本上也同样限制了海外 IP，比较麻烦。

因此，这个根源问题目前来说应该是不会解决了。

不过，幸好[iOS是unix-like system](https://en.wikipedia.org/wiki/IOS#:~:text=%2C%20assembly%20language-,OS%20family,-Unix%2Dlike%2C%20based)，因此使用linux机器作为unm代理来解码应该可以与iOS兼容（反过来说Windows不属于unix家族，所以解码也和iOS不兼容）。带着这种想法，我就在一台ubuntu机器上部署了项目（[参考](https://github.com/nondanee/UnblockNeteaseMusic/issues/65)），最终能在iOS上播放了。

同时我的代理机器是海外的，这也说明
> 最好是放国内的机子上，不然基本无解

并非原因。（Issues和Discussions板块也有看到海外机器与iOS配合成功的案例）

不过不知什么原因，我只能使用pyncd音源，而无法使用yt-dlp、bilibili、kuwo、kugo的音源。

yt-dlp输出如下：
```
WARN: (spawn) [yt-dlp][stderr] ERROR: [youtube] CkGmzyt6tB8: Sign in to confirm you’re not a bot. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies

ERROR (ProcessExitNotSuccessfully): (provider/yt-dlp) yt-dlp exited with 1, which is not zero.
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.
        at ChildProcess.<anonymous> (/home/localusr/unm-server/precompiled/app.js:12:1614)
        at ChildProcess.emit (node:events:518:28)
        at maybeClose (node:internal/child_process:1101:16)
        at Socket.<anonymous> (node:internal/child_process:456:11)
        at Socket.emit (node:events:518:28)
        at Pipe.<anonymous> (node:net:351:12)
    process: yt-dlp
    exitCode: 1
ERROR (ProcessExitNotSuccessfully): (provider/match) yt-dlp exited with 1, which is not zero.
    ProcessExitNotSuccessfully: yt-dlp exited with 1, which is not zero.
        at ChildProcess.<anonymous> (/home/localusr/unm-server/precompiled/app.js:12:1614)
        at ChildProcess.emit (node:events:518:28)
        at maybeClose (node:internal/child_process:1101:16)
        at Socket.<anonymous> (node:internal/child_process:456:11)
        at Socket.emit (node:events:518:28)
        at Pipe.<anonymous> (node:net:351:12)
    process: yt-dlp
    exitCode: 1
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://m.music.migu.cn/migu/remoting/scr_search_tag?keyword=%E5%AF%82%E5%AF%9E%E7%9A%84%E7%94%B7%E4%BA%BA%20-%20%E5%BC%A0%E5%AD%A6%E5%8F%8B&type=2&rows=20&pgc=1"
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
```

而bilibili等的日志输出为：
```
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
```
类似此[问题](https://github.com/UnblockNeteaseMusic/server/discussions/1081)

希望来日有缘能看到音源问题的解决方案。
