### ISSUE TITLE
修复ios搜索出来的音乐没有解锁变灰

### ISSUE THREAD

**Issue by jiyiv5** [1715173329/UnblockNeteaseMusic#1258]
### 需求描述

网易云音乐api接口中加入了大量的eapi这个接口，因为现在版本部分接口没有匹配eapi接口就导致出现以下问题。
1.打开应用出现广告
2.搜索出来的音乐还是灰色无法播放
3.解锁本地SVIP失效

我的修复办法:
1.在hook.target.path列表中添加"/api/v2/artist/songs".
2.把hook.js代码中所有的"/api/xxx"在添加一份"/eapi/xxx".

### 操作系统

IOS

**Comment by jiyiv5** [comment]
QQ音乐api貌似有问题，不能使用，我也没具体查明

**Comment by joyoner** [comment]
同问，这个问题依旧存在；
PS： 现在iOS的分流文件用哪个

**Comment by jiyiv5** [comment]
> 同问，这个问题依旧存在； PS： 现在iOS的分流文件用哪个
手动修改js代码就行了。但是ios挺不稳定的。还是安卓hook好用

**Comment by jiyiv5** [comment]
> 同问，这个问题依旧存在； PS： 现在iOS的分流文件用哪个

手动修改js代码就行了。但是ios挺不稳定的。还是安卓hook好用

**Comment by srlihg66** [comment]
docker里面没有这个文件 构建好像没有引入这个文件夹 如何修改 如果有是在哪里修改
