### ISSUE TITLE
似乎新版Windows会随缘播放非网易云的链接

### ISSUE THREAD

**Issue by HinataKato** [1715173329/UnblockNeteaseMusic#126]
启动参数
`node /root/UnblockNeteaseMusic/app.js -u http://[proxy address]7890 -s -o pyncmd bilibili kuwo kugou youtube`

测试环境
![image](https://user-images.githubusercontent.com/57648531/131330979-58be7ab0-3928-4dc4-8d65-dbf3c4d9737f.png)
![image](https://user-images.githubusercontent.com/57648531/131327883-b106690b-4598-4f01-8007-b3071313dcc4.png)
![image](https://user-images.githubusercontent.com/57648531/131327902-1c50077b-8c69-433d-ac1e-cbcdd0aa60f4.png)
系统已安装ca证书

测试歌曲
https://music.163.com/song?id=1858165740
![Snipaste_2021-08-30_18-52-21](https://user-images.githubusercontent.com/57648531/131331498-19e1016e-9537-4076-bec3-c9654f4d620d.png)
获取到了酷我的源 有时候过一段时间之后直接播放错误 有时候就能播 Android就好好的
而
http://music.163.com/song?id=1391849655
因为走了pyncmd一直都可以直接播放

**Comment by 1715173329** [comment]
> 播放非网易云的链接

https://github.com/1715173329/UnblockNeteaseMusic#%E7%89%B9%E6%80%A7
此项目工作方式即为使用其他平台音源替换网易云自身无法播放的歌曲

> https://music.163.com/song?id=1858165740

这首歌本身网易云音乐没有版权，自然需要通过其他平台获取
目前程序在首次连接时会确认是否有效，如果播放至中途无法继续加载，请检查您的网络

> http://music.163.com/song?id=1391849655

这首歌网易云音乐自身有版权，但需要 CVIP
pyncmd 提供的示例接口使用了 CVIP cookie，自然可使用网易云音乐自己的音源

**Comment by HinataKato** [comment]
> > 播放非网易云的链接
> 
> https://github.com/1715173329/UnblockNeteaseMusic#%E7%89%B9%E6%80%A7
> 此项目工作方式即为使用其他平台音源替换网易云自身无法播放的歌曲
> 
> > https://music.163.com/song?id=1858165740
> 
> 这首歌本身网易云音乐没有版权，需要通过其他平台获取
> 目前程序在首次连接时会确认是否有效，如果播放至中途无法继续加载，请检查您的网络
> 
> > http://music.163.com/song?id=1391849655
> 
> 这首歌网易云音乐自身有版权，但需要 CVIP
> pyncmd 提供的示例接口使用了 CVIP cookie，自然可获取并使用网易云音乐自己的音源



> > 播放非网易云的链接
> 
> https://github.com/1715173329/UnblockNeteaseMusic#%E7%89%B9%E6%80%A7
> 此项目工作方式即为使用其他平台音源替换网易云自身无法播放的歌曲
> 
> > https://music.163.com/song?id=1858165740
> 
> 这首歌本身网易云音乐没有版权，需要通过其他平台获取
> 目前程序在首次连接时会确认是否有效，如果播放至中途无法继续加载，请检查您的网络
> 
> > http://music.163.com/song?id=1391849655
> 
> 这首歌网易云音乐自身有版权，但需要 CVIP
> pyncmd 提供的示例接口使用了 CVIP cookie，自然可获取并使用网易云音乐自己的音源

它又自己全好了 我就当CDN抽了吧...

**Comment by HinataKato** [comment]
> > > 播放非网易云的链接
> > 
> > 
> > https://github.com/1715173329/UnblockNeteaseMusic#%E7%89%B9%E6%80%A7
> > 此项目工作方式即为使用其他平台音源替换网易云自身无法播放的歌曲
> > > https://music.163.com/song?id=1858165740
> > 
> > 
> > 这首歌本身网易云音乐没有版权，需要通过其他平台获取
> > 目前程序在首次连接时会确认是否有效，如果播放至中途无法继续加载，请检查您的网络
> > > http://music.163.com/song?id=1391849655
> > 
> > 
> > 这首歌网易云音乐自身有版权，但需要 CVIP
> > pyncmd 提供的示例接口使用了 CVIP cookie，自然可获取并使用网易云音乐自己的音源
> 
> > > 播放非网易云的链接
> > 
> > 
> > https://github.com/1715173329/UnblockNeteaseMusic#%E7%89%B9%E6%80%A7
> > 此项目工作方式即为使用其他平台音源替换网易云自身无法播放的歌曲
> > > https://music.163.com/song?id=1858165740
> > 
> > 
> > 这首歌本身网易云音乐没有版权，需要通过其他平台获取
> > 目前程序在首次连接时会确认是否有效，如果播放至中途无法继续加载，请检查您的网络
> > > http://music.163.com/song?id=1391849655
> > 
> > 
> > 这首歌网易云音乐自身有版权，但需要 CVIP
> > pyncmd 提供的示例接口使用了 CVIP cookie，自然可获取并使用网易云音乐自己的音源
> 
> 它又自己全好了 我就当CDN抽了吧...
> Update:
> 排查了一圈大概是因为我加的代理规则写糊了...

事后想起来其实就是我指定了 -s 然后匹配的歌曲不能从代理走 然后就炸了
