### ISSUE TITLE
听不了周杰伦的歌了吗

### ISSUE THREAD

**Issue by ccsugar** [1715173329/UnblockNeteaseMusic#127]
听不了周杰伦的歌了吗

**Comment by pan93412** [comment]
可以呀。你可以把啟動 UnblockNeteaseMusic 的指令傳過來嗎？

**Comment by ccsugar** [comment]
> 可以呀。你可以把啟動 UnblockNeteaseMusic 的指令傳過來嗎？

D:\>cd D:\Download\UnblockNeteaseMusic-0.26.1\UnblockNeteaseMusic-0.26.1
D:\Download\UnblockNeteaseMusic-0.26.1\UnblockNeteaseMusic-0.26.1>node app.js

**Comment by pan93412** [comment]
你有設定 Proxy 跟 HTTPS 證書嗎？

**Comment by ccsugar** [comment]
> 你有設定 Proxy 跟 HTTPS 證書嗎？

设定了客户端代理，现在又好了

**Comment by pan93412** [comment]
> > 你有設定 Proxy 跟 HTTPS 證書嗎？
> 
> 设定了客户端代理，现在又好了

有問題歡迎再回報～
