### ISSUE TITLE
Pyncmd疑似失效

### ISSUE THREAD

**Issue by DestoryG** [1715173329/UnblockNeteaseMusic#1274]
### Bug 描述

利用Pyncmd前往网易云播放CVIP音乐 只能试听

### 启动命令及环境变量

set ENABLE_FLAC=true
set ENABLE_LOCAL_VIP=svip
set LOG_LEVEL=debug
node app.js -p 8888:8889 -o pyncmd

### 日志内容

![QQ截图20231020183143](https://github.com/UnblockNeteaseMusic/server/assets/136814177/f1033d5a-4a38-4b2c-a5c9-ab4423e14b19)

### 网易云音乐歌曲链接

https://music.163.com/song?id=1974705042&userid=1521079201

### 网易云音乐版本号

2.10.12

### 操作系统

Windows 10

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by mario6714** [comment]
The Pyncmd is no longer working because netease blocked the vip account in the vercel, if you want you need create your own vercel and a vip account.

https://github.com/mos9527/pyncmd

More info about why is not longer working:

https://github.com/mos9527/pyncmd/issues/8

**Comment by 1715173329** [comment]
#1279
