### ISSUE TITLE
有没有考虑过更换pyncmd的api？

### ISSUE THREAD

**Issue by M-HLSLY** [1715173329/UnblockNeteaseMusic#1279]
### 需求描述

可否用其他的api，比如网易云CSM api：https://csm-docs.apifox.cn/api-49565129
替换掉目前的，其他音源或多或少会有匹配错误的情况

**Comment by 1715173329** [comment]
感谢提供信息，现已切换。

**Comment by chris7395328** [comment]
这个api指向的音源名称还是pyncmd么，获取无损环境变量有什么需要更改么

**Comment by M-HLSLY** [comment]
> 这个api指向的音源名称还是pyncmd么，获取无损环境变量有什么需要更改么

是的；并没有什么需要更改的。名称由项目里的文件定义，和api没太大关系，之所以叫pyncmd应该是因为最开始用的是https://github.com/mos9527/pyncmd
然后就延续这个叫法到现在了。不过现在这个api和以前的api请求参数不一样，要改下（已经由项目组成员完成了），应该要改和pyncmd和request有关的文件吧……虽然我到现在也搞不懂怎么改，但是改音源和请求的大方向应该是没错的

**Comment by chris7395328** [comment]
> 感谢提供信息，现已切换。

该api可以最高获取到超清母带，[level]参数：standard=>标准, exhigh=>极高, lossless=>无损, hires=>Hi-Res, jyeffect=>高清环绕声, sky=>沉浸环绕声, jymaster=>超清母带
环绕声应该没啥必要，可以在hires前再添加一个jymaster为优先选择

**Comment by chris7395328** [comment]
> > 这个api指向的音源名称还是pyncmd么，获取无损环境变量有什么需要更改么
> 
> 是的；并没有什么需要更改的。名称由项目里的文件定义，和api没太大关系，之所以叫pyncmd应该是因为最开始用的是https://github.com/mos9527/pyncmd 然后就延续这个叫法到现在了。不过现在这个api和以前的api请求参数不一样，要改下（已经由项目组成员完成了），应该要改和pyncmd和request有关的文件吧……虽然我到现在也搞不懂怎么改，但是改音源和请求的大方向应该是没错的

今早发现 csm.sayqz.com好像寄了（x
