### ISSUE TITLE
New pyncmd api

### ISSUE THREAD

**Issue by M-HLSLY** [1715173329/UnblockNeteaseMusic#1282]
### 需求描述

**此API有较大缺陷，不建议作为主力API，可以在原API无法访问时使用，平时请无视**
_注：该API来自互联网_

本来吧，pyncmd已经有了应该较好的api了，应该够用一段时间了。但是吧……我特喵是和网易云过不去了吗，今天上网又看到了一个网易云的无损解析（并没有直接给出api），还最高支持SVIP的超清母带（应该也没啥人用吧），于是……我又花了亿点点时间分析了一下这个东西（现在想起来我也太tmd闲了）。反正最后是摸索出来了，~~至少能用~~但是约等于没啥用，就当应急的吧，不用也好过没有，于是就想着放这了。
#1279 
注：github新人，对github的操作有很多不熟悉的地方，请多包涵。

出处：https://tools.qzxdp.cn/wyy_vip
api请求地址：https://tools.qzxdp.cn/api/wyy_vip/parse?url=https://music.163.com/song?id=[id]&musicType=[level]
请求参数：[id]==>歌曲id  ;   [level]==>音质
[level]参数：standard=>标准, exhigh=>极高, lossless=>无损, hires=>Hi-Res, jyeffect=>高清环绕声, sky=>沉浸环绕声, jymaster=>超清母带

示例：
Request：
https://tools.qzxdp.cn/api/wyy_vip/parse?url=https://music.163.com/song?id=2074798037&musicType=jymaster

Return：
Web
![IMG_20231029_040040](https://github.com/UnblockNeteaseMusic/server/assets/102822186/2ac8e4cb-7451-4e08-9431-d73fc1c849b9)

Api
![IMG_20231029_040056](https://github.com/UnblockNeteaseMusic/server/assets/102822186/161782b3-33b9-4f39-9e96-277b7ee50d01)

想必你也注意到了这个返回有些……与众不同，这大概是作者的一种防滥用措施，其实就是把每个“/”变成了“ \ / ”而已，去除“\”就可以正常用了，反正我们也就是要到url就行，这个在本地应该能处理的吧……

OK，关于api的部分完结了（应该）。
最后是一些可能需要注意的地方：
1.我在最开始使用web端的时候出现过“验证”类的东西，~~我并不清楚陌生设备直接访问api能否绕过这个验证~~在到达一定次数后web端似乎会弹窗，但是api似乎没什么影响，或许有cookie、token之类的。~~总之，按照网站的指示可以解开，之后一段时间或到达一定次数前应该就没有验证了（仅限web端）。~~
![IMG_20231029_161213.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/7dfd8750-73c6-46d0-87db-04b44f5584eb)

2.如果访问出现Access Denied，可以尝试重新手动输入部分字符，如下
https://tools.qzxdp.cn/api/wyy_vip/parse?url=https://music.163.com/song?id=2074798037&musicType=jymaster
将jymaster删除访问一次，在重新手动输入后再访问一次（要不就直接粗暴一点，直接请求两次，第一次故意缺少某个字符，再请求第二次应该就不会被拒绝了）；或者尝试用web端访问几次，再用api访问。

**Comment by M-HLSLY** [comment]
我刚刚试了一下，#1279 CSM-Api也可以获取超清母带等的音源……我现在tmd就是真的闲了去扒这玩意儿……还不如老老实实用现在的……

**Comment by M-HLSLY** [comment]
我刚刚试了一下，#1279 CSM-Api也可以获取超清母带等的音源……我现在tmd就是真的闲了去扒这玩意儿……还不如老老实实用现在的……

更麻的是![IMG_20231029_042721.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/81786f71-7eee-4928-bc7a-db5eba420ce5)

6，看来这个只能应急用。

**Comment by chris7395328** [comment]
csm那个源被版权炮了，看看能不能替换这个？
