### ISSUE TITLE
设置代理后提示网络连接失败

### ISSUE THREAD

**Issue by LeLouch-vilk** [1715173329/UnblockNeteaseMusic#1290]
### Bug 描述

配置成windos服务后，在网易云也设置代理了。之前还可以，现在提示无网络，无法添加播放。之前是最新版本，现在降级为2.9.10依旧不行。

### 启动命令及环境变量

windows服务。

还试了一下 node app.js -p 8000:8043 -s -e https://music.163.com
也不行

### 日志内容

unblockneteasecloudmusic.err.log无内容
unblockneteasecloudmusic.out.log里面有以下内容：
INFO: (app) HTTP Server running @ http://0.0.0.0:8080
INFO: (app) HTTPS Server running @ http://0.0.0.0:8081
Error: getaddrinfo ENOTFOUND interface.music.163.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:119:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'interface.music.163.com'
}
Error: getaddrinfo ENOTFOUND interface.music.163.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:119:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'interface.music.163.com'
}

### 网易云音乐版本号

2.9.10 

### 操作系统

windows

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by bruce2233** [comment]
same error. 兄弟怎么解决的?

**Comment by bruce2233** [comment]
DEBUG: (server) TUNNEL
    decision: "blank"
    url: "music.163.com:443"

就报这个信息
