### ISSUE TITLE
kuwo：您所播放的内容需开通会员后畅听，限时优惠正在进行中。。。。。

### ISSUE THREAD

**Issue by gu0o00** [1715173329/UnblockNeteaseMusic#1299]
### Bug 描述

最近发现，请求到kuwo的音源都会返回同一个URL，播放内容就是要求开通kuwo会员

```
INFO: (provider/match) Replaced: [157276] Last Dance
    audioId: 157276
    songName: "Last Dance"
    url: "http://nf.sycdn.kuwo.cn/64a30f9542cbf925fb0ef7225767dde7/6555ce10/resource/s2/23/61/3992993176.flac?bitrate"

INFO: (provider/match) Replaced: [157276] Last Dance
    audioId: 157276
    songName: "Last Dance"
    url: "http://nf.sycdn.kuwo.cn/64a30f9542cbf925fb0ef7225767dde7/6555ce10/resource/s2/23/61/3992993176.flac?bitrate"
```
个别的kuwo歌曲也能播放
```
INFO: (provider/match) Replaced: [1888915574] 路过人间
    audioId: 1888915574
    songName: "路过人间"
    url: "http://nf.sycdn.kuwo.cn/21f4bd7f377dad50bc7bcfcde73a5bf4/6555ce36/resource/n3/23/50/3275958566.mp3?bitrate"
```
以前好像没这问题，是最近这样的吗

### 启动命令及环境变量

docker run -d -p 8080:8080  -m 300M --memory-swap -1 -e ENABLE_LOCAL_VIP=true -e NO_CACHE=true -e ENABLE_FLAC=true -e NODE_ENV=production --restart=always --log-opt max-size=10m --name=unblockmusic pan93412/unblock-netease-music-enhanced -e https://music.163.com -s -o kugou bilibili migu kuwo

### 日志内容

如上

### 网易云音乐版本号

2.10.12 build:201849

### 操作系统

windows

### 其他信息

```
REPOSITORY                                TAG       IMAGE ID       CREATED        SIZE
pan93412/unblock-netease-music-enhanced   latest    5d2363681433   12 days ago    245MB
```

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by META-KRIS** [comment]
同样,遇到该问题了

**Comment by wxchil** [comment]
+1

**Comment by logicr** [comment]
+1

**Comment by redn3ck** [comment]
应该是kuwo机制变了，不是bug，马上要无源可用了，哎

**Comment by 1715173329** [comment]
毕竟是免费的 api，很正常，隔壁咪咕也停了。
等以后看看有没有能填 cookie 的 api 吧。

**Comment by bunnyi116** [comment]
+1

**Comment by wosuxiongmao** [comment]
可恶啊。。还有没有办法

**Comment by ITManCHINA** [comment]
> 可恶啊。。还有没有办法

Nope，继续等接口吧，或者上传flac到云盘以达到解灰的效果

**Comment by 1715173329** [comment]
暂时修了，但是没得用也是迟早的事。如果有喜欢的，就下载下来，或者传云盘里备份吧。
