### ISSUE TITLE
pyncmd的api请求jymaster音质导致加载缓慢

### ISSUE THREAD

**Issue by Neeinn** [1715173329/UnblockNeteaseMusic#1300]
### Bug 描述

<img width="853" alt="屏幕截图 2023-11-17 171253" src="https://github.com/UnblockNeteaseMusic/server/assets/147433443/5be254b1-18e2-4c5c-812b-c3dfe23962b4">
在使用pyncmd音源听歌时请求的音质是jymaster而不是hires，导致加载歌曲缓慢

### 预期行为

vip和非vip歌曲都被替换成hires音质

### 实际行为

vip歌曲被替换为超清母带音质，非vip歌曲不会替换音源

### 启动命令及环境变量

set ENABLE_FLAC=true
set ENABLE_LOCAL_VIP=svip
set LOG_LEVEL=debug
node app.js -o pyncmd

### 日志内容

DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/find"
DEBUG: (cache) 1483503085 did not hit. Storing the execution result...
    logKey: 1483503085
    cacheStorageId: "provider/find"
DEBUG: (request) Start requesting https://music.163.com/api/song/detail?ids=[1483503085]
DEBUG: (provider/match) Getting the audio...
    source: "pyncmd"
    info: {
      "name": "娈嬮叿銇ぉ浣裤伄銉嗐兗銈?<Director's Edit.>",
      "id": 1483503085,
      "alias": [],
      "duration": 245093,
      "album": {
        "name": "NEON GENESIS EVANGELION SOUNDTRACK 25th ANNIVERSARY BOX",
        "id": 96176345
      },
      "artists": [
        {
          "name": "楂樻娲嬪瓙",
          "id": 17909
        }
      ],
      "keyword": "娈嬮叿銇ぉ浣裤伄銉嗐兗銈?<Director's Edit.> - 楂樻娲嬪瓙"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/pyncmd"
DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/pyncmd"
DEBUG: (request) Start requesting https://csm.sayqz.com/api/?type=apiSongUrlV1&id=1483503085&level=jymaster
DEBUG: (request) Start requesting http://m701.music.126.net/20231118003619/be7d808ef0e6c0b35390604f4e7ebc9e/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/26311811992/0ec9/89a6/c55f/f3621ed4509aaabd36c7ed3c522c7a3b.flac
DEBUG: (provider/match) The matched song is:
    size: 172372438
    br: 999000
    url: "http://m701.music.126.net/20231118003619/be7d808ef0e6c0b35390604f4e7ebc9e/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/26311811992/0ec9/89a6/c55f/f3621ed4509aaabd36c7ed3c522c7a3b.flac"
    md5: "f3621ed4509aaabd36c7ed3c522c7a3b"
DEBUG: (provider/match) The audio matched!
    source: "pyncmd"
    info: {
      "name": "娈嬮叿銇ぉ浣裤伄銉嗐兗銈?<Director's Edit.>",
      "id": 1483503085,
      "alias": [],
      "duration": 245093,
      "album": {
        "name": "NEON GENESIS EVANGELION SOUNDTRACK 25th ANNIVERSARY BOX",
        "id": 96176345
      },
      "artists": [
        {
          "name": "楂樻娲嬪瓙",
          "id": 17909
        }
      ],
      "keyword": "娈嬮叿銇ぉ浣裤伄銉嗐兗銈?<Director's Edit.> - 楂樻娲嬪瓙"
    }
DEBUG: (provider/match) The data to replace:
    audioInfo: {
      "name": "娈嬮叿銇ぉ浣裤伄銉嗐兗銈?<Director's Edit.>",
      "id": 1483503085,
      "alias": [],
      "duration": 245093,
      "album": {
        "name": "NEON GENESIS EVANGELION SOUNDTRACK 25th ANNIVERSARY BOX",
        "id": 96176345
      },
      "artists": [
        {
          "name": "楂樻娲嬪瓙",
          "id": 17909
        }
      ],
      "keyword": "娈嬮叿銇ぉ浣裤伄銉嗐兗銈?<Director's Edit.> - 楂樻娲嬪瓙"
    }
    audioData: {
      "size": 172372438,
      "br": 999000,
      "url": "http://m701.music.126.net/20231118003619/be7d808ef0e6c0b35390604f4e7ebc9e/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/26311811992/0ec9/89a6/c55f/f3621ed4509aaabd36c7ed3c522c7a3b.flac",
      "md5": "f3621ed4509aaabd36c7ed3c522c7a3b",
      "source": "pyncmd"
    }
INFO: (provider/match) Replaced: [1483503085] 娈嬮叿銇ぉ浣裤伄銉嗐兗銈?<Director's Edit.>
    audioId: 1483503085
    songName: "娈嬮叿銇ぉ浣裤伄銉嗐兗銈?<Director's Edit.>"
    url: "http://m701.music.126.net/20231118003619/be7d808ef0e6c0b35390604f4e7ebc9e/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/26311811992/0ec9/89a6/c55f/f3621ed4509aaabd36c7ed3c522c7a3b.flac"

### 网易云音乐版本号

2.10.12

### 操作系统

Windows 11 22H2

### 其他信息

在安卓上使用杜比大喇叭代理或将杜比大喇叭内模块替换成最新构建版都会出现和上面一样的情况

### 问题排查

- [x] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
现在不会请求 jymaster 了，“加载缓慢”那说明你要更换网络了。
