### ISSUE TITLE
运行tomcat时打开闪退

### ISSUE THREAD

**Issue by GYIIDTF** [1715173329/UnblockNeteaseMusic#131]
不能一边编码一边听歌😭😭😭

**Comment by pan93412** [comment]
我懷疑是 Tomcat 把佔住 port 的程式強行中止。你改掉 Tomcat 或是 UNM 的 Port 看看？

**Comment by GYIIDTF** [comment]
是这样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月2日(星期四) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1715173329/UnblockNeteaseMusic] 运行tomcat时打开闪退 (#131)





 
我懷疑是 Tomcat 把佔住 port 的程式強行中止。你改掉 Tomcat 或是 UNM 的 Port 看看？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
