### ISSUE TITLE
设置 process.env.QQ_COOKIE后仍然无法请求

### ISSUE THREAD

**Issue by Sherlockouo** [1715173329/UnblockNeteaseMusic#1311]
### Bug 描述

desktop:dev: ERROR: (provider/match) connect ETIMEDOUT 2a03:2880:f11c:8183:face:b00c:0:25de:443
desktop:dev:     Error: connect ETIMEDOUT 2a03:2880:f11c:8183:face:b00c:0:25de:443
desktop:dev:         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
desktop:dev:     errno: -60
desktop:dev:     code: ETIMEDOUT
desktop:dev:     syscall: connect
desktop:dev:     address: 2a03:2880:f11c:8183:face:b00c:0:25de
desktop:dev:     port: 443
desktop:dev: ERROR: (provider/match) connect ETIMEDOUT 2a03:2880:f11c:8183:face:b00c:0:25de:443
desktop:dev:     Error: connect ETIMEDOUT 2a03:2880:f11c:8183:face:b00c:0:25de:443
desktop:dev:         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
desktop:dev:     errno: -60
desktop:dev:     code: ETIMEDOUT
desktop:dev:     syscall: connect
desktop:dev:     address: 2a03:2880:f11c:8183:face:b00c:0:25de
desktop:dev:     port: 443

### 预期行为

 await match(trackID, ['qq'])
预期能够正常请求QQ音乐的信息。

### 实际行为

但实际无法得到QQ音乐的歌曲信息，还链接报错

### 启动命令及环境变量

 await match(trackID, ['qq'])

### 日志内容

desktop:dev: ERROR: (provider/match) connect ETIMEDOUT 2a03:2880:f11c:8183:face:b00c:0:25de:443
desktop:dev:     Error: connect ETIMEDOUT 2a03:2880:f11c:8183:face:b00c:0:25de:443
desktop:dev:         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
desktop:dev:     errno: -60
desktop:dev:     code: ETIMEDOUT
desktop:dev:     syscall: connect
desktop:dev:     address: 2a03:2880:f11c:8183:face:b00c:0:25de
desktop:dev:     port: 443
desktop:dev: ERROR: (provider/match) connect ETIMEDOUT 2a03:2880:f11c:8183:face:b00c:0:25de:443
desktop:dev:     Error: connect ETIMEDOUT 2a03:2880:f11c:8183:face:b00c:0:25de:443
desktop:dev:         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
desktop:dev:     errno: -60
desktop:dev:     code: ETIMEDOUT
desktop:dev:     syscall: connect
desktop:dev:     address: 2a03:2880:f11c:8183:face:b00c:0:25de
desktop:dev:     port: 443

### 网易云音乐版本号

4.13.2

### 操作系统

macos arm 

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
你网烂了。
