### ISSUE TITLE
使用node app.js启动脚本如何携带环境变量

### ISSUE THREAD

**Issue by 1965514404** [1715173329/UnblockNeteaseMusic#1315]
### 需求描述

想用-e携带joox_cookie报错,没找到如何携带环境变量启动,环境是ubuntu22, node16,
使用ytdlp总是导致服务器跑满cpu和内存,遂使用joox,不知如何携带环境变量,

### 操作系统

ubuntu22

**Comment by pk49800** [comment]
在项目根目录创建`.env`文件，在里面添加环境变量，就像下面这样
JOOX_COOKIE="wmid=<your_wmid>; session_key=<your_session_key>"
