### ISSUE TITLE
docker运行时migu音源识别歌曲错误

### ISSUE THREAD

**Issue by wxchil** [1715173329/UnblockNeteaseMusic#1316]
### Bug 描述

周杰伦的"最伟大的作品"所有歌曲播放是都是"最后的战役"这一首歌曲
使用参数

### 预期行为

正确识别

### 实际行为

<img width="853" alt="image" src="https://github.com/UnblockNeteaseMusic/server/assets/44988562/f52d7f89-9ae8-4ddb-801d-9d71f89f6f33">
<img width="1356" alt="image" src="https://github.com/UnblockNeteaseMusic/server/assets/44988562/2686f84b-b34e-403f-b6d9-3be9fe989600">
<img width="1407" alt="image" src="https://github.com/UnblockNeteaseMusic/server/assets/44988562/ca3e0251-4b04-4944-b83a-d855024b85fb">
http://freetyst.nf.migu.cn/public/product9th/product46/2023/08/1117/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/60054701920171436.mp3?channelid=02&msisdn=8e1250c9-3730-4139-9745-6ba8d7616833&Tim=1701866049908&Key=7efe8fbc89dc7900

### 启动命令及环境变量

"-e FOLLOW_SOURCE_ORDER=true -o kugou qq migu bilibili"

### 日志内容

INFO: (app) HTTP Server running @ http://0.0.0.0:8080
INFO: (app) HTTPS Server running @ http://0.0.0.0:8081
INFO: (app) HTTP Server running @ http://0.0.0.0:8080
INFO: (app) HTTPS Server running @ http://0.0.0.0:8081
INFO: (provider/match) Replaced: [1962165890] Intro
    audioId: 1962165890
    songName: "Intro"
    url: "http://freetyst.nf.migu.cn/public/product9th/product46/2023/08/1117/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/60054701920171436.mp3?channelid=02&msisdn=ecad9d02-d5ba-43a6-9b99-40f7e2d2f19c&Tim=1701866049915&Key=cfa11391a18d5654"
INFO: (provider/match) Replaced: [1962165890] Intro
    audioId: 1962165890
    songName: "Intro"
    url: "http://freetyst.nf.migu.cn/public/product9th/product46/2023/08/1117/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/60054701920171436.mp3?channelid=02&msisdn=8e1250c9-3730-4139-9745-6ba8d7616833&Tim=1701866049908&Key=7efe8fbc89dc7900"
INFO: (provider/match) Replaced: [1962165898] 最伟大的作品
    audioId: 1962165898
    songName: "最伟大的作品"
    url: "http://freetyst.nf.migu.cn/public/product9th/product46/2023/08/1117/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/60054701920171436.mp3?channelid=02&msisdn=10a61d80-48e3-4f91-a49f-c1d833dfbb94&Tim=1701866304435&Key=2eade769c9c1eb4f"
INFO: (provider/match) Replaced: [1962165922] 还在流浪
    audioId: 1962165922
    songName: "还在流浪"
    url: "http://freetyst.nf.migu.cn/public/product9th/product46/2023/08/1117/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/60054701920171436.mp3?channelid=02&msisdn=28aaf500-c6df-4a07-bcd9-2a58ac69463c&Tim=1701866557991&Key=e56f3d44c62bb6f7"

### 网易云音乐版本号

网页版

### 操作系统

edge for mac

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by pk49800** [comment]
是不是没有设置MIGU_COOKIE

**Comment by wxchil** [comment]
> 是不是没有设置MIGU_COOKIE

设置了
-e MIGU_COOKIE="DF94898C97A6AA91649.......

我刚才登录了app,没有掉线,重新抓包,cookie确实有变化,我重部署下试试

**Comment by wxchil** [comment]
重新部署以后,专辑里有的正常了,前面几首歌还是不行(也有可能是缓存的事)
这个migu的cookie有效期多久呢?

**Comment by 1715173329** [comment]
咪咕的搜索接口一直有点问题，无解。周的歌用酷我就行
