### ISSUE TITLE
模仿SVIP但不能播放SVIP的音质如空间音频和超清母版

### ISSUE THREAD

**Issue by aliencaocao** [1715173329/UnblockNeteaseMusic#1318]
### 需求描述

![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/1665fe34-f051-4308-bc0c-39ce8619e635)
希望可以支持这两种音质
已经开了并且客户端显示是SVIP

### 网易云音乐版本号

3.0.0 build 210949

### 操作系统

Win 10

**Comment by chris7395328** [comment]
实测这两种音质都是网易云的ai算法升频，除了体质巨大和一些音染外毫无益处，原始最高的音质就到hire

**Comment by aliencaocao** [comment]
我其实是想体验空间音频，因为我入了个xm5

**Comment by M-HLSLY** [comment]
> 我其实是想体验空间音频，因为我入了个xm5

如果想体验的话，可以fork该项目后修改如下参数获后clone自己的项目运行![IMG_20231209_190924.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/4f164a02-464a-4551-b518-a4c14081ccc7)

jyeffect=>高清环绕声, sky=>沉浸环绕声, jymaster=>超清母带

注：如客户端显示仍显示“无损”或“Hi-Res”是正常的，实际match到的已经是对应音质了。另需要在较好的网络条件下使用，否则会出现加载缓慢的情况。（一般为等待2秒左右）

**Comment by M-HLSLY** [comment]
如果想体验的话，可以fork该项目后修改如下参数获后clone自己的项目运行
![IMG_20231209_190924.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/3821e0a1-a673-4662-8a4a-09c4d24f8a74)



jyeffect=>高清环绕声, sky=>沉浸环绕声, jymaster=>超清母带

注：如客户端显示仍显示“无损”或“Hi-Res”是正常的，实际match到的已经是对应音质了。由于这类音质体积巨大，加载时间较长！需要在较好的网络条件下使用，否则会出现加载缓慢的情况。（一般为等待2秒左右）

**Comment by aliencaocao** [comment]
好的，感谢

**Comment by aliencaocao** [comment]
可以保留hires和exhigh选项吗？比如我多加这些进去
另外，客户端要选哪个才是match到我改的？
![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/d608d867-1eb4-4a64-b28c-64fc5ce378b4)
现在是这四个都可以选

**Comment by chris7395328** [comment]
> 可以保留hires和exhigh选项吗？比如我多加这些进去 另外，客户端要选哪个才是match到我改的？ ![image](https://private-user-images.githubusercontent.com/20109683/289269513-d608d867-1eb4-4a64-b28c-64fc5ce378b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjI5MzQsIm5iZiI6MTcwMjEyMjYzNCwicGF0aCI6Ii8yMDEwOTY4My8yODkyNjk1MTMtZDYwOGQ4NjctMWViNC00YTY0LWIyOGMtNjRmYzVjZTM3OGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDExNTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhODMxMTZmNWJiODI1NTVjOWUyMTkxYmU3YzgxY2ZjMmY5ZjAwMGUyNWRmMzJlMjU2YzcxMDllMDJmYTlhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VIqJ3VZPQvi0DaGZ6CNKn_IyIvZk23BxGoFIkIUTB7Y) 现在是这四个都可以选

和你客户端选什么都无关，如果你设置是全部替换音源的话，优先选择母带，音源没有母带就到顺延到hire，以此类推，我之前没测试过环绕所以不知道会不会从母带顺延到环绕

**Comment by M-HLSLY** [comment]
> 可以保留hires和exhigh选项吗？比如我多加这些进去
> 另外，客户端要选哪个才是match到我改的？
> ![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/d608d867-1eb4-4a64-b28c-64fc5ce378b4)
> 现在是这四个都可以选

我觉得应该是加不了的，客户端的音质由服务器决定，“hires”和“exhigh”分别对应的应该是有无SELECT_MAX_BR=true这个环境变量

**Comment by aliencaocao** [comment]
> 和你客户端选什么都无关

但是现在我客户端选不同的音质可以明显感觉到加载时间的区别，说明都是有区别的啊？我开了flac 的环境变量

**Comment by chris7395328** [comment]
> > 和你客户端选什么都无关
> 
> 但是现在我客户端选不同的音质可以明显感觉到加载时间的区别，说明都是有区别的啊？我开了flac 的环境变量

如果你环境变量设置了MIN_BR=999000 和音源严格按照顺序，那就是优选用pyncmd的音源，这时候你客户端选标准都是会优先请求无损音质

**Comment by aliencaocao** [comment]
> 你环境变量设置了mr=999000 和音源严格按照顺序

这个倒是没有设置

那你的意思是我得设这个才能改fork吗

**Comment by chris7395328** [comment]
> > 你环境变量设置了mr=999000 和音源严格按照顺序
> 
> 这个倒是没有设置
> 
> 那你的意思是我得设这个才能改fork吗

环境变量是你启动服务器设置的，fork项目你只需要更改那个hires到jymaster就行。
你如果是windows做服务器就直接在电脑的环境变量添加对应的参数，dockers就参考说明文档

**Comment by M-HLSLY** [comment]
> > > 你环境变量设置了mr=999000 和音源严格按照顺序
> > 
> > 这个倒是没有设置
> > 
> > 那你的意思是我得设这个才能改fork吗
> 
> 环境变量是你启动服务器设置的，fork项目你只需要更改那个hires到jymaster就行。
> 你如果是windows做服务器就直接在电脑的环境变量添加对应的参数，dockers就参考说明文档

你先看一下debug先
![IMG_20231209_202430.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/6e6f0f9b-7974-4281-a4ae-84d888407e17)



看看你选不同音质的时候level后面是啥先……我已经被绕晕了(／_＼)

**Comment by aliencaocao** [comment]
我的意思是，如果我光改hires，环境变量不设mr=999000 和音源严格按照顺序，是否有效，因为我本来就没设
我是linux docker的

**Comment by M-HLSLY** [comment]
> > > 你环境变量设置了mr=999000 和音源严格按照顺序
> > 
> > 这个倒是没有设置
> > 
> > 那你的意思是我得设这个才能改fork吗
> 
> 环境变量是你启动服务器设置的，fork项目你只需要更改那个hires到jymaster就行。
> 你如果是windows做服务器就直接在电脑的环境变量添加对应的参数，dockers就参考说明文档

额……对应的参数……指的是？

**Comment by chris7395328** [comment]
> 我的意思是，如果我光改hires，环境变量不设mr=999000 和音源严格按照顺序，是否有效，因为我本来就没设 我是linux docker的

你不设环境变量就是全部默认参数啊，音源也没有限定，那你获取到kuwo还是网易都不一定，是按照最先响应的

**Comment by chris7395328** [comment]
> > > > 你环境变量设置了mr=999000 和音源严格按照顺序
> > > 
> > > 
> > > 这个倒是没有设置
> > > 那你的意思是我得设这个才能改fork吗
> > 
> > 
> > 环境变量是你启动服务器设置的，fork项目你只需要更改那个hires到jymaster就行。
> > 你如果是windows做服务器就直接在电脑的环境变量添加对应的参数，dockers就参考说明文档
> 
> 额……对应的参数……指的是？

0.0就是设置环境变

> > > > 你环境变量设置了mr=999000 和音源严格按照顺序
> > > 
> > > 
> > > 这个倒是没有设置
> > > 那你的意思是我得设这个才能改fork吗
> > 
> > 
> > 环境变量是你启动服务器设置的，fork项目你只需要更改那个hires到jymaster就行。
> > 你如果是windows做服务器就直接在电脑的环境变量添加对应的参数，dockers就参考说明文档
> 
> 额……对应的参数……指的是？

他没有设置环境变量可能压根就没请求到csm这个音源，得发debug才知道

**Comment by M-HLSLY** [comment]
> > > > > 你环境变量设置了mr=999000 和音源严格按照顺序
> > > > 
> > > > 
> > > > 这个倒是没有设置
> > > > 那你的意思是我得设这个才能改fork吗
> > > 
> > > 
> > > 环境变量是你启动服务器设置的，fork项目你只需要更改那个hires到jymaster就行。
> > > 你如果是windows做服务器就直接在电脑的环境变量添加对应的参数，dockers就参考说明文档
> > 
> > 额……对应的参数……指的是？
> 
> 0.0就是设置环境变
> 
> > > > > 你环境变量设置了mr=999000 和音源严格按照顺序
> > > > 
> > > > 
> > > > 这个倒是没有设置
> > > > 那你的意思是我得设这个才能改fork吗
> > > 
> > > 
> > > 环境变量是你启动服务器设置的，fork项目你只需要更改那个hires到jymaster就行。
> > > 你如果是windows做服务器就直接在电脑的环境变量添加对应的参数，dockers就参考说明文档
> > 
> > 额……对应的参数……指的是？
> 
> 他没有设置环境变量可能压根就没请求到csm这个音源，得发debug才知道

改hires参数成jymaster然后保持你原来那样就行了……音源不是可以用-o pyncmd解决吗……pyncmd对应的就是csm，api获取jymaster的br高于999000，但是项目最高显示999000……额……我绕晕了，我先看看去

**Comment by chris7395328** [comment]
> 
> 改hires参数成jymaster然后保持你原来那样就行了……音源不是可以用-o pyncmd解决吗……pyncmd对应的就是csm，api获取jymaster的br高于999000，但是项目最高显示999000……额……我绕晕了，我先看看去

设置999000是为了完全使用第三方音源，如果不设置如果本身曲子不用氪金可以有320k的话会直接用官方的，就不会让pyncmd工作了，是这个意思啦

**Comment by M-HLSLY** [comment]
> 
> > 
> > 改hires参数成jymaster然后保持你原来那样就行了……音源不是可以用-o pyncmd解决吗……pyncmd对应的就是csm，api获取jymaster的br高于999000，但是项目最高显示999000……额……我绕晕了，我先看看去
> 
> 设置999000是为了完全使用第三方音源，如果不设置如果本身曲子不用氪金可以有320k的话会直接用官方的，就不会让pyncmd工作了，是这个意思啦

Emmmmm所以？
哦，我解决了，看看
![IMG_20231209_204538.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/b31745dd-b5fe-448b-8f29-ab760bc25903)

![IMG_20231209_204618.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/4f2433e3-8634-4d8d-b625-f346f852e9c6)

![IMG_20231209_204601.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/fe4656e7-f4c5-4fc8-bedc-c6ca16949355)

- 我的配置和环境变量
![IMG_20231209_204519.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/24e2a5bb-83a5-4751-96db-b251f0ffa743)

![Screenshot_2023-12-09-20-31-39-97_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/a740b47c-cb21-4ff2-b0ba-a1b4d6af5313)

运行环境：zerotermux上的ubuntu proot容器

你要不先看看吧……我快晕了，改好的已经放我仓库里了

你说的不设999000就用官方的……其实SELECT_MAX_BR=true就是直接获取最高音质了，再加上-o pyncmd固定基本就没问题了……

**Comment by chris7395328** [comment]
> 你说的不设999000就用官方的……其实SELECT_MAX_BR=true就是直接获取最高音质了，再加上-o pyncmd固定基本就没问题了……

没毛病，获取最高也可以，不过我会几个音源一起用所以用到严格按照顺序的环境变量所以就不用这个变量了，那么问题来了题主看懂了没有（。

**Comment by M-HLSLY** [comment]
> 
> > 你说的不设999000就用官方的……其实SELECT_MAX_BR=true就是直接获取最高音质了，再加上-o pyncmd固定基本就没问题了……
> 
> 没毛病，获取最高也可以，不过我会几个音源一起用所以用到严格按照顺序的环境变量所以就不用这个变量了，那么问题来了题主看懂了没有（。

勉强懂了……我的也加了严格按照顺序啊
多音源也没什么问题啊……
![IMG_20231209_205921.jpg](https://github.com/UnblockNeteaseMusic/server/assets/102822186/b663422b-63d5-42de-8f98-f789733726d0)

**Comment by aliencaocao** [comment]
我这边debug没有啊
![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/b2792b83-04c3-4239-8821-af36834101a2)
全都是这种

**Comment by M-HLSLY** [comment]
> 我这边debug没有啊
> ![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/b2792b83-04c3-4239-8821-af36834101a2)
> 全都是这种

怪了，要不你fork项目自己改一下？我这个以前fork的，也不确定好不好使（至少我这跑的起来）

**Comment by aliencaocao** [comment]
我现在开的是这些
-e ENABLE_FLAC=true -e ENABLE_LOCAL_VIP=svip -e BLOCK_ADS=true -e SELECT_MAX_BR=true -e LOG_LEVEL=debug -e FOLLOW_SOURCE_ORDER=true
所以是开了严格按照顺序，但是我不知道怎么设置顺序，我是docker的

**Comment by aliencaocao** [comment]
我刚刚fork后用node 跑也是一样，没有任何request的log

**Comment by M-HLSLY** [comment]
> 我现在开的是这些
> -e ENABLE_FLAC=true -e ENABLE_LOCAL_VIP=svip -e BLOCK_ADS=true -e SELECT_MAX_BR=true -e LOG_LEVEL=debug -e FOLLOW_SOURCE_ORDER=true
> 所以是开了严格按照顺序，但是我不知道怎么设置顺序，我是docker的

用原来的变量试试

**Comment by M-HLSLY** [comment]
> 我刚刚fork后用node 跑也是一样，没有任何request的log

Node在我这压根跑不起来……我用的脚本解决的

**Comment by aliencaocao** [comment]
> 用原来的变量试试

这就是原来的变量

我加了min_br=9900000然后-o pyncmd 后看到和你一样的log了，但是我已经改了源码，还是请求的hires。。。
![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/3f2399ce-0416-44ad-b99c-0c435062884e)
![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/61d791cb-c9b4-49c3-8bf2-74c7c599e743)

**Comment by M-HLSLY** [comment]
> > 用原来的变量试试
> 
> 这就是原来的变量
> 
> 我加了min_br=9900000然后-o pyncmd 后看到和你一样的log了，但是我已经改了源码，还是请求的hires。。。
> ![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/3f2399ce-0416-44ad-b99c-0c435062884e)
> ![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/61d791cb-c9b4-49c3-8bf2-74c7c599e743)
> 

是在github里改完再clone的吗？

**Comment by aliencaocao** [comment]
是，本地也改了，我把两个都改成sky了，还是在请求hires

**Comment by M-HLSLY** [comment]
> 是，本地也改了，我把两个都改成sky了，还是在请求hires

我没用过doker，不太了解，看了文档也没看出问题。用linux环境跑一下？

**Comment by aliencaocao** [comment]
我就在linux

**Comment by M-HLSLY** [comment]
> 我就在linux

试过安装脚本了？
https://github.com/UnblockNeteaseMusic/install-scripts

**Comment by chris7395328** [comment]
> 是，本地也改了，我把两个都改成sky了，还是在请求hires

有没有检查docker的配置文件，有在自己项目设置好密钥注册自己的docker hub替换进去么，我之前有clone做过一次是没问题的记得

或者pull我的docker试试看 chris7395328/unblockncm
已经修改优先sky音质

**Comment by aliencaocao** [comment]
我是本地node 直接运行的，和docker没关系
我回头试试你的docker

**Comment by aliencaocao** [comment]
![image](https://github.com/UnblockNeteaseMusic/server/assets/20109683/d9df7dcd-2560-4d3b-87f8-47d29eb81eb5)
用了你的docker还是hires。。。是不是和我用v3.0客户端有关系？

**Comment by aliencaocao** [comment]
这个歌是有sky的，我手动修改api链接就可以下载到5.1 的flac

**Comment by aliencaocao** [comment]
另外我如果用docker，该怎么指定音源顺序？
我试了`docker run -d --name unblocknetease -e ENABLE_FLAC=true -e ENABLE_LOCAL_VIP=svip -e BLOCK_ADS=true -e SELECT_MAX_BR=true -e LOG_LEVEL=debug -e FOLLOW_SOURCE_ORDER=true -e MIN_BR=990000 --memory 4g --memory-swap -1 --restart always -p 5888:5888 -p 5889:5889 chris7395328/unblockncm -p 5888:5889 -s -o pyncmd -o kugou -o kuwo -o yt-dlp`
还有`docker run -d --name unblocknetease -e ENABLE_FLAC=true -e ENABLE_LOCAL_VIP=svip -e BLOCK_ADS=true -e SELECT_MAX_BR=true -e LOG_LEVEL=debug -e FOLLOW_SOURCE_ORDER=true -e MIN_BR=990000 --memory 4g --memory-swap -1 --restart always -p 5888:5888 -p 5889:5889 chris7395328/unblockncm -p 5888:5889 -s -o pyncmd kugou kuwo yt-dlp`都不行，docker直接就crash
