### ISSUE TITLE
无法启动 Error: connect ECONNREFUSED 59.111.179.213:80

### ISSUE THREAD

**Issue by c321474** [1715173329/UnblockNeteaseMusic#132]
最近几天突然就用不了了，之前一直都没有问题，方法1和方法2都试过了
`Error: connect ECONNREFUSED 59.111.179.213:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.179.213',
  port: 80`

也尝试过使用手机热点连接，一样会报错，80端口也没有被占用

**Comment by byludy** [comment]
手动多启动几次 我就是这样

**Comment by pan93412** [comment]
試試看參考[這個連結](https://github.com/acgotaku/NetEaseMusicWorld)更換網易雲音樂的 IP？

也可以試試看我使用的啟動 script：

```
node app.js -e https://music.163.com -s -p 8080:8081
```

**Comment by SaguruHakuba** [comment]
> node app.js -e https://music.163.com -s -p 8080:8081

问题依旧在啊。
![image](https://user-images.githubusercontent.com/22808988/132055794-4ba20cb6-715c-4ae1-bfb6-78da3ec5f2dd.png)

**Comment by 1715173329** [comment]
这是由于你的网络问题造成的，无法正常与网易云音乐服务器通讯。
在海外网络情况下比较严重。
![image](https://user-images.githubusercontent.com/22235437/132057504-6b72ec25-0994-4b87-b145-2fd765420d56.png)

**Comment by 1715173329** [comment]
猜测是由于网易云音乐的 [httpdns2](http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com) 造成的问题。
可以先试试将其禁用：
```patch
diff --git a/src/app.js b/src/app.js
index 428c008..09b3d45 100644
--- a/src/app.js
+++ b/src/app.js
@@ -129,7 +129,7 @@ const httpdns2 = (host) =>
 		);
 
 Promise.all(
-	[httpdns, httpdns2]
+	[httpdns]
 		.map((query) => query(target.join(',')))
 		.concat(target.map(dns))
 )
```

**Comment by c321474** [comment]
> 猜测是由于网易云音乐的 [httpdns2](http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com) 造成的问题。
> 可以先试试将其禁用：
> 
> ```diff
> diff --git a/src/app.js b/src/app.js
> index 428c008..09b3d45 100644
> --- a/src/app.js
> +++ b/src/app.js
> @@ -129,7 +129,7 @@ const httpdns2 = (host) =>
>  		);
>  
>  Promise.all(
> -	[httpdns, httpdns2]
> +	[httpdns]
>  		.map((query) => query(target.join(',')))
>  		.concat(target.map(dns))
>  )
> ```

删除掉httpdns2之后启动成功率显著提高了，非常感谢！

**Comment by pan93412** [comment]
@1715173329 我們要在 enhanced 套用這個 patch 嗎？之前想砍，但怕有副作用。還是我們用 environment variable？

**Comment by 1715173329** [comment]
> @1715173329 我們要在 enhanced 套用這個 patch 嗎？之前想砍，但怕有副作用。還是我們用 environment variable？

我个人觉得去掉 httpdns2 仅是一个 possible workaround，并不算真正的解决方案。

**Comment by 1715173329** [comment]
现在可以使用环境变量 `DISABLE_HTTPDNS` 以禁用 httpdns 查询，详细请看 README。

**Comment by pan93412** [comment]
有問題歡迎再重啟 Issue owo

**Comment by hwbai** [comment]
禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨

**Comment by c321474** [comment]
> 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨

可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD

**Comment by hwbai** [comment]
> > 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨
> 
> 可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD

感谢回答呀，请问切换音源就是不用网易云吗？还是什么其他的设置我没有弄呀

**Comment by c321474** [comment]
> > > 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨
> > 
> > 
> > 可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD
> 
> 感谢回答呀，请问切换音源就是不用网易云吗？还是什么其他的设置我没有弄呀

启动的时候-o 选择音源，如果是国内的话就用-o kuwo，可以去看这个项目原版的readme，里面有介绍

**Comment by pan93412** [comment]
> > > > 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨
> > > 
> > > 
> > > 可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD
> > 
> > 
> > 感谢回答呀，请问切换音源就是不用网易云吗？还是什么其他的设置我没有弄呀
> 
> 启动的时候-o 选择音源，如果是国内的话就用-o kuwo，可以去看这个项目原版的readme，里面有介绍

有個坑需要注意：`-o` 會把我們指定的預設來源清掉。最好是指定多一點：

    -o kuwo kugou ...

**Comment by pan93412** [comment]
> 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨

有設定 Proxy、安裝 ca.crt 和信任憑證嗎？此外啟動 UNM 之後必須完全重新啟動客戶端。

**Comment by hwbai** [comment]
> > > > > 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨
> > > > 
> > > > 
> > > > 可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD
> > > 
> > > 
> > > 感谢回答呀，请问切换音源就是不用网易云吗？还是什么其他的设置我没有弄呀
> > 
> > 
> > 启动的时候-o 选择音源，如果是国内的话就用-o kuwo，可以去看这个项目原版的readme，里面有介绍
> 
> 有個坑需要注意：`-o` 會把我們指定的預設來源清掉。如果執意要覆蓋，最好是指定多一點：
> 
> ```
> -o kuwo kugou ...
> ```

你好呀，我按照你说现在可以听啦！但是现在遇到了一个新问题就是打开网易云之后加载每一个页面都很慢……比如打开排行榜大概要两分钟，有啥办法可以加速吗，感谢感谢

**Comment by pan93412** [comment]
> > > > > > 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨
> > > > > 
> > > > > 
> > > > > 可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD
> > > > 
> > > > 
> > > > 感谢回答呀，请问切换音源就是不用网易云吗？还是什么其他的设置我没有弄呀
> > > 
> > > 
> > > 启动的时候-o 选择音源，如果是国内的话就用-o kuwo，可以去看这个项目原版的readme，里面有介绍
> > 
> > 
> > 有個坑需要注意：`-o` 會把我們指定的預設來源清掉。如果執意要覆蓋，最好是指定多一點：
> > ```
> > -o kuwo kugou ...
> > ```
> 
> 你好呀，我按照你说现在可以听啦！但是现在遇到了一个新问题就是打开网易云之后加载每一个页面都很慢……比如打开排行榜大概要两分钟，有啥办法可以加速吗，感谢感谢

你試試看用你電腦內建的瀏覽器進入 `music.163.com`，有可能是你的電腦沒完全信任憑證。

**Comment by hwbai** [comment]
> > > > > > > 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨
> > > > > > 
> > > > > > 
> > > > > > 可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD
> > > > > 
> > > > > 
> > > > > 感谢回答呀，请问切换音源就是不用网易云吗？还是什么其他的设置我没有弄呀
> > > > 
> > > > 
> > > > 启动的时候-o 选择音源，如果是国内的话就用-o kuwo，可以去看这个项目原版的readme，里面有介绍
> > > 
> > > 
> > > 有個坑需要注意：`-o` 會把我們指定的預設來源清掉。如果執意要覆蓋，最好是指定多一點：
> > > ```
> > > -o kuwo kugou ...
> > > ```
> > 
> > 
> > 你好呀，我按照你说现在可以听啦！但是现在遇到了一个新问题就是打开网易云之后加载每一个页面都很慢……比如打开排行榜大概要两分钟，有啥办法可以加速吗，感谢感谢
> 
> 你試試看用你電腦內建的瀏覽器進入 `music.163.com`，有可能是你的電腦沒完全信任憑證。

你好呀，我是在我的synology里面用docker跑的，像这种情况应该怎么解决呀～

**Comment by pan93412** [comment]
> > > > > > > > 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨
> > > > > > > 
> > > > > > > 
> > > > > > > 可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD
> > > > > > 
> > > > > > 
> > > > > > 感谢回答呀，请问切换音源就是不用网易云吗？还是什么其他的设置我没有弄呀
> > > > > 
> > > > > 
> > > > > 启动的时候-o 选择音源，如果是国内的话就用-o kuwo，可以去看这个项目原版的readme，里面有介绍
> > > > 
> > > > 
> > > > 有個坑需要注意：`-o` 會把我們指定的預設來源清掉。如果執意要覆蓋，最好是指定多一點：
> > > > ```
> > > > -o kuwo kugou ...
> > > > ```
> > > 
> > > 
> > > 你好呀，我按照你说现在可以听啦！但是现在遇到了一个新问题就是打开网易云之后加载每一个页面都很慢……比如打开排行榜大概要两分钟，有啥办法可以加速吗，感谢感谢
> > 
> > 
> > 你試試看用你電腦內建的瀏覽器進入 `music.163.com`，有可能是你的電腦沒完全信任憑證。
> 
> 你好呀，我是在我的synology里面用docker跑的，像这种情况应该怎么解决呀～

那你有

  1. 在你的電腦安裝 `ca.crt`
  2. 信任 `ca.crt`

嗎？如果有的話，不排除是 Synology 有限制了連入或連出連線，可能要看看他們的說明文件。

**Comment by hwbai** [comment]
> > > > > > > > > 禁用了DISABLE_HTTPDNS可以成功启动，但是还有好多歌是灰色的听不了唉😮‍💨
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 可以先试着换换音源，我是有少数歌不行，这种歌我都是去别处下载再传到云盘上听的. xD
> > > > > > > 
> > > > > > > 
> > > > > > > 感谢回答呀，请问切换音源就是不用网易云吗？还是什么其他的设置我没有弄呀
> > > > > > 
> > > > > > 
> > > > > > 启动的时候-o 选择音源，如果是国内的话就用-o kuwo，可以去看这个项目原版的readme，里面有介绍
> > > > > 
> > > > > 
> > > > > 有個坑需要注意：`-o` 會把我們指定的預設來源清掉。如果執意要覆蓋，最好是指定多一點：
> > > > > ```
> > > > > -o kuwo kugou ...
> > > > > ```
> > > > 
> > > > 
> > > > 你好呀，我按照你说现在可以听啦！但是现在遇到了一个新问题就是打开网易云之后加载每一个页面都很慢……比如打开排行榜大概要两分钟，有啥办法可以加速吗，感谢感谢
> > > 
> > > 
> > > 你試試看用你電腦內建的瀏覽器進入 `music.163.com`，有可能是你的電腦沒完全信任憑證。
> > 
> > 
> > 你好呀，我是在我的synology里面用docker跑的，像这种情况应该怎么解决呀～
> 
> 那你有
> 
> 1. 在你的電腦安裝 `ca.crt`
> 2. 信任 `ca.crt`
> 
> 嗎？如果有的話，不排除是 Synology 有限制了連入或連出連線，可能要看看他們的說明文件。

嗯嗯，我去找一下看看有没有人问类似的问题～我在手机上用网易云，是有安装描述文件的
