### ISSUE TITLE
目前无损音质是否必须要求自己提供vip信息，开启无损，无账号状态测试官方demo是低品质的

### ISSUE THREAD

**Issue by little-buddy** [1715173329/UnblockNeteaseMusic#1329]
### Bug 描述

调用官方的api demo，开启了无损音乐，但是返回的结果也才只有128000，是非无损的

### 启动命令及环境变量

```js
const match = require('@unblockneteasemusic/server');

const dotenv = require('dotenv');

dotenv.config();
/**
 * Set proxy or hosts if needed
 */
// global.proxy = require('url').parse('http://127.0.0.1:1080');
// global.hosts = { 'i.y.qq.com': '59.37.96.220' };

/**
 * Find matching song from other platforms
 * @param {Number} id netease song id
 * @param {Array<String>||undefined} source support qq, xiami, baidu, kugou, kuwo, migu, joox
 * @return {Promise<Object>}
 */
match(418602084, [
  'qq',
  'xiami',
  'baidu',
  'kugou',
  'kuwo',
  'migu',
  //   'joox',
]).then(console.log);

```

### 日志内容

<img width="585" alt="image" src="https://github.com/UnblockNeteaseMusic/server/assets/30054881/82c75d2e-258c-41ba-a7e4-580f13c45673">

### 网易云音乐版本号

无

### 操作系统

macos@13.6

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
没设置环境变量

**Comment by little-buddy** [comment]
有环境变量呀，通过 dotenv 导入的。
你的回答的意思就是当前版本依旧支持 解锁无损音乐？
而不是像网易云api一样需要vip账号请求？
@1715173329
