### ISSUE TITLE
启动失败 Error: connect ECONNREFUSED 59.111.179.214:80

### ISSUE THREAD

**Issue by byludy** [1715173329/UnblockNeteaseMusic#133]
由于服务器做了开机自启动，以及定时重启服务器，发现经常重启后进程没运行，就手动运行，看到如图错误，运行成功和运行失败的概率大概是失败的更多，服务器是美国的，不知道跟这个有没有关系。
项目已经更新到最新了。

![image](https://user-images.githubusercontent.com/56289598/131981467-84f75a9a-e5c7-42dd-8d5c-6887ed937639.png)
出现的错误是链接失败

Error: connect ECONNREFUSED 59.111.179.214:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.179.214',
  port: 80
}

Error: connect ECONNREFUSED 59.111.179.213:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '59.111.179.213',
  port: 80
}

**Comment by pan93412** [comment]
與 #132 問題相同。合併到同個討論串。
