### ISSUE TITLE
如何添加为Windows服务

### ISSUE THREAD

**Issue by fbstorm** [1715173329/UnblockNeteaseMusic#1330]
### Bug 描述

已经安装为依赖项
![image](https://github.com/UnblockNeteaseMusic/server/assets/100028477/556fc8e8-806e-4692-93ee-3665feaf5e59)

已经下载本项目，但不知道怎么  “  在项目根目录运行 node ./nw.js  ”
![image](https://github.com/UnblockNeteaseMusic/server/assets/100028477/e3d428c5-59be-46b7-9bf6-4a7c5e0f0e63)

### 启动命令及环境变量

没有

### 日志内容

不会

### 网易云音乐版本号

2.10.2

### 操作系统

Win10 22H2 内部版本19045.3448

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by fbstorm** [comment]
应该怎样添加到windows服务

**Comment by 1715173329** [comment]
先跑 yarn install 安装依赖
