### ISSUE TITLE
目前的pyncmd api寄了，希望可以替换这个新的api

### ISSUE THREAD

**Issue by chris7395328** [1715173329/UnblockNeteaseMusic#1369]
### 需求描述

csm那个api官网表示关站了，被版权了，目前还有这个api可用，希望可以换一下

感谢mario6714分享的一个新api:
来源：https://music.gdstudio.xyz/
作者：https://space.bilibili.com/13715770
API地址：[https://music.gdstudio.xyz/api.php?types=url&source=netease&br=[]&id=[]](https://music.gdstudio.xyz/api.php?types=url&source=netease&br=%5B%5D&id=%5B%5D)

[br]=999,320

我尝试fork修改进去发现没办法获取url，不知道什么原因

**Comment by mario6714** [comment]
How work?

Like this?

https://tools.qzxdp.cn/api/wyy_vip/parse?url=https://music.163.com/song?id=[19292984]&musicType=standard

https://tools.qzxdp.cn/api/wyy_vip/parse?url=https://music.163.com/song?id=19292984&musicType=hires

not working:

![imagen](https://github.com/UnblockNeteaseMusic/server/assets/32179719/6d741741-ec62-4983-ba1a-13665c12b11c)

![imagen](https://github.com/UnblockNeteaseMusic/server/assets/32179719/2cbc773b-4497-4bd9-97d3-8bc42aefb90f)

**Comment by mario6714** [comment]
And after one song send this:

https://tools.qzxdp.cn/free_unlock

**Comment by chris7395328** [comment]
> And after one song send this:
> 
> https://tools.qzxdp.cn/free_unlock

确实是有验证了，那我没办法了（

**Comment by mario6714** [comment]
Maybe this won't work for new source

**Comment by mario6714** [comment]
> How work?
> 
> Like this?
> 
> [https://tools.qzxdp.cn/api/wyy_vip/parse?url=https://music.163.com/song?id=[19292984]&musicType=standard](https://tools.qzxdp.cn/api/wyy_vip/parse?url=https://music.163.com/song?id=%5B19292984%5D&musicType=standard)
> 
> https://tools.qzxdp.cn/api/wyy_vip/parse?url=https://music.163.com/song?id=19292984&musicType=hires
> 
> not working:
> 
> ![imagen](https://private-user-images.githubusercontent.com/32179719/310161445-6d741741-ec62-4983-ba1a-13665c12b11c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTA4MDAsIm5iZiI6MTcwOTY1MDUwMCwicGF0aCI6Ii8zMjE3OTcxOS8zMTAxNjE0NDUtNmQ3NDE3NDEtZWM2Mi00OTgzLWJhMWEtMTM2NjVjMTJiMTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE0NTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZDllZWU3ZTYyZGNkYmRmMzk1MDE2NGViM2ZhMzNlNzE3MmNjMWNmMGU3Yzk1Y2E1MmM0ZmZiNmYzZTQ4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f8GSpHt6-aBzpVFoFtsyKxQuCyhDNFSHSsP2byVj7WI)
> 
> ![imagen](https://private-user-images.githubusercontent.com/32179719/310164452-2cbc773b-4497-4bd9-97d3-8bc42aefb90f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTA4MDAsIm5iZiI6MTcwOTY1MDUwMCwicGF0aCI6Ii8zMjE3OTcxOS8zMTAxNjQ0NTItMmNiYzc3M2ItNDQ5Ny00YmQ5LTk3ZDMtOGJjNDJhZWZiOTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE0NTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzNiMDNjNDJiNWVjZjhhYzQ5OWJiNmE3MWEzYjZhNGQ1ZGU5NDg1MDY4NmE0MWYyZjE2NGNkNTY3ZjQwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oMJ5zHxGq6quNx7AEyzD8lhFno-Tdgtl86YTtRc_GZY)

Just a quick try

**Comment by M-HLSLY** [comment]
提供一个新api:
来源：https://music.gdstudio.xyz/
作者：https://space.bilibili.com/13715770
API地址：https://music.gdstudio.xyz/api.php?types=url&source=netease&br=[]&id=[]

[br]=999,320

**Comment by chris7395328** [comment]
> 提供一个新api: 来源：https://music.gdstudio.xyz/ 作者：https://space.bilibili.com/13715770 API地址：[https://music.gdstudio.xyz/api.php?types=url&source=netease&br=[]&id=[]](https://music.gdstudio.xyz/api.php?types=url&source=netease&br=%5B%5D&id=%5B%5D)
> 
> [br]=999,320

@1715173329 大佬有空搓一下~
