### ISSUE TITLE
repo内生成的网易云证书于2024年3月12日过期导致网络错误

### ISSUE THREAD

**Issue by rcy17** [1715173329/UnblockNeteaseMusic#1373]
### Bug 描述

我使用了配置CA证书+系统代理的方式使用项目，注意到今天开始无法正常使用，app内报告网络错误，进一步探索发现是因为证书过期的缘故。

![screenshot-20240312-153409](https://github.com/UnblockNeteaseMusic/server/assets/31961869/3efcf555-1e29-4627-9a16-713d067b6fe0)

这与 commit 370d0d95730e863f1d5567600c2d0048039c0761 在 2023年3月13日更新证书的记录一致，我猜测需要再次更新证书并发布新版本以修复问题。 

### 启动命令及环境变量

略

### 日志内容

略

### 网易云音乐版本号

略

### 操作系统

略

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by zhongjieyang** [comment]
今天也是没法用了

**Comment by Extreme-Icer** [comment]
@1715173329

**Comment by catsimple** [comment]
./generate-cert.sh

**Comment by rcy17** [comment]
对于其他受困于这一 issue 的用户：[generate-cert.sh](https://github.com/UnblockNeteaseMusic/server/blob/enhanced/generate-cert.sh) 可以一键生成全新证书（包含ca根证书，需要重新添加信任），我使用这一办法暂时解决了问题，但我相信目前的过期证书会对越来越多的用户造成困扰，可能并非所有用户都有方便的环境执行这一操作，期待 @1715173329 尽快renew证书。

**Comment by Extreme-Icer** [comment]
https://github.com/Extreme-Icer/unm-server/releases/tag/0.27.6-dev
可从这里下载。

**Comment by catshitz** [comment]
确实连不上 不能用了

**Comment by redn3ck** [comment]
> 对于其他受困于这一 issue 的用户：[generate-cert.sh](https://github.com/UnblockNeteaseMusic/server/blob/enhanced/generate-cert.sh) 可以一键生成全新证书（包含ca根证书，需要重新添加信任），我使用这一办法暂时解决了问题，但我相信目前的过期证书会对越来越多的用户造成困扰，可能并非所有用户都有方便的环境执行这一操作，期待 @1715173329 尽快renew证书。

感谢，已解决，另外贴上新证书ca.crt，不方便生成新证书的童鞋直接拿去用就好，另存为ca.crt就好
`chmod +x generate-cert.sh`
`./generate-cert.sh`

![ca crt](https://github.com/UnblockNeteaseMusic/server/assets/12512242/18805168-3f9f-46b2-b562-b1ea28ed797c)

**Comment by yxok200** [comment]
> > 对于其他受困于这一 issue 的用户：[generate-cert.sh](https://github.com/UnblockNeteaseMusic/server/blob/enhanced/generate-cert.sh) 可以一键生成全新证书（包含ca根证书，需要重新添加信任），我使用这一办法暂时解决了问题，但我相信目前的过期证书会对越来越多的用户造成困扰，可能并非所有用户都有方便的环境执行这一操作，期待 @1715173329 尽快renew证书。
> 
> 感谢，已解决，另外贴上新证书ca.crt，不方便生成新证书的童鞋直接拿去用就好，另存为ca.crt就好 `chmod +x generate-cert.sh` `./generate-cert.sh`
> 
> ![ca crt](https://private-user-images.githubusercontent.com/12512242/312336821-18805168-3f9f-46b2-b562-b1ea28ed797c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNjMzMTcsIm5iZiI6MTcxMDM2MzAxNywicGF0aCI6Ii8xMjUxMjI0Mi8zMTIzMzY4MjEtMTg4MDUxNjgtM2Y5Zi00NmIyLWI1NjItYjFlYTI4ZWQ3OTdjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDIwNTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMDkxM2Y5MTJlNzEwZTBmODU5NDgzNTcxZjJkZDdmZTc0ODBlYWY2NWZlYzRlMDY1NDlkMGFjMzc4NmI2ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iGbDroKG5pf4CVCVsAOEp5l1YC4CXNlHp7qvaoVR7iY)

我运行./generate-cert.sh不知道出啥问题了，没有更新证书
![image](https://github.com/UnblockNeteaseMusic/server/assets/23090472/52ccdc82-c29f-4891-8e29-5c6cb7a037f2)

**Comment by redn3ck** [comment]
> 我运行./generate-cert.sh不知道出啥问题了，没有更新证书 ![image](https://private-user-images.githubusercontent.com/23090472/312617934-52ccdc82-c29f-4891-8e29-5c6cb7a037f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODI2NTUsIm5iZiI6MTcxMDM4MjM1NSwicGF0aCI6Ii8yMzA5MDQ3Mi8zMTI2MTc5MzQtNTJjY2RjODItYzI5Zi00ODkxLThlMjktNWM2Y2I3YTAzN2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyMTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZTFjYzU0MzY1ZTZhMTJkY2ExMzY0NzQxNzkwYzI1NWNlZTI5ZmQzMGM2MjY2YzhlMjQ2MzljMDMzYTE0MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUKfaB_iuq2ti0gbSc94GkB-FqnFtA-11IKrf2MjNAA)

你这是win环境的cmd，各个路径就不对，没法运行，你用我发的ca吧

**Comment by IMFsy** [comment]
> > 我运行./generate-cert.sh不知道出啥问题了，没有更新证书 ![image](https://private-user-images.githubusercontent.com/23090472/312617934-52ccdc82-c29f-4891-8e29-5c6cb7a037f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODI2NTUsIm5iZiI6MTcxMDM4MjM1NSwicGF0aCI6Ii8yMzA5MDQ3Mi8zMTI2MTc5MzQtNTJjY2RjODItYzI5Zi00ODkxLThlMjktNWM2Y2I3YTAzN2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyMTIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZTFjYzU0MzY1ZTZhMTJkY2ExMzY0NzQxNzkwYzI1NWNlZTI5ZmQzMGM2MjY2YzhlMjQ2MzljMDMzYTE0MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUKfaB_iuq2ti0gbSc94GkB-FqnFtA-11IKrf2MjNAA)
> 
> 你这是win环境的cmd，各个路径就不对，没法运行，你用我发的ca吧

使用的你发的ca.crt 网易云还是显示无网络

**Comment by redn3ck** [comment]
> 使用的你发的ca.crt 网易云还是显示无网络

可能是生成的server.crt要对应，所以单独的ca不能用，那你就用楼上的那里下载吧

**Comment by windy1021** [comment]
> > 使用的你发的ca.crt 网易云还是显示无网络
> 
> 可能是生成的server.crt要对应，所以单独的ca不能用，那你就用楼上的那里下载吧

请问下上面那个exe文件下载完要怎么用，我之前是注册成 Windows 服务使用的，我双击后只有一个弹窗弹出来就消失了

**Comment by redn3ck** [comment]
> 请问下上面那个exe文件下载完要怎么用，我之前是注册成 Windows 服务使用的，我双击后只有一个弹窗弹出来就消失了

肯定要加参数运行的啊大兄弟，本项目的release和上面的不是一样的么。。。

**Comment by RiftRays** [comment]
请问一下docker如何更换容器内的证书？

**Comment by 631894570** [comment]
> 请问一下码头工人如何更换容器内的证书？

我是进入容器sh，/app目录下的server.crt 和.key  使用vi全部删除后，贴进去新的后重启容器可用；直接wget文件用不了，不清楚为啥
