### ISSUE TITLE
遇到了报错

### ISSUE THREAD

**Issue by windy1021** [1715173329/UnblockNeteaseMusic#1376]
### Bug 描述

之前成功安装并运行过，今天显示网络错误没找到原因想重装，但在运行node ./nw.js时遇到了这个报错，尝试安装node-windows 模块也没有效果，不知道是不是我装错位置了？对这方面不太懂，，求大佬看看，顺便问下那个网络过期的问题要怎么解决
<img src="https://s3.bmp.ovh/imgs/2024/03/14/6a801f09b2d6a528.png"  />

### 预期行为

正常安装并运行

### 实际行为

如上所述

### 复现步骤

如上所述

### 启动命令及环境变量

node ./nw.js
<img src="https://s3.bmp.ovh/imgs/2024/03/14/bb5c2ffa710ba0d6.png"  />

### 日志内容

无

### 网易云音乐版本号

2.10.12

### 操作系统

windows11

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by kohakox** [comment]
证书过期问题已经更新  尝试在当前目录下运行   npm link node-windows    命令、然后运行 node nw.js

**Comment by windy1021** [comment]
今天git pull后又正常工作了
