### ISSUE TITLE
注册windows服务，双击exe文件启动不了。手动或者用命令启动，

### ISSUE THREAD

**Issue by jukk8866** [1715173329/UnblockNeteaseMusic#1378]
### Bug 描述

双击EXE
![1710847791676](https://github.com/UnblockNeteaseMusic/server/assets/122716213/c1a3de97-048c-42f7-86ea-3cef1d5c32d8)
手动或者用命令
![image](https://github.com/UnblockNeteaseMusic/server/assets/122716213/cebfece1-2ad8-4e13-91e3-44fb01576338)
没有日志
![image](https://github.com/UnblockNeteaseMusic/server/assets/122716213/22656e91-763f-40c8-a4e0-3b62de4aae42)

issue里面基本都搜了，没找到解决方法

### 启动命令及环境变量

const svc = new Service({
	name: 'unblock-netease-cloud-music',
	description: '点亮网易云音乐灰色歌曲',
	script: './app.js', // 入口文件路径
	scriptOptions:'-p 52100:52101', // 可选参数示例: 自定义端口并开启HTTPS
	scriptOptions: '-o qq kugou kuwo ytdlp bilibili', // 可选参数
	scriptOptions: '-e https://music.163.com/', // 可选参数
	wait: '1', // 程序崩溃后重启时间间隔
	grow: '0.25', // 重启等待时间成长值，第一次1秒，第二次1.25秒。。。
	maxRestarts: '40', // 60秒内最大重启次数
	env: [
		{
			name: 'ENABLE_FLAC', //激活无损音质获取
			value: 'true',
		},
		{
			name: 'ENABLE_LOCAL_VIP=svip', 
			value: 'true',
			//ENABLE_LOCAL_VIP=svip
		},
		{
			name: 'MIN_BR',//允许的最低源音质，小于该值将被替换
			value:'320000',
		},
		{
			name: 'SELECT_MAX_BR',//选择所有音源中的最高码率替换音频
			value: 'true',
		},
		{
			name: 'FOLLOW_SOURCE_ORDER',//严格按照配置音源的顺序进行查询
			value: 'true',
		},
		// {
		// 	name: 'QQ_COOKIE',
		// 	value: 'uin=<your_uin>; qm_keyst=<your_qm_keyst>',
		// },
	],
});

### 日志内容

.

### 网易云音乐版本号

2.10

### 操作系统

win11

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [ ] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by BigMajesty** [comment]
不用启动，注册后（即命令行输入node ./nw.js后），已经作为服务运行在你的电脑上了
![image](https://github.com/UnblockNeteaseMusic/server/assets/103768015/1d8cae62-e257-4d78-b2e5-b1f3dc3b508b)

**Comment by jukk8866** [comment]
是的，我注册了，然后我的这个服务状态是关闭的，你的显示正在运行，
![image](https://github.com/UnblockNeteaseMusic/server/assets/122716213/4bf2cf0c-4038-4d6e-9dfd-e2010da5de0a)
 


运行第二次是卸载，但是好像没有卸载
 `C:\Users\JUIK\Desktop\0\wyy>node ./nw.js
{
  loc: 'winsw.js ~line 77',
  xml: [
    { id: 'unblockneteasecloudmusic.exe' },
    { name: 'unblock-netease-cloud-music' },
    { description: '点亮网易云音乐灰色歌曲' },
    { executable: 'E:\\appp\\node\\node.exe' },
    { argument: '--harmony' },
    {
      argument: 'E:\\appp\\node\\node_global\\node_modules\\node-windows\\lib\\wrapper.js'
    }
  ],
  config: {
    name: 'unblock-netease-cloud-music',
    id: 'unblockneteasecloudmusic.exe',
    nodeOptions: '--harmony',
    script: 'E:\\appp\\node\\node_global\\node_modules\\node-windows\\lib\\wrapper.js',
    scriptOptions: '',
    wrapperArgs: [
      '--file',
      'C:\\Users\\JUIK\\Desktop\\0\\wyy\\app.js',
      '--scriptoptions=',
      '--log',
      'unblock-netease-cloud-music wrapper',
      '--grow',
      '0.25',
      '--wait',
      '1',
      '--maxrestarts',
      '40',
      '--abortonerror',
      'n',
      '--stopparentfirst',
      undefined
    ],
    description: '点亮网易云音乐灰色歌曲',
    logpath: null,
    env: [],
    execPath: null,
    logOnAs: {
      account: null,
      password: null,
      domain: 'JUIK',
      mungeCredentialsAfterInstall: true
    },
    workingdirectory: 'C:\\Users\\JUIK\\Desktop\\0\\wyy',
    stopparentfirst: undefined,
    stoptimeout: 30,
    logmode: 'rotate',
    logging: undefined,
    allowServiceLogon: undefined
  }
}
Installation completed.

C:\Users\JUIK\Desktop\0\wyy>node ./nw.js
node:fs:1874
  binding.unlink(path);
          ^

Error: EPERM: operation not permitted, unlink 'C:\Users\JUIK\Desktop\0\wyy\daemon\unblockneteasecloudmusic.exe'
    at Object.unlinkSync (node:fs:1874:11)
    at rm (E:\appp\node\node_global\node_modules\node-windows\lib\daemon.js:602:22)
    at E:\appp\node\node_global\node_modules\node-windows\lib\daemon.js:615:15
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:337:12) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\Users\\JUIK\\Desktop\\0\\wyy\\daemon\\unblockneteasecloudmusic.exe'`

**Comment by BigMajesty** [comment]
这些错误信息表明你的服务已经安装，但是在启动后立即停止了。这可能是因为 UnblockNeteaseMusic 应用在启动后遇到了错误，或者它在没有接收到任何请求时自动停止了。

以下是一些可能的解决方法：

1. **检查 UnblockNeteaseMusic 应用：** 你应该首先确认 UnblockNeteaseMusic 应用是否可以正常运行。你可以尝试直接运行 `app.js` 文件，看是否有任何错误信息。如果应用在运行时崩溃或者显示错误信息，那么你需要解决这些问题。

2. **检查服务的日志：** `node-windows` 模块应该会生成一个日志文件，记录服务的运行情况。你可以在这个日志文件中查找更详细的错误信息。默认的日志文件路径是 `C:\Users\YourUsername\.node-windows\daemon\`，你可以在这个目录下查找日志文件。

3. **检查服务的配置：** 你的服务配置可能有一些问题。例如，你的 `scriptOptions` 属性被设置了三次，只有最后一次的设置会生效。你应该把所有的选项合并到一个字符串中，像这样：`scriptOptions: '-p 52100:52101 -o qq kugou kuwo ytdlp bilibili -e https://music.163.com/'`。

4. **尝试手动启动服务：** 你可以在 Windows 的 "服务" 管理器中手动启动你的服务。如果服务在启动后立即停止，那么可能是 UnblockNeteaseMusic 应用在启动后遇到了错误。

 上面是gpt生成的回答，或许你可以参考下。

你可以试一下启动app.js文件（同样目录下输入，node app.js)看看能不能正常运行
不行的话，如果你能提供更详细的信息，我可以帮你问下gpt（我也不懂）

**Comment by jukk8866** [comment]
解决了 我配置的有问题应该，然后前面的又没删干净

**Comment by BigMajesty** [comment]
哈哈，恭喜

**Comment by BigMajesty** [comment]
哈哈，恭喜

**Comment by jukk8866** [comment]
谢谢你，你改了配置文件吗

**Comment by BigMajesty** [comment]
没有，我第一次是下载的exe程序，结果网易云内部改了相应的端口，测试连接可行，但是显示没有网络
第二次注册的服务，刚开始按流程操作还是不行，后来我尝试重新安装证书，就成功了
似乎不能单独安装crt，需要下载zip，然后在解压后的文件夹下点击crt安装才行

**Comment by jukk8866** [comment]
这样，我是直接安装的crt 可以用
