### ISSUE TITLE
希望可以加入 Proxy Authentication 增加安全性

### ISSUE THREAD

**Issue by canc3s** [1715173329/UnblockNeteaseMusic#1379]
### 需求描述

希望可以加入 Proxy Authentication 增加安全性

**Comment by xream** [comment]
我一般网易云音乐解锁代理不开严格模式, 然后在前面套一个 VMess. 这样更稳一些(个人经验

**Comment by canc3s** [comment]
感谢，麻烦问一下套 VMess 被墙的概率会不会增加呢

**Comment by tillsunrise** [comment]
> 我一般网易云音乐解锁代理不开严格模式, 然后在前面套一个 VMess. 这样更稳一些(个人经验

大佬，请问套了vmess怎么让只有网易云的流量走呢，不然其他流量都走代理了

**Comment by canc3s** [comment]
> > 我一般网易云音乐解锁代理不开严格模式, 然后在前面套一个 VMess. 这样更稳一些(个人经验
> 
> 大佬，请问套了vmess怎么让只有网易云的流量走呢，不然其他流量都走代理了

直接写规则不就行了

**Comment by 1715173329** [comment]
之前 nondanee 加过貌似不工作，后面索性移除了，还是借助第三方工具吧。

**Comment by 1715173329** [comment]
之前 nondanee 加过貌似不工作，后面索性移除了，还是借助第三方工具吧。
