### ISSUE TITLE
我是第三方源pyncmd站长，请更换API链接

### ISSUE THREAD

**Issue by gdstudio-org** [1715173329/UnblockNeteaseMusic#1395]
### 需求描述

你好，我是GD音乐台(music.gdstudio.xyz)的站长。我发现该repo在未经过本人许可的情况下调用我站API（详见：`https://github.com/UnblockNeteaseMusic/server/issues/1369`），给网站带来大量不明流量，希望作者能处理下。

### 预期行为

1、更换第三方API源，从`https://music.gdstudio.xyz/api.php`更改为`https://music-api.gdstudio.xyz/api.php`，参数保留不变。我会尽量保留源站的所有功能，包括无损接口，只是希望鸡蛋不要放同个篮子，分开管理会更合理些。
2、源站API（music.gdstudio.xyz）将在3天后限制对外访问权限，新API（music-api.gdstudio.xyz）无此限制。为了大家的使用体验，请作者能尽快更换。
3、API不但提供网易云接口，其它音乐源同样可用，包括但不限于：('netease', 'tencent', 'kugou', 'baidu', 'kuwo', 'migu', 'joox', 'tidal', 'qobuz', 'ytmusic', 'deezer', 'spotify', 'netease_album', 'kuwo_album', 'migu_album', 'tidal_album', 'qobuz_album', 'ytmusic_album', 'deezer_album', 'spotify_album', 'tencent_album', 'netease_playlist')。功能包括：获取音乐url、封面图、歌词、单曲/专辑/歌单搜索等。有意向的开发者可通过B站私信与我联系，获取API的详细使用说明。
4、若使用我提供的API，还请注明出处（music.gdstudio.xyz），谢谢。我会尽我所能维护此API，愿项目长久！

**Comment by pan93412** [comment]
这里根据您的建议做了修改 (#1396)，再麻烦您检阅一下～

**Comment by gdstudio-org** [comment]
谢谢～这修改速度真的无敌，合作愉快！

**Comment by 1715173329** [comment]
非常抱歉给您带来不必要的麻烦，现已更新相关代码并添加 Credits。
同时也感谢您提供的公共 API，如果还有其他问题，请随时提出~

**Comment by gdstudio-org** [comment]
好的谢谢！作为UNM的老用户，我也很高兴能以这种方式为社区提供帮助。如有需要使用更多音乐源的无损接口，欢迎随时与我联系

**Comment by mario6714** [comment]
> ### 需求描述
> 
> 你好，我是GD音乐台(music.gdstudio.xyz)的站长。我发现该repo在未经过本人许可的情况下调用我站API（详见：`https://github.com/UnblockNeteaseMusic/server/issues/1369`），给网站带来大量不明流量，希望作者能处理下。
> ### 预期行为
> 
> 1、更换第三方API源，从`https://music.gdstudio.xyz/api.php`更改为`https://music-api.gdstudio.xyz/api.php`，参数保留不变。我会尽量保留源站的所有功能，包括无损接口，只是希望鸡蛋不要放同个篮子，分开管理会更合理些。 2、源站API（music.gdstudio.xyz）将在3天后限制对外访问权限，新API（music-api.gdstudio.xyz）无此限制。为了大家的使用体验，请作者能尽快更换。 3、API不但提供网易云接口，其它音乐源同样可用，包括但不限于：('netease', 'tencent', 'kugou', 'baidu', 'kuwo', 'migu', 'joox', 'tidal', 'qobuz', 'ytmusic', 'deezer', 'spotify', 'netease_album', 'kuwo_album', 'migu_album', 'tidal_album', 'qobuz_album', 'ytmusic_album', 'deezer_album', 'spotify_album', 'tencent_album', 'netease_playlist')。功能包括：获取音乐url、封面图、歌词、单曲/专辑/歌单搜索等。有意向的开发者可通过B站私信与我联系，获取API的详细使用说明。 4、若使用我提供的API，还请注明出处（music.gdstudio.xyz），谢谢。我会尽我所能维护此API，愿项目长久！
> ### 网易云音乐版本号
> 
> _No response_
> ### 操作系统
> 
> _No response_
> ### 其他信息
> 
> _No response_

One question , can i ask how to use the api for example for "kuwo"? thanks

**Comment by gdstudio-org** [comment]
> > ### 需求描述
> > 你好，我是GD音乐台(music.gdstudio.xyz)的站长。我发现该repo在未经过本人许可的情况下调用我站API（详见：`https://github.com/UnblockNeteaseMusic/server/issues/1369`），给网站带来大量不明流量，希望作者能处理下。
> > ### 预期行为
> > 1、更换第三方API源，从`https://music.gdstudio.xyz/api.php`更改为`https://music-api.gdstudio.xyz/api.php`，参数保留不变。我会尽量保留源站的所有功能，包括无损接口，只是希望鸡蛋不要放同个篮子，分开管理会更合理些。 2、源站API（music.gdstudio.xyz）将在3天后限制对外访问权限，新API（music-api.gdstudio.xyz）无此限制。为了大家的使用体验，请作者能尽快更换。 3、API不但提供网易云接口，其它音乐源同样可用，包括但不限于：('netease', 'tencent', 'kugou', 'baidu', 'kuwo', 'migu', 'joox', 'tidal', 'qobuz', 'ytmusic', 'deezer', 'spotify', 'netease_album', 'kuwo_album', 'migu_album', 'tidal_album', 'qobuz_album', 'ytmusic_album', 'deezer_album', 'spotify_album', 'tencent_album', 'netease_playlist')。功能包括：获取音乐url、封面图、歌词、单曲/专辑/歌单搜索等。有意向的开发者可通过B站私信与我联系，获取API的详细使用说明。 4、若使用我提供的API，还请注明出处（music.gdstudio.xyz），谢谢。我会尽我所能维护此API，愿项目长久！
> > ### 网易云音乐版本号
> > _No response_
> > ### 操作系统
> > _No response_
> > ### 其他信息
> > _No response_
> 
> One question , can i ask how to use the api for example for "kuwo"? thanks

The last time I maintained the kuwo API is about half year ago, and I don't think it can work functionally. Maybe it can only get the 128k resource currently. So I highly recommend you to use some music sources which music.gdstudio.xyz is using now, such as tencent, tidal, etc. These music sources have stable Hi-Res options and will get maintained for a long time.
The usage of my APIs to get a track url is very simple. Try to make a GET request in this format: `https://music-api.gdstudio.xyz/api.php?types=url&source=[MUSIC SOURCE]&id=[TRACK ID]&br=[128/192/320/740/999]`

**Comment by mario6714** [comment]
> > > ### 需求描述
> > > 你好，我是GD音乐台(music.gdstudio.xyz)的站长。我发现该repo在未经过本人许可的情况下调用我站API（详见：`https://github.com/UnblockNeteaseMusic/server/issues/1369`），给网站带来大量不明流量，希望作者能处理下。
> > > ### 预期行为
> > > 1、更换第三方API源，从`https://music.gdstudio.xyz/api.php`更改为`https://music-api.gdstudio.xyz/api.php`，参数保留不变。我会尽量保留源站的所有功能，包括无损接口，只是希望鸡蛋不要放同个篮子，分开管理会更合理些。 2、源站API（music.gdstudio.xyz）将在3天后限制对外访问权限，新API（music-api.gdstudio.xyz）无此限制。为了大家的使用体验，请作者能尽快更换。 3、API不但提供网易云接口，其它音乐源同样可用，包括但不限于：('netease', 'tencent', 'kugou', 'baidu', 'kuwo', 'migu', 'joox', 'tidal', 'qobuz', 'ytmusic', 'deezer', 'spotify', 'netease_album', 'kuwo_album', 'migu_album', 'tidal_album', 'qobuz_album', 'ytmusic_album', 'deezer_album', 'spotify_album', 'tencent_album', 'netease_playlist')。功能包括：获取音乐url、封面图、歌词、单曲/专辑/歌单搜索等。有意向的开发者可通过B站私信与我联系，获取API的详细使用说明。 4、若使用我提供的API，还请注明出处（music.gdstudio.xyz），谢谢。我会尽我所能维护此API，愿项目长久！
> > > ### 网易云音乐版本号
> > > _No response_
> > > ### 操作系统
> > > _No response_
> > > ### 其他信息
> > > _No response_
> > 
> > 
> > One question , can i ask how to use the api for example for "kuwo"? thanks
> 
> The last time I maintained the kuwo API is about half year ago, and I don't think it can work functionally. Maybe it can only get the 128k resource currently. So I highly recommend you to use some music sources which music.gdstudio.xyz is using now, such as tencent, tidal, etc. These music sources have stable Hi-Res options and will get maintained for a long time. The usage of my APIs to get a track url is very simple. Try to make a GET request in this format: `https://music-api.gdstudio.xyz/api.php?types=url&source=[MUSIC SOURCE]&id=[TRACK ID]&br=[128/192/320/740/999]`

Cool thanks, i am going to try

**Comment by gdstudio-org** [comment]
API使用文档已更新：https://music-api.gdstudio.xyz/api.php

**Comment by one-pyy** [comment]
站长您好，现在这个链接因为证书过期已经不能使用了，能麻烦修复一下嘛

**Comment by gdstudio-org** [comment]
> 站长您好，现在这个链接因为证书过期已经不能使用了，能麻烦修复一下嘛

网站SSL证书已续签。自动续签脚本出了点问题，目前已解决，感谢反馈

**Comment by SergioZgz** [comment]
> > 站长您好，现在这个链接因为证书过期已经不能使用了，能麻烦修复一下嘛
> 
> 网站SSL证书已续签。自动续签脚本出了点问题，目前已解决，感谢反馈

Then we could use your API in public projects? Of course I will label you

**Comment by gdstudio-org** [comment]
> > > 站长您好，现在这个链接因为证书过期已经不能使用了，能麻烦修复一下嘛
> > 
> > 
> > 网站SSL证书已续签。自动续签脚本出了点问题，目前已解决，感谢反馈
> 
> Then we could use your API in public projects? Of course I will label you

Sure! Feel free to use this developer API, as long as you follow the rules listed in the API page. Leave me a github comment or email me if you have trouble of using it. Good luck!

**Comment by SergioZgz** [comment]
> > > > 站长您好，现在这个链接因为证书过期已经不能使用了，能麻烦修复一下嘛
> > > 
> > > 
> > > 网站SSL证书已续签。自动续签脚本出了点问题，目前已解决，感谢反馈
> > 
> > 
> > Then we could use your API in public projects? Of course I will label you
> 
> Sure! Feel free to use this developer API, as long as you follow the rules listed in the API page. Leave me a github comment or email me if you have trouble of using it. Good luck!

Thank you so much !!!  I will just use netease, I think it is the option that will use the least resources on your server and is 100% perfect for me.
