### ISSUE TITLE
comm:87ff628无法运行“app.js:139:36 ”“app.js:139:11”

### ISSUE THREAD

**Issue by 4860575** [1715173329/UnblockNeteaseMusic#140]
root@Debian:~/UnblockNeteaseMusic# git log
commit 87ff628c10c7dd335ae4531d030775df3315dad9 (HEAD -> enhanced, origin/enhanced, origin/HEAD)
Author: Yi-Jyun Pan <pan93412@gmail.com>
Date:   Mon Sep 6 21:52:03 2021 +0800
日志如下：
root@Debian:~# node /root/UnblockNeteaseMusic-b/app.js
TypeError: array.forEach is not a function
    at /root/UnblockNeteaseMusic-b/src/app.js:139:36
    at Array.forEach (<anonymous>)
    at /root/UnblockNeteaseMusic-b/src/app.js:139:11

**Comment by pan93412** [comment]
你幫我輸入一下 `node -v`

**Comment by 4860575** [comment]
> node -v

root@Debian:~/UnblockNeteaseMusic# node -v
v14.17.6

**Comment by pan93412** [comment]
修好了。試試看 35a89fb
