### ISSUE TITLE
酷我音源寄了

### ISSUE THREAD

**Issue by catsimple** [1715173329/UnblockNeteaseMusic#1405]
### Bug 描述

kwplayer_ar_8.5.5.0_apk_keluze.apk
这个接口已经关掉了

### 启动命令及环境变量

/

### 日志内容

/

### 网易云音乐版本号

/

### 操作系统

/

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by Guciliang** [comment]
确实寄了

**Comment by Jia060117** [comment]
是的 寄了

**Comment by pan93412** [comment]
@939163156 你的能用嗎

**Comment by john7125** [comment]
确实不能用了，等大佬修复

**Comment by Guciliang** [comment]
> 确实寄了

刚试了一首狐妖小红娘的“寄"又能获取了，看了下是酷我的，原先寄了的依旧不能获取

**Comment by gdstudio-org** [comment]
> @939163156 你的能用嗎

不能，kuwo接口更换太频繁，又没高品无损资源，半年前就放弃维护了

**Comment by zxymdaddy** [comment]
现在确定能用的音源有几个？？都有哪个？

**Comment by chris7395328** [comment]
酷我用不了感觉可以用@939163156 大佬的qq替代？毕竟曲库差不多

**Comment by catsimple** [comment]
> 酷我用不了感觉可以用@939163156 大佬的qq替代？毕竟曲库差不多

你的unm的pyncmd源能用？我的显示all promises were rejected

**Comment by chris7395328** [comment]
> > 酷我用不了感觉可以用@939163156 大佬的qq替代？毕竟曲库差不多
> 
> 你的unm的pyncmd源能用？我的显示all promises were rejected

目前正常哦

**Comment by gdstudio-org** [comment]
> > 酷我用不了感觉可以用@939163156 大佬的qq替代？毕竟曲库差不多
> 
> 你的unm的pyncmd源能用？我的显示all promises were rejected

UNM更新到最新版，老版pyncmd使用的API URL被我加访问限制了
