### ISSUE TITLE
有时能正常播放，有时候会变成固定6秒音频

### ISSUE THREAD

**Issue by shenchuisi** [1715173329/UnblockNeteaseMusic#1409]
### Bug 描述

同一首歌曲，播放的时，有时候会变成6秒音频：你所播放的内容需开通会员后畅听，如已是会员，请到应用商店更新最新版本

### 启动命令及环境变量

node app.js

### 日志内容

没找到日志

### 网易云音乐版本号

2.10.13、3.xbeta

### 操作系统

centos7

### 其他信息

有时可以正常播放，有时就是6秒的提示音频

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by Yusoo** [comment]
用的docker版本，也是一样，可能是哪个音源要验证会员了

**Comment by Inkarro** [comment]
更新unm即可，最新commit修了

**Comment by Aruiyasama** [comment]
> 更新unm即可，最新commit修改了

请问该如何更新？我使用的是[https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic](url)QtUnblockNeteaseMusic]Public

我刚刚下载了[https://github.com/UnblockNeteaseMusic/server/releases](url)把QtUnblockNeteaseMusic Public的UNM替换了后，又下载了 项目的文件夹然后安装了证书，又下载了Node.js 然后把server-enhanced文件夹里面的内容复制到了那个启动器的文件夹下 然后全部退出又重新启动后又可以正常播放了，我这是歪打正着？还是怎么...如果可以麻烦大佬指明一下更新的路ov0本人比较笨刚刚开始研究这个东西

**Comment by shenchuisi** [comment]
更新到最新版本可以解决

**Comment by Aruiyasama** [comment]
> 更新到最新版本可以解决

那个软件我点击了检查更新是显示最新版...[https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.6-patch.1](url)的上次更新是2个星期前，能在具体一点吗？我不知道我的那个操作方法是否正确，如果可以请给我一个更新的链接或者教程

**Comment by Inkarro** [comment]
> > 更新unm即可，最新commit修改了
> 
> 请问该如何更新？我使用的是[https://github.com/FrzMtrsprt/QtUnblockNeteaseMusic](url)QtUnblockNeteaseMusic]Public
> 
> 我刚刚下载了[https://github.com/UnblockNeteaseMusic/server/releases](url)把QtUnblockNeteaseMusic Public的UNM替换了后，又下载了 项目的文件夹然后安装了证书，又下载了Node.js 然后把server-enhanced文件夹里面的内容复制到了那个启动器的文件夹下 然后全部退出又重新启动后又可以正常播放了，我这是歪打正着？还是怎么...如果可以麻烦大佬指明一下更新的路ov0本人比较笨刚刚开始研究这个东西

就是这么操作的。其实你只用clone本项目然后覆盖掉旧版本就可以了，不用重新安装NodeJS
