### ISSUE TITLE
酷我源又不能用了

### ISSUE THREAD

**Issue by LiuXiaohuanhh** [1715173329/UnblockNeteaseMusic#1410]
### Bug 描述

解析到酷我的都会变成一个6秒的广告

### 启动命令及环境变量

node\node.exe Unlock-netease-cloud-music\app.js -p 8080:8081 -s -o bilibili kugou migu -e https://music.163.com

### 日志内容

日志显示解析到这个文件 
 http://nf.sycdn.kuwo.cn/e12f722e161e7e143dbfcd71e91e2560/66440581/resource/n3/58/79/2272659253.mp3?bitrate

### 网易云音乐歌曲链接

https://music.163.com/song?id=186005&userid=278477392

### 网易云音乐版本号

3.0.0.Beta Build:202739 Patch:c4d2760

### 操作系统

Windows 11

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by wwfra** [comment]
我也是这样，把酷我源先下了就可以

**Comment by 1715173329** [comment]
![image](https://github.com/UnblockNeteaseMusic/server/assets/22235437/6757c8ec-b749-433d-bf77-8c42d0415b12)
啊酷我不能用了，哪里不能用了，这么多年一直都是这个 API

**Comment by wwfra** [comment]
可能你这个歌不要会员是不是？我的好多都是6s广告，告诉我"请开通会员..."，然后我把酷我下了，结果变成试听30s了，我网易云版本2.10.12，插件重装了最新的，证书也是，这里截图比较早，我的插件已经成功更新到0.27.6了
![ncm](https://github.com/UnblockNeteaseMusic/server/assets/105968960/aed03cd5-502b-41b8-b02b-8b765f7f9db3)

**Comment by LiuXiaohuanhh** [comment]
也是暂时把酷我去掉了在 2024年5月15日，09:42，李炜哲 ***@***.***> 写道：﻿
我也是这样，把酷我源先下了就可以

**Comment by LiuXiaohuanhh** [comment]
> ![image](https://private-user-images.githubusercontent.com/22235437/330638452-6757c8ec-b749-433d-bf77-8c42d0415b12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDgxNDAsIm5iZiI6MTcxNTc0Nzg0MCwicGF0aCI6Ii8yMjIzNTQzNy8zMzA2Mzg0NTItNjc1N2M4ZWMtYjc0OS00MzNkLWJmNzctOGM0MmQwNDE1YjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA0MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MDMxZjU1ZWU4ODFjNGJiM2I4Y2I3ODZmMTBmOTkxMDUyYWIzNTBmMWFlMjhiZGJmZjFkZjkzMWY1YjhiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LrIfvMczMh2RFkdvpNPZiLMN9a_1Fj7PFhV--ZpAGaw) 啊酷我不能用了，哪里不能用了，这么多年一直都是这个 API

我的解析出来就是前面那个6s链接

**Comment by floatinghua** [comment]
![image](https://github.com/UnblockNeteaseMusic/server/assets/38682071/b8f4ed2d-f9af-4834-9f73-8aa5c015d445)

解析出来的音源也是6s的 开通会员http://nf.sycdn.kuwo.cn/2893af7a1d232f68f4633e5aaedde1b8/66446d70/resource/n3/58/79/2272659253.mp3?bitrate

**Comment by Inkarro** [comment]
该问题在昨天就已被修复，请更新至master分支里的预编译版本。
参见 #1405 #1409

**Comment by LiuXiaohuanhh** [comment]
多谢在 2024年5月15日，20:27，Inkarro ***@***.***> 写道：﻿
该问题在昨天就已被修复，请更新至master分支里的预编译版本。
参见 #1405 #1409

**Comment by LiuXiaohuanhh** [comment]
使用最新的enchened分支已解决问题

**Comment by ttttya** [comment]
> 可能你这个歌不要会员是不是？我的好多都是6s广告，告诉我"请开通会员..."，然后我把酷我下了，结果变成试听30s了，我网易云版本2.10.12，插件重装了最新的，证书也是，这里截图比较早，我的插件已经成功更新到0.27.6了 ![ncm](https://private-user-images.githubusercontent.com/105968960/330644726-aed03cd5-502b-41b8-b02b-8b765f7f9db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMjg5NDEsIm5iZiI6MTcxOTMyODY0MSwicGF0aCI6Ii8xMDU5Njg5NjAvMzMwNjQ0NzI2LWFlZDAzY2Q1LTUwMmItNDFiOC1iMDJiLThiNzY1ZjdmOWRiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNTE3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDhjOGE1ZWFhMmM2OWY3MGFiN2FkOTJmODk5OTZmOTRmNWNkYmQwMTViMWQ5MzlkNWYyMmVmMTBjNzljOThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z--QTUC5vwBekMoCK8qfttpOrQAKUanaTCt6MViz0Mg)

老兄你这revivedunblock插件是怎么安装的，我根据官方指引https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller/blob/close/README.md，并没有其所说的"来输入自定义源的输入框啊"
![image](https://github.com/UnblockNeteaseMusic/server/assets/134094307/801226d5-e11c-46fc-be3a-88c2ef0dfffa)
