### ISSUE TITLE
选的酷我 qq音源问题。

### ISSUE THREAD

**Issue by Ayuyi** [1715173329/UnblockNeteaseMusic#1411]
### Bug 描述

很多歌曲都提示你所播放的内容需要开通会员什么的

### 启动命令及环境变量

环境正常

### 日志内容

这个不懂

### 网易云音乐歌曲链接

http://music.163.com/song?id=1984758339&userid=455176327

### 网易云音乐版本号

2.10.12

### 操作系统

win10

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by Inkarro** [comment]
请使用最新的enchened分支

**Comment by KusanagiKW** [comment]
> 请使用最新的enchened分支

不行啊，https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.6-patch.1 这个就是最新版啊

**Comment by Ayuyi** [comment]
> 请使用最新的enchened分支

用的就是最新的，

> 请使用最新的enchened分支

之前我一直使用0.

> 请使用最新的enchened分支

之前我是用0.27.4版本的，昨天突然就各种歌曲都提示开通会员什么，反正放不了。之后我就更新0.27.6也不行，然后酒试了分支，以及0.27.5的都试了，一样情况

**Comment by Ayuyi** [comment]
> 请使用最新的enchened分支

之前我是用0.27.4版本的，昨天突然就各种歌曲都提示开通会员什么，反正放不了。之后我就更新0.27.6也不行，然后酒试了分支，以及0.27.5的都试了，一样情况

**Comment by Ayuyi** [comment]
> > 请使用最新的enchened分支
> 
> 不行啊，https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.6-patch.1 这个就是最新版啊

你也这个情况吗？我暂时远了网易云第三方API的音源解决了，其他音源酷我的提示开会员，其他音源大部分是15秒，唯一“网易云第三方API”这个能用，YouTube那些我没试。

**Comment by wa1028** [comment]
把这个换了就好了 https://github.com/UnblockNeteaseMusic/server/tree/enhanced/precompiled

**Comment by Ayuyi** [comment]
> 把这个换了就好了 https://github.com/UnblockNeteaseMusic/server/tree/enhanced/precompiled

怎么更换文件，我是用BetterNCM 安装的，在BetterNCM里也找不到UnblockNeteaseMusic

**Comment by Inkarro** [comment]
> > 请使用最新的enchened分支
> 
> 不行啊，https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.6-patch.1 这个就是最新版啊

请分清什么是“分支”，什么是“发型版本”

**Comment by pan93412** [comment]
發行了新的 v0.27.7，再麻煩您再測試一次～

https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.7

BetterNCM 不太清楚，看了一下文件，它應該沒預裝 UNM 吧。

**Comment by KusanagiKW** [comment]
> 發行了新的 v0.27.7，再麻煩您再測試一次～
> 
> https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.7
> 
> BetterNCM 不太清楚，看了一下文件，它應該沒預裝 UNM 吧。

好了，感谢更新

**Comment by FrontGnat437168** [comment]
> 發行了新的 v0.27.7，再麻煩您再測試一次～
> 
> https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.7
> 
> BetterNCM 不太清楚，看了一下文件，它應該沒預裝 UNM 吧。

感谢大佬更新！

**Comment by Ayuyi** [comment]
> 發行了新的 v0.27.7，再麻煩您再測試一次～
> 
> https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.7
> 
> BetterNCM 不太清楚，看了一下文件，它應該沒預裝 UNM 吧。

可以了，感谢大佬。

**Comment by KusanagiKW** [comment]
> 發行了新的 v0.27.7，再麻煩您再測試一次～
> 
> https://github.com/UnblockNeteaseMusic/server/releases/tag/v0.27.7
> 
> BetterNCM 不太清楚，看了一下文件，它應該沒預裝 UNM 吧。

又挂了T T
