### ISSUE TITLE
win端网易云 无法选择母带音质？

### ISSUE THREAD

**Issue by Noyamo** [1715173329/UnblockNeteaseMusic#1414]
### Bug 描述

请问一下，播放的音质是标准 选择更高的母带音质后，界面显示的还是标准音质，是选择高音质失败了吗？
![Lz7g3J0jvy](https://github.com/UnblockNeteaseMusic/server/assets/96122356/1ad0b114-e0b4-4734-9b3d-110379014bc0)

### 启动命令及环境变量

ENABLE_LOCAL_VIP=svip
ENABLE_FLAC
SELECT_MAX_BR=true

### 日志内容

no

### 网易云音乐版本号

当前版本3.0.0.Beta(64位)(Build:202825)Patch:79a5279

### 操作系统

windows

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by ITManCHINA** [comment]
母带是AI升频的版本，这个插件只能提供最高HiRes或者SQ品质

然后建议少听点音乐平台的母带

**Comment by 1715173329** [comment]
音质取决于音源接口，而不是 ui。
