### ISSUE TITLE
酷我源又双叒叕不能用了......

### ISSUE THREAD

**Issue by DestoryG** [1715173329/UnblockNeteaseMusic#1415]
### Bug 描述

酷我源解析VIP音乐时，再次出现了熟悉的“您所播放的内容需开通会员畅听，如已是会员，请到应用商店下载最新APP”

### 启动命令及环境变量

set ENABLE_LOCAL_VIP=svip
set ENABLE_FLAC=true
set MIGU_COOKIE=xxxxxx
node app.js -o pyncmd kuwo migu kugou -p 8888:8889

### 日志内容

http://nf.sycdn.kuwo.cn/9366bf8c5316b6dceaa32347952bf713/6659ce82/resource/n3/58/79/2272659253.mp3?bitrate

### 网易云音乐歌曲链接

https://music.163.com/song?id=1836117628&userid=1521079201

### 网易云音乐版本号

2.10.12

### 操作系统

Windows 10

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
寄啦

**Comment by TiantingShi** [comment]
同样！！  求求替换音源

**Comment by Jia060117** [comment]
难受死了一晚上没听歌😭

**Comment by Iseink** [comment]
附议

**Comment by DDHZJ** [comment]
难受

**Comment by 1715173329** [comment]
鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。
附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。

**Comment by Jia060117** [comment]
> 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。

老大，这个好像也不行了

**Comment by Zruiry** [comment]
> 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。

大哥，这个要从哪获取

**Comment by wahha2003** [comment]
> 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。

大佬，这个也不行了

**Comment by TiantingShi** [comment]
> 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。

老大， 不行了， 救救孩子把

**Comment by milo1023** [comment]
> 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。

作者已经提示的很明显了。

**Comment by Daedemons** [comment]
> > 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。
> 
> 作者已经提示的很明显了。

请问下除了在kuwo.js文件修改这个包名以外还有其他需要调整的地方吗？我在这一处调整还是没效果

**Comment by milo1023** [comment]
> > > 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。
> > 
> > 
> > 作者已经提示的很明显了。
> 
> 请问下除了在kuwo.js文件修改这个包名以外还有其他需要调整的地方吗？我在这一处调整还是没效果

不是开发模式下，请再次编译食用

**Comment by Daedemons** [comment]
> > > > 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。
> > > 
> > > 
> > > 作者已经提示的很明显了。
> > 
> > 
> > 请问下除了在kuwo.js文件修改这个包名以外还有其他需要调整的地方吗？我在这一处调整还是没效果
> 
> 不是开发模式下，请再次编译食用

再次打扰一下，我是在win下用nodejs挂的，将kuwo.js文件修改完后用``node app.js``重新挂，cmd生成的链接也是都导向开通会员的音频的，这种应该再进行什么处理呢？

**Comment by Zruiry** [comment]
> > > > > 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。
> > > > 
> > > > 
> > > > 作者已经提示的很明显了。
> > > 
> > > 
> > > 请问下除了在kuwo.js文件修改这个包名以外还有其他需要调整的地方吗？我在这一处调整还是没效果
> > 
> > 
> > 不是开发模式下，请再次编译食用
> 
> 再次打扰一下，我是在win下用nodejs挂的，将kuwo.js文件修改完后用`node app.js`重新挂，cmd生成的链接也是都导向开通会员的音频的，这种应该再进行什么处理呢？

![image](https://github.com/UnblockNeteaseMusic/server/assets/49809454/f39d354e-2e9d-44fb-8776-1f4a88aa17c7)

**Comment by windy1021** [comment]
> > > > 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。
> > > 
> > > 
> > > 作者已经提示的很明显了。
> > 
> > 
> > 请问下除了在kuwo.js文件修改这个包名以外还有其他需要调整的地方吗？我在这一处调整还是没效果
> 
> 不是开发模式下，请再次编译食用

大佬可以加个联系方式求教一下吗😭

**Comment by kiko-love** [comment]
> 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。

大佬，请问这个包名是从哪里得到的呢

**Comment by aynakeya** [comment]
> > 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。
> 
> 大佬，请问这个包名是从哪里得到的呢

我猜是酷我车机版
![image](https://github.com/UnblockNeteaseMusic/server/assets/32156054/cd6edb7a-6119-4b33-826c-630620bc974d)

**Comment by Zruiry** [comment]
> > > 鉴于目前的封杀情况，还是暂时不放出来了，相信你们可以解决的。 附上神秘包名：`kwplayer_ar_5.1.0.0_B_jiakong_vh.apk`。
> > 
> > 
> > 大佬，请问这个包名是从哪里得到的呢
> 
> 我猜是酷我车机版 ![image](https://private-user-images.githubusercontent.com/32156054/340871801-cd6edb7a-6119-4b33-826c-630620bc974d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NTczMTksIm5iZiI6MTcxODc1NzAxOSwicGF0aCI6Ii8zMjE1NjA1NC8zNDA4NzE4MDEtY2Q2ZWRiN2EtNjExOS00YjMzLTgyNmMtNjMwNjIwYmM5NzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAwMzAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYTczZjlkOGJlNGEzMmUxMWJmY2Q3MDA4YjFjMWQ5NWMzMjFlMDY0NzdlMWQ4NDg4ZTE0MDk0NjI3OGYzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kMj57ffYVE7Bn7hhR1EzBi4ypHWIDBqpOxopK-zPOgE)

你这是哪个版本的，我抓车机包不是jiakong

**Comment by aynakeya** [comment]
> 你这是哪个版本的，我抓车机包不是jiakong

6.3.9.40，而且这个版本用的不是明文，他是用kpk加密了的，直接抓包看不到的

http://nmobi.kuwo.cn/mobi.s?f=kwxs&q=OCGk_ECm6dOb_DJVKzHfKPA1qKoKNG8sz1IhuP8pKvw1GoN4mZM6LYX9iFdgEkJfYXBrNAGAe2eDwZLE3Vxpj41B5q0s6z8RLqmUPkXZ2CRyBvo9VR6-IF6-4iGy9C_D3hIBq4xG2abDBxpjMepcJE_O2VVWGhdtXrNBuPjZqBGxggi2M-Xx8_fHHPe3gIXXfhJMle10Orc3B8KbuxSI2s8xhcwOqQJM2MAuK6VXJpl_jBrQZyi1sFxJVx4DRXGCntYe6V0I3RVG5V4Z3rUZBIMq0N9NMYDrVFIEE5RyBJfaPUS4SVRQzdY5aUxFEhnZHlR3QLgLvCwaO74tZQANy3VnigEuuBANVHcZm5bpWByEZgH_urF_q9mhOZEFfqirxvcNhQxNiI_Ng6Yr8lcZLZCecrz0lZ-yc2o3C1DmB_OIwFWSdxU6K6OcpBOnzOrdR6O74I_NPcDA7Jy1PsBQ5WHwbI73nMhsnw97300cte2WDbqzn2d45ZkHjftAP2MSmSxHUNacNp2zgHOfakTF8hbVxHfMzzNt6vOIl6TAMOAxs7awl9ZDLMPAEeKQhAykMr6aa1FhHmk2xNEh9Uvkx4VvHUCGvYxUr0uS2iYZq7KLoHvIWoOm9Cr8_S25OjwiNzTiayfCdIcFDOCkiPVIIT-eEtWfxFoQu-iwfb0DF31TijGSvGsxnGorZSbbd1XpnMm3tmyFRdfL1_15K7erWFh2GLu-_TASR1wXUoIkgLhSyMyk-x_xdT-DhXyTGZqWTTVs8Rl52QGDE62WTesahmn7Phl7MKnpKz0LgsD2Q0-zsd4c6AzQ8DQfN0YliqOa

**Comment by Zruiry** [comment]
> > 你这是哪个版本的，我抓车机包不是jiakong
> 
> 6.3.9.40，而且这个版本用的不是明文，他是用kpk加密了的，直接抓包看不到的
> 
> http://nmobi.kuwo.cn/mobi.s?f=kwxs&q=OCGk_ECm6dOb_DJVKzHfKPA1qKoKNG8sz1IhuP8pKvw1GoN4mZM6LYX9iFdgEkJfYXBrNAGAe2eDwZLE3Vxpj41B5q0s6z8RLqmUPkXZ2CRyBvo9VR6-IF6-4iGy9C_D3hIBq4xG2abDBxpjMepcJE_O2VVWGhdtXrNBuPjZqBGxggi2M-Xx8_fHHPe3gIXXfhJMle10Orc3B8KbuxSI2s8xhcwOqQJM2MAuK6VXJpl_jBrQZyi1sFxJVx4DRXGCntYe6V0I3RVG5V4Z3rUZBIMq0N9NMYDrVFIEE5RyBJfaPUS4SVRQzdY5aUxFEhnZHlR3QLgLvCwaO74tZQANy3VnigEuuBANVHcZm5bpWByEZgH_urF_q9mhOZEFfqirxvcNhQxNiI_Ng6Yr8lcZLZCecrz0lZ-yc2o3C1DmB_OIwFWSdxU6K6OcpBOnzOrdR6O74I_NPcDA7Jy1PsBQ5WHwbI73nMhsnw97300cte2WDbqzn2d45ZkHjftAP2MSmSxHUNacNp2zgHOfakTF8hbVxHfMzzNt6vOIl6TAMOAxs7awl9ZDLMPAEeKQhAykMr6aa1FhHmk2xNEh9Uvkx4VvHUCGvYxUr0uS2iYZq7KLoHvIWoOm9Cr8_S25OjwiNzTiayfCdIcFDOCkiPVIIT-eEtWfxFoQu-iwfb0DF31TijGSvGsxnGorZSbbd1XpnMm3tmyFRdfL1_15K7erWFh2GLu-_TASR1wXUoIkgLhSyMyk-x_xdT-DhXyTGZqWTTVs8Rl52QGDE62WTesahmn7Phl7MKnpKz0LgsD2Q0-zsd4c6AzQ8DQfN0YliqOa

密文不全，我写了解密程序的，你这个解密报错

**Comment by aynakeya** [comment]
> 密文不全，我写了解密程序的，你这个解密报错

没少复制啊，你访问一下不就知道了。

![Screenshot_20240619_112720](https://github.com/UnblockNeteaseMusic/server/assets/32156054/b83b4d5a-b9d7-4810-b374-c3eff7f37cb6)

**Comment by Zruiry** [comment]
> > 密文不全，我写了解密程序的，你这个解密报错
> 
> 没少复制啊，你访问一下不就知道了。
> 
> ![Screenshot_20240619_112720](https://private-user-images.githubusercontent.com/32156054/340902401-b83b4d5a-b9d7-4810-b374-c3eff7f37cb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjgyMzAsIm5iZiI6MTcxODc2NzkzMCwicGF0aCI6Ii8zMjE1NjA1NC8zNDA5MDI0MDEtYjgzYjRkNWEtYjlkNy00ODEwLWIzNzQtYzNlZmY3ZjM3Y2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAzMzIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjRmNjU0ODVkMzE1NjY5M2IxZmIxOTc2ZDU0MTkwM2Q4NDAyYjk3YjgyZmFjZTdmNzQzNjNjZGYwYTYzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GtnrZlrntE_5bDADBfgCdfjLCL61_tmo31sfBnYN8ls)

我解的是这个
http://mobi.kuwo.cn/mobi.s?f=kuwo&q=SDKKpI8vPfYgGOuiJY59OZljoyUt6DFXUN5HoB1/aa9rwLMymeAjDAmjU5mTN8Sw3whMj5yrWXA6/DRBilOnYGuBXXkgV5MdffmcFWsJhDqrQw+6WNGMVRNfI3JLDEnAyEy1hwNfyU9ACdwuDd1xj+Omz5jwsMecM8KBfD2xgXTFCySu79pWgsgqO9c3DBQehRhuLv8hLwiRAcRvUqhAdkAJ3C4N3XGP46bPmPCwx5y2adXW/K99z2E2n2bX+Fwd7F5kr8GzYjs+m1cDKK/3UssN5FLLHmCpbcE7ApaxXPY2bO0SK/8oCwxgPfEl9SwcTK87RS972DCRU4ROC6X0OiUUbHZIa2p157c/FY5MTifcWx+3kcdV70dnruMI869z+IL9BiT6W3xlZQhzKr3Icn+P0QX1q4pqu72VgOgzzRAgzv02CJLmDoEwl9S0rHFHO0NBly+8Km8qPTerlPCHHlaDXiRl3tqu8JSCHrTZxwBndGye2vsoICdYUUtspzzaZGjpMffgP+dl/+sopbe/5uyxn8dCI1S2ct03wxw3uYHkSfGoKCk34wcYr79jYgyVBLR2doYANINLp5lx7WIjdZ+4zN/hLz4DWFtKOBbGIDODtdC74jfC1GgDZwlZfPZ6Q1RqR+PI1ceDPTKyMPDnAz+wLwm99Y+bs6N0yCaeXFfGVkYWcrMkjaxCODzhAKtw6RFcB72SG7Qcvg/7qZIaw652hHdh9p5LiQHDRlol+jdcfsAPqG5uoyxjkVM/5DGq/+t/OQDyrnsAEOYfeidRZHltQf4GZ2qg
![image](https://github.com/UnblockNeteaseMusic/server/assets/49809454/b4db2b04-5685-43bc-a5ae-309384b2167c)

**Comment by aynakeya** [comment]
你这是歌词的接口，f=kuwo。f=kwxs这两种加密不一样的。而且我也不知道他发送的时候用的是什么包名，我只是在apk里找到了，所以我猜是车机里的。

**Comment by aynakeya** [comment]
> 你这是哪个版本的，我抓车机包不是jiakong

逆向出来了，包名就是`kwplayercar_ar_6.3.9.40_C_APK_guanwang.apk`，但是type不是`convert_url2`。

这下我也不知道包名是从哪里来的了。

（但是用这个f=kwxs这个接口好像也能拿vip歌曲。

**Comment by galan99** [comment]
还是不能用，到底如何解决啊，提示播放会员

**Comment by 51Hertz** [comment]
插个眼👁

**Comment by HuShanquan3** [comment]
网上找个能用的手机版本，抓个包替换一下就可以了

**Comment by 51Hertz** [comment]
大佬怎么替换?

**Comment by HuShanquan3** [comment]
> 大佬怎么替换?

先根据kpk加密算法写个解密算法，然后抓包，将请求解密出参数，替换下上面那个包名参数

**Comment by 1710643680** [comment]
蹲一手大佬编译

**Comment by ghost** [comment]
需要定制版本的source的值

**Comment by roadwhite** [comment]
> > 你这是哪个版本的，我抓车机包不是jiakong
> 
> 逆向出来了，包名就是`kwplayercar_ar_6.3.9.40_C_APK_guanwang.apk`，但是type不是`convert_url2`。
> 
> 这下我也不知道包名是从哪里来的了。
> 
> （但是用这个f=kwxs这个接口好像也能拿vip歌曲。

大佬,这个接口加密有没有

**Comment by Andyf1-A** [comment]
各位，我是新来的，可不可以通过苹果手机的波 ·点音乐抓包来弄？他的链接好像是lu-sycdn.kuwo.cn

**Comment by gqbre** [comment]
> > 你这是哪个版本的，我抓车机包不是jiakong
> 
> 逆向出来了，包名就是`kwplayercar_ar_6.3.9.40_C_APK_guanwang.apk`，但是type不是`convert_url2`。
> 
> 这下我也不知道包名是从哪里来的了。
> 
> （但是用这个f=kwxs这个接口好像也能拿vip歌曲。

试了不行，是不是姿势有问题
