### ISSUE TITLE
运行报错，Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by Cl0ud9** [1715173329/UnblockNeteaseMusic#142]
前几天一直用的还是好好的，后面更新了一下系统第二天重启后就一直运行不了报错了。我的系统是Win11最新的预览版，版本号为22449.1000，nodejs的版本是16.9.0，麻烦请教一下各位有没有遇到同样的问题，是如何解决的呢？
![1](https://user-images.githubusercontent.com/30020035/132466926-39cb39a6-fdfb-4c3a-a530-c41b913746ab.png)

**Comment by pan93412** [comment]
跟 #91 問題類似。我在那邊回答。
