### ISSUE TITLE
请问能不能将其部署在cloudflare的worker上

### ISSUE THREAD

**Issue by AkimioJR** [1715173329/UnblockNeteaseMusic#1426]
### 需求描述

目前我是在用NAS上的Docker部署了这个项目，由于我没有公网IP，所以在外的时候我使用Frp进行内网穿透访问这项服务，但因为我的VPS在境外，容易被GWF识别为代理流量（虽然就是），导致访问不稳定（http、ss协议都能被GWF精准识别）
后面我偶然发现可以使用CloudFlare的Worker、Pages实现代理访问，就在想是不是可以和本项目结合起来
大致原理是用https://github.com/zizifn/edgetunnel、https://github.com/ca110us/epeius等项目解析传入的vless、trojan协议、然后在转发给本项目进行进一步解析

### 预期行为

实现利用Cloudflare免服务器UnblockNeteaseMusic

**Comment by 1715173329** [comment]
没接触过这个，需要自行研究了。
