### ISSUE TITLE
日志里报错，我不知道这代表了什么

### ISSUE THREAD

**Issue by PearFlowersRattanUp** [1715173329/UnblockNeteaseMusic#1432]
### Bug 描述

{"level":50,"time":1718674918349,"pid":18552,"hostname":"DESKTOP-DUNO5PR","scope":"provider/match","stack":"SyntaxError: Unexpected token < in JSON at position 0\n    at parse (<anonymous>)\n    at JSON.parse (C:\\UnblockMusic\\precompiled\\app.js:81:140690)\n    at C:\\UnblockMusic\\precompiled\\app.js:3:41859\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async u.cache (C:\\UnblockMusic\\precompiled\\app.js:2:1244)\n    at async m (C:\\UnblockMusic\\precompiled\\app.js:3:29352)\n    at async b (C:\\UnblockMusic\\precompiled\\app.js:3:30067)\n    at async Promise.all (index 0)","type":"Error","msg":"Unexpected token < in JSON at position 0"}
{"level":50,"time":1718674918349,"pid":18552,"hostname":"DESKTOP-DUNO5PR","scope":"hook","msg":"No audioData!"}

### 启动命令及环境变量

-p x:x -f x.x.x.x -o bilibili kugou qq kuwo
DISABLE_UPGRADE_CHECK=true
ENABLE_LOCAL_VIP=cvip
FOLLOW_SOURCE_ORDER=true
JSON_LOG=true
LOG_FILE=app.log
QQ_COOKIE=uin=x; qm_keyst=x
NODE_PATH=%USERPROFILE%\Application Data\npm\node_modules

### 日志内容

{"level":50,"time":1718674918349,"pid":18552,"hostname":"DESKTOP-DUNO5PR","scope":"provider/match","stack":"SyntaxError: Unexpected token < in JSON at position 0\n    at parse (<anonymous>)\n    at JSON.parse (C:\\UnblockMusic\\precompiled\\app.js:81:140690)\n    at C:\\UnblockMusic\\precompiled\\app.js:3:41859\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async u.cache (C:\\UnblockMusic\\precompiled\\app.js:2:1244)\n    at async m (C:\\UnblockMusic\\precompiled\\app.js:3:29352)\n    at async b (C:\\UnblockMusic\\precompiled\\app.js:3:30067)\n    at async Promise.all (index 0)","type":"Error","msg":"Unexpected token < in JSON at position 0"}
{"level":50,"time":1718674918349,"pid":18552,"hostname":"DESKTOP-DUNO5PR","scope":"hook","msg":"No audioData!"}

### 网易云音乐版本号

2.9.5

### 操作系统

windows10 Pro

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
忽略即可。
