### ISSUE TITLE
你好作者，我直接下载了你的可执行(.exe)最新版本，但是下载歌的时候会出现如下问题

### ISSUE THREAD

**Issue by qs372243217** [1715173329/UnblockNeteaseMusic#144]
![E6UB@4 CXGJHN%PJ1{ C S1](https://user-images.githubusercontent.com/35731419/132951966-2ab10710-1dfc-4493-9490-36c51a515087.png)
![KGAXB@~R _R(0J921I3BI~2](https://user-images.githubusercontent.com/35731419/132951970-72e278d2-2056-4c8e-9d51-ea90693d802a.png)
.exe里面没报任何错误，但是很多歌下载都出现了404

**Comment by qs372243217** [comment]
### _****_

**Comment by 1715173329** [comment]
看样子 UNM 并没有给出任何可用于替换的音源链接
可以尝试降级版本，目前我正在使用 2.5.0，未出现该问题

**Comment by qs372243217** [comment]
> 



> 
> 
> 看样子 UNM 并没有给出任何可用于替换的音源链接
> 可以尝试降级版本，目前我正在使用 2.5.0，未出现该问题

我换回去确实没有出现这个问题了，但是下载的歌曲的音质大幅下降，原先都是30MB左右，换了之后只有7到10MB了

**Comment by 1715173329** [comment]
> 我换回去确实没有出现这个问题了，但是下载的歌曲的音质大幅下降，原先都是30MB左右，换了之后只有7到10MB了

这大概是你的设定问题，30M 通常是 flac，而 10M 是 320 kbps mp3
![image](https://user-images.githubusercontent.com/22235437/132969726-df73fa1d-7407-44dd-bdd7-7cf82b0df18e.png)

**Comment by qs372243217** [comment]
![B7I)NAZ$~7TKO(C}D I_PCX](https://user-images.githubusercontent.com/35731419/132971115-9f06acc9-55bd-41bc-9cf3-402b18f1e6c6.png)
我就是无损设置的

**Comment by 1715173329** [comment]
FYI
![image](https://user-images.githubusercontent.com/22235437/132971200-f6e7398f-06bc-406e-9b41-89bb421003c5.png)

**Comment by 1715173329** [comment]
https://transfer.sh/iXvkT5/CloudMusic.zip
这是我用的版本，你可以试试

**Comment by qs372243217** [comment]
> 
> 
> https://transfer.sh/iXvkT5/CloudMusic.zip
> 这是我用的版本，你可以试试
不好意思，难道你说的是网易云的版本吗！

**Comment by pan93412** [comment]
> https://transfer.sh/iXvkT5/CloudMusic.zip
> 这是我用的版本，你可以试试
> 不好意思，难道你说的是网易云的版本吗！

看檔案大小，應該是。

**Comment by qs372243217** [comment]
> 
> 
> https://transfer.sh/iXvkT5/CloudMusic.zip
> 这是我用的版本，你可以试试

![图片](https://user-images.githubusercontent.com/35731419/132971413-69d03052-3a97-4bba-8968-144da99899b9.png)
我试了一下，依然是不能下载，但是提示框出现了这些错误
![图片](https://user-images.githubusercontent.com/35731419/132971434-8b01a173-53c6-41f7-ab9d-2a01135ff13c.png)

**Comment by 1715173329** [comment]
> 我试了一下，依然是不能下载，但是提示框出现了这些错误

这只是常规输出。

正常工作的例子：
![image](https://user-images.githubusercontent.com/22235437/132971685-b4f1ad5b-2e8e-4b04-99da-eeaa6e8c0595.png)

**Comment by qs372243217** [comment]
> 
> 
> > 我试了一下，依然是不能下载，但是提示框出现了这些错误
> 
> 这只是常规输出。
> 
> 正常工作的例子：
> ![image](https://user-images.githubusercontent.com/22235437/132971685-b4f1ad5b-2e8e-4b04-99da-eeaa6e8c0595.png)

我不知道我哪里搞错了，我直接下载的作者的这个版本
![图片](https://user-images.githubusercontent.com/35731419/132971782-5eaa5959-ec44-42dd-9f32-bd3b936e8aff.png)
然后按照提示连接了127.0.0.1:8080端口，但是会出现一部分歌下不了的情况（这些歌偶尔能下载偶尔不能，即使能下也只是下10MB到5MB之间的大小）

**Comment by 1715173329** [comment]
> 我不知道我哪里搞错了，我直接下载的作者的这个版本

请到 actions 里面下载最新的版本
如果需要【被替换的音源】也拥有无损音质，需要手动指定环境变量以及按需调整音源。
https://github.com/1715173329/UnblockNeteaseMusic#%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0 #145

**Comment by qs372243217** [comment]
> 
> 
> > 我不知道我哪里搞错了，我直接下载的作者的这个版本
> 
> 请到 actions 里面下载最新的版本
> 如果需要【被替换的音源】也拥有无损音质，需要手动指定环境变量以及按需调整音源。
> https://github.com/1715173329/UnblockNeteaseMusic#%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0 #145

不好意思！，是这样配置就行了吗
![图片](https://user-images.githubusercontent.com/35731419/132972219-665fbab7-25d3-4e6a-a673-02d7651d42b8.png)

**Comment by 1715173329** [comment]
FYI

```cmd
set ENABLE_FLAC=true
.\unblockneteasemusic-win-x64.exe -o kuwo
```

**Comment by qs372243217** [comment]
> 
> 
> FYI
> 
> ```batchfile
> set ENABLE_FLAC=true
> .\unblockneteasemusic-win-x64.exe -o kuwo
> ```

谢谢你的耐心答复，我终于知道是怎么回事了！

**Comment by qs372243217** [comment]
> 
> 
> FYI
> 
> ```batchfile
> set ENABLE_FLAC=true
> .\unblockneteasemusic-win-x64.exe -o kuwo
> ```

抱歉，我使用了这个方法之后，似乎音源质量还下降了
![图片](https://user-images.githubusercontent.com/35731419/132972878-b5a652b7-22ad-4cda-9e15-4557522e33b1.png)
![图片](https://user-images.githubusercontent.com/35731419/132972882-77923f01-58fa-4ede-ba5e-9421af640375.png)

**Comment by qs372243217** [comment]
![图片](https://user-images.githubusercontent.com/35731419/132972892-6e461579-d6dd-4e7d-b0eb-0b9062f05ac7.png)
这个是歌的下载链接

**Comment by 1715173329** [comment]
That's why I used `kuwo` in example ;)

migu 需要自己抓包手机 app 使用的 cookie 才能获取到高音质，见 readme

**Comment by qs372243217** [comment]
> 
> 
> 这就是我`kuwo`在示例中使用的原因;)
> 
> migu 需要自己抓包手机 app 使用的 cookie 才能获取到高音质，见 readme

好的谢谢
