### ISSUE TITLE
你现在收听的音乐需开通会员后畅听，如已是会员请到应用商店更新最新版本

### ISSUE THREAD

**Issue by Yaozh-04** [1715173329/UnblockNeteaseMusic#1445]
### Bug 描述

播放解灰的歌曲时可以看到解析了几分钟的完整歌曲但是开始播放就突然换成了这个提示“你现在收听的音乐需开通会员后畅听，如已是会员请到应用商店更新最新版本”

### 启动命令及环境变量

![QQ_1721484508610](https://github.com/user-attachments/assets/dbaffee9-fd33-4e97-92c0-6f7b89bc7d1b)
![QQ_1721484538272](https://github.com/user-attachments/assets/71dc63c8-3dd3-46f5-aa11-40c32dc37984)

### 日志内容

![QQ_1721484101409](https://github.com/user-attachments/assets/0cc9bb6d-0a7c-4130-849e-17252e250570)

### 网易云音乐版本号

2.10.13

### 操作系统

windows 11

### 其他信息

小白第一次不知道怎么提issue

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by bluesxu** [comment]
+1

**Comment by ghost** [comment]
#1415

**Comment by lfs010324** [comment]
我的也是

**Comment by 789cn** [comment]
+1 pan93412的 docker ,openwrt,都有这问题,
    audioId: 185906
    songName: "发如雪"
    url: "http://nf.sycdn.kuwo.cn/5eb794ed7957c7e2861ba449527a2788/669e139c/resource/n3/58/79/2272659253.mp3?bitrate"
INFO: (provider/match) Replaced: [185878] 夜的第七章
    audioId: 185878
    songName: "夜的第七章"
    url: "http://nf.sycdn.kuwo.cn/95582cbcf5ff5e82c825f4aeaedec498/669e13a4/resource/n3/58/79/2272659253.mp3?bitrate"
好像是酷我的原因,

**Comment by onismss** [comment]
试着取消酷我的音源用别的音源

**Comment by Yaozh-04** [comment]
> 试着取消酷我的音源用别的音源
我这里只有咪咕音乐的音源可以用但是我没有填咪咕的cookie，这个音源还是有部分有问题，比如枫的音源是一路向北
![QQ_1721955146598](https://github.com/user-attachments/assets/fb83612b-7120-491e-9e5a-739acb569266)
还有就是我这个终端里的中文乱码问题不知道怎么解决

**Comment by bywhite0** [comment]
> 还有就是我这个终端里的中文乱码问题不知道怎么解决

在图示路径新建名为 `CodePage` 的DWORD(32位)值，设置为65001（十进制），之后重启终端
![image](https://github.com/user-attachments/assets/f5b0ae38-b92c-48a1-8cea-2f2daa55a4e2)

**Comment by Yaozh-04** [comment]
> > 还有就是我这个终端里的中文乱码问题不知道怎么解决
> 
> 在图示路径新建名为 `CodePage` 的DWORD(32位)值，设置为65001（十进制），之后重启终端 ![image](https://private-user-images.githubusercontent.com/86943191/352442241-f5b0ae38-b92c-48a1-8cea-2f2daa55a4e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDY4NDgsIm5iZiI6MTcyMjAwNjU0OCwicGF0aCI6Ii84Njk0MzE5MS8zNTI0NDIyNDEtZjViMGFlMzgtYjkyYy00OGExLThjZWEtMmYyZGFhNTVhNGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE1MDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNzk2NTM0MWMzMmU0ZjA0ZmM5NTgzY2NjMmZlMDI4YTE3N2RkNWQ3MzhkMmQ0NmYyNWU4ZGUzYzllYzIwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jRI5Z8AbQKYCuVT0pTsDj-HXu7EQ1ifGFW-00R_60EM)

谢谢你，已经解决了，网上找了很多方法包括你说的这种，都不行，最后是下面这种可以
![QQ_1722006519111](https://github.com/user-attachments/assets/3b1a779f-2a66-4141-a5d2-ecf89fd76054)

**Comment by mtxd0529** [comment]
> ### Bug 描述
> 播放解灰的歌曲时可以看到解析了几分钟的完整歌曲但是开始播放就突然换成了这个提示“你现在收听的音乐需开通会员后畅听，如已是会员请到应用商店更新最新版本”
> 
> ### 预期行为
> _No response_
> 
> ### 实际行为
> _No response_
> 
> ### 复现步骤
> _No response_
> 
> ### 启动命令及环境变量
> ![QQ_1721484508610](https://private-user-images.githubusercontent.com/112221723/350696874-dbaffee9-fd33-4e97-92c0-6f7b89bc7d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTQ4MzUsIm5iZiI6MTcyMzY5NDUzNSwicGF0aCI6Ii8xMTIyMjE3MjMvMzUwNjk2ODc0LWRiYWZmZWU5LWZkMzMtNGU5Ny05MmMwLTZmN2I4OWJjN2QxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDAyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjFmY2U5ZDJjMzQwOGM5NWE4NDhmODM0NDU2YTY2ZjY2M2Y2MTQ0NTZjODY3NzcwNjY5YjczZmY2M2RiNzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kiWgXTx9BNNs0SvxqqtQfKV8e6CYdhjp9BeCz0-7Too) ![QQ_1721484538272](https://private-user-images.githubusercontent.com/112221723/350696893-71dc63c8-3dd3-46f5-aa11-40c32dc37984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTQ4MzUsIm5iZiI6MTcyMzY5NDUzNSwicGF0aCI6Ii8xMTIyMjE3MjMvMzUwNjk2ODkzLTcxZGM2M2M4LTNkZDMtNDZmNS1hYTExLTQwYzMyZGMzNzk4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDAyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Zjc3NzAxZDgwNWE3YzRmMTRlYmZlZmJmZjIzYzM5ZTg0NGJhODk4MGMxNGQzOTk4NGUyOWRiZDYzY2JlMjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WNm-mtz2Yxmh8oOVx7UVYB5mIyiXERuT6lVL9-s10nw)
> 
> ### 日志内容
> ![QQ_1721484101409](https://private-user-images.githubusercontent.com/112221723/350696428-0cc9bb6d-0a7c-4130-849e-17252e250570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTQ4MzUsIm5iZiI6MTcyMzY5NDUzNSwicGF0aCI6Ii8xMTIyMjE3MjMvMzUwNjk2NDI4LTBjYzliYjZkLTBhN2MtNDEzMC04NDllLTE3MjUyZTI1MDU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDAyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDkwYzcxZjI0YWM4Y2JiOWQ3ZTAzZmJjNzA0MWFiNWFlZjIxYzg3MDIyOWI0NDdkNWUwZDkyMDRiNjQwOGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._lF_T2ckaolNgfv7OwTApYu0rwMf-qvy3dxtCUMpyJY)
> 
> ### 网易云音乐歌曲链接
> _No response_
> 
> ### 网易云音乐版本号
> 2.10.13
> 
> ### 操作系统
> windows 11
> 
> ### 其他信息
> 小白第一次不知道怎么提issue
> 
> ### 问题排查
> * [x]  我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
> * [x]  我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
> * [x]  我确认我已经启用了 HTTPS 端口。
> * [x]  我确认我已经正确设置了 EndPoint。
> * [x]  我确认我已经在对应的客户端正确安装了 CA 证书。

音源设置那个可视界面是从哪里调出来的？

**Comment by Ember-Dawn** [comment]
> > ### Bug 描述
> > 播放解灰的歌曲时可以看到解析了几分钟的完整歌曲但是开始播放就突然换成了这个提示“你现在收听的音乐需开通会员后畅听，如已是会员请到应用商店更新最新版本”
> > ### 预期行为
> > _No response_
> > ### 实际行为
> > _No response_
> > ### 复现步骤
> > _No response_
> > ### 启动命令及环境变量
> > ![QQ_1721484508610](https://private-user-images.githubusercontent.com/112221723/350696874-dbaffee9-fd33-4e97-92c0-6f7b89bc7d1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTQ4MzUsIm5iZiI6MTcyMzY5NDUzNSwicGF0aCI6Ii8xMTIyMjE3MjMvMzUwNjk2ODc0LWRiYWZmZWU5LWZkMzMtNGU5Ny05MmMwLTZmN2I4OWJjN2QxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDAyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjFmY2U5ZDJjMzQwOGM5NWE4NDhmODM0NDU2YTY2ZjY2M2Y2MTQ0NTZjODY3NzcwNjY5YjczZmY2M2RiNzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kiWgXTx9BNNs0SvxqqtQfKV8e6CYdhjp9BeCz0-7Too) ![QQ_1721484538272](https://private-user-images.githubusercontent.com/112221723/350696893-71dc63c8-3dd3-46f5-aa11-40c32dc37984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTQ4MzUsIm5iZiI6MTcyMzY5NDUzNSwicGF0aCI6Ii8xMTIyMjE3MjMvMzUwNjk2ODkzLTcxZGM2M2M4LTNkZDMtNDZmNS1hYTExLTQwYzMyZGMzNzk4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDAyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Zjc3NzAxZDgwNWE3YzRmMTRlYmZlZmJmZjIzYzM5ZTg0NGJhODk4MGMxNGQzOTk4NGUyOWRiZDYzY2JlMjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WNm-mtz2Yxmh8oOVx7UVYB5mIyiXERuT6lVL9-s10nw)
> > ### 日志内容
> > ![QQ_1721484101409](https://private-user-images.githubusercontent.com/112221723/350696428-0cc9bb6d-0a7c-4130-849e-17252e250570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTQ4MzUsIm5iZiI6MTcyMzY5NDUzNSwicGF0aCI6Ii8xMTIyMjE3MjMvMzUwNjk2NDI4LTBjYzliYjZkLTBhN2MtNDEzMC04NDllLTE3MjUyZTI1MDU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNDAyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDkwYzcxZjI0YWM4Y2JiOWQ3ZTAzZmJjNzA0MWFiNWFlZjIxYzg3MDIyOWI0NDdkNWUwZDkyMDRiNjQwOGIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._lF_T2ckaolNgfv7OwTApYu0rwMf-qvy3dxtCUMpyJY)
> > ### 网易云音乐歌曲链接
> > _No response_
> > ### 网易云音乐版本号
> > 2.10.13
> > ### 操作系统
> > windows 11
> > ### 其他信息
> > 小白第一次不知道怎么提issue
> > ### 问题排查
> > 
> > * [x]   我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
> > * [x]   我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
> > * [x]   我确认我已经启用了 HTTPS 端口。
> > * [x]   我确认我已经正确设置了 EndPoint。
> > * [x]   我确认我已经在对应的客户端正确安装了 CA 证书。
> 
> 音源设置那个可视界面是从哪里调出来的？

应该用的BetterNCM，看这个issue链接：https://github.com/UnblockNeteaseMusic/server/issues/1410
