### ISSUE TITLE
插件设置内无可选版本

### ISSUE THREAD

**Issue by A1120789008** [1715173329/UnblockNeteaseMusic#1446]
### Bug 描述

如题 重新安装插件后无可选版本

### 启动命令及环境变量

![ecd0f48e6798eab03070a077e12fb65d](https://github.com/user-attachments/assets/db75de83-e98c-4ca6-ad84-8b0042ed849d)

### 日志内容

不清楚怎么使用

### 网易云音乐版本号

2.10.12

### 操作系统

windous11  23H2

### 问题排查

- [X] 我确认我使用的核心是由 UnblockNeteaseMusic 项目官方发行，不是其他任何 fork。
- [X] 我确认我已经升级到了最新的核心版本（推荐使用最新构建而不是 release）。
- [X] 我确认我已经启用了 HTTPS 端口。
- [X] 我确认我已经正确设置了 EndPoint。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by bywhite0** [comment]
请移步至 [RevivedUnblockInstaller]( https://github.com/ReviveUnblockNCMInstaller/RevivedUnblockInstaller) 提交问题

**Comment by 1715173329** [comment]
第三方插件自行联系第三方支持。
