### ISSUE TITLE
使用YT-DLP 音频流 命令是否可以更加优化

### ISSUE THREAD

**Issue by 543069760** [1715173329/UnblockNeteaseMusic#1449]
### 需求描述

![image](https://github.com/user-attachments/assets/ea31f89b-9ffc-46e6-8533-44a134bc9db2)

问题现象：使用TY-DLP在执行ytsearch1获得YTB ID之后
根据日志来看执行了 yt-dlp -f 140 --dump-json https://www.youtube.com/watch?v=FYRPm2knWkY
表现出来的现象，需要10s~15s左右开始加载URL执行下载导致 音乐切换的时候。【下一曲】播放卡顿，不流畅需要时间等待
经过查看YT-DLP的文档说， 以下命令可以直接加载 最优 音频，并且排除 WEBM（因为WEBM某些情况下有可能依然被认为是最优音频）这样加速速度更加快
 yt-dlp -f 'bestaudio/best' --format 'bestaudio[ext!=webm]' https://www.youtube.com/watch?v=DXrGoDJuyPg
![image](https://github.com/user-attachments/assets/08afaf38-97cf-41dd-85bb-5428b2f87686)
最终总结逻辑
通过yt-dlp -f 140 --dump-json ytsearch1 搜索，执行搜索获取到YTB-ID之后（删掉yt-dlp -f 140 --dump-json https://www.youtube.com/watch?v=FYRPm2knWkY 过程这个过程使加载更顺畅）直接执行  yt-dlp -f 'bestaudio/best' --format 'bestaudio[ext!=webm]' https://www.youtube.com/watch?v=  

### 其他信息

辛苦开发者大佬评估可行性

**Comment by 1715173329** [comment]
试了下并没有什么差异，dump 出来的 json 也都一样，能卡 15s 大概是网络问题。

**Comment by 1715173329** [comment]
减少一次 call 大概更有意义：#1481
