### ISSUE TITLE
一切都正常只是IOS无法打开排行榜，每次都显示“获取数据失败”

### ISSUE THREAD

**Issue by hwbai** [1715173329/UnblockNeteaseMusic#148]
CMD尝试过 -s -e https://music.163.com 和 -s -e https://music.163.com -f 103.126.92.132都是无法打开排行榜

源在用kuwo qq kugou 和 migu

在IOS设备使用网易云，已添加并且信任ca.crt，使用pac代理连接到synology主机 http://<synology ip: 8080port>/proxy.pac

我自己对docker里面8080和8081两个port有点疑惑：我自己的理解是8080对应的是http，8081对应的是https，因为pac代理用的是http所以只能对接8080？我尝试了https://<synology ip: 8081port>/proxy.pac并不能work，我目前使用的是http://<synology ip: 8080port>/proxy.pac，但是见到docker的log里面都是TUNNEL > localhost:8081，不知道是不是我哪里设置的不对

**Comment by Stonewalling** [comment]
> CMD尝试过 -s -e https://music.163.com 和 -s -e https://music.163.com -f 103.126.92.132都是无法打开排行榜
> 
> 源在用kuwo qq kugou 和 migu
> 
> 在IOS设备使用网易云，已添加并且信任ca.crt，使用pac代理连接到synology主机 http://<synology ip: 8080port>/proxy.pac
> 
> 我自己对docker里面8080和8081两个port有点疑惑：我自己的理解是8080对应的是http，8081对应的是https，因为pac代理用的是http所以只能对接8080？我尝试了https://<synology ip: 8081port>/proxy.pac并不能work，我目前使用的是http://<synology ip: 8080port>/proxy.pac，但是见到docker的log里面都是TUNNEL > localhost:8081，不知道是不是我哪里设置的不对

大佬你在那里设置的是docker-compose.yml文件吗，我设置了youtube源不行啊

**Comment by DieJob** [comment]
我这边ios不能解锁，mac倒是正常，证书已信任，我是个例吗？

**Comment by Stonewalling** [comment]
我mac和ios都不行，证书设置了信任，就是无法解锁，顺便问下各位大佬
![image](https://user-images.githubusercontent.com/21361701/133101783-df3b5482-4cb8-42cf-8c22-51deb4eaebcb.png)
pe配置这么些对吗

**Comment by Stonewalling** [comment]
> 我mac和ios都不行，证书设置了信任，就是无法解锁，顺便问下各位大佬
> ![image](https://user-images.githubusercontent.com/21361701/133101783-df3b5482-4cb8-42cf-8c22-51deb4eaebcb.png)
> pe配置这么些对吗

我是腾讯的服务器，没备案，所以没有域名，是不是这样我的证书无法使用

**Comment by hwbai** [comment]
> > 我mac和ios都不行，证书设置了信任，就是无法解锁，顺便问下各位大佬
> > ![image](https://user-images.githubusercontent.com/21361701/133101783-df3b5482-4cb8-42cf-8c22-51deb4eaebcb.png)
> > pe配置这么些对吗
> 
> 我是腾讯的服务器，没备案，所以没有域名，是不是这样我的证书无法使用

我几乎就是按照这里的教程安装的：https://blog.csdn.net/nomil9/article/details/99696097
看起来感觉没啥问题，其实我也是小白。。

**Comment by hwbai** [comment]
> 我这边ios不能解锁，mac倒是正常，证书已信任，我是个例吗？

mac不需要这个也能解锁哎，不知道为啥～所以我只是在ios上面用这个代理

**Comment by pan93412** [comment]
> 我mac和ios都不行，证书设置了信任，就是无法解锁，顺便问下各位大佬
> ![image](https://user-images.githubusercontent.com/21361701/133101783-df3b5482-4cb8-42cf-8c22-51deb4eaebcb.png)
> pe配置这么些对吗

那份教學感覺是舊的吧，我有空寫一份新的安裝教學。你的做法雖然不太正規，但也應該沒有問題。

除了證書之外，也要記得設定 Proxy 喔

**Comment by hwbai** [comment]
> > 我mac和ios都不行，证书设置了信任，就是无法解锁，顺便问下各位大佬
> > ![image](https://user-images.githubusercontent.com/21361701/133101783-df3b5482-4cb8-42cf-8c22-51deb4eaebcb.png)
> > pe配置这么些对吗
> 
> 那份教學感覺是舊的吧。我有空寫一份新的安裝教學。你的做法雖然不太正規，但也應該沒有問題。
> 
> 除了證書之外，也要記得設定 Proxy 喔

你好，不知道你能不能解答一下我的这个疑惑呀，感谢感谢：我自己对docker里面8080和8081两个port有点疑惑：我自己的理解是8080对应的是http，8081对应的是https，因为pac代理用的是http所以只能对接8080？我尝试了https://<synology ip: 8081port>/proxy.pac并不能work，我目前使用的是http://<synology ip: 8080port>/proxy.pac，但是见到docker的log里面都是TUNNEL > localhost:8081，不知道是不是我哪里设置的不对

**Comment by Stonewalling** [comment]
> > > 我mac和ios都不行，证书设置了信任，就是无法解锁，顺便问下各位大佬
> > > ![image](https://user-images.githubusercontent.com/21361701/133101783-df3b5482-4cb8-42cf-8c22-51deb4eaebcb.png)
> > > pe配置这么些对吗
> > 
> > 
> > 那份教學感覺是舊的吧。我有空寫一份新的安裝教學。你的做法雖然不太正規，但也應該沒有問題。
> > 除了證書之外，也要記得設定 Proxy 喔
> 
> 你好，不知道你能不能解答一下我的这个疑惑呀，感谢感谢：我自己对docker里面8080和8081两个port有点疑惑：我自己的理解是8080对应的是http，8081对应的是https，因为pac代理用的是http所以只能对接8080？我尝试了https://<synology ip: 8081port>/proxy.pac并不能work，我目前使用的是http://<synology ip: 8080port>/proxy.pac，但是见到docker的log里面都是TUNNEL > localhost:8081，不知道是不是我哪里设置的不对

你设置的没有问题，dcoekr显示的端口是docker容器的端口你的外部端口8080（http）映射到了docker内部的8080端口

**Comment by hwbai** [comment]
> > > > 我mac和ios都不行，证书设置了信任，就是无法解锁，顺便问下各位大佬
> > > > ![image](https://user-images.githubusercontent.com/21361701/133101783-df3b5482-4cb8-42cf-8c22-51deb4eaebcb.png)
> > > > pe配置这么些对吗
> > > 
> > > 
> > > 那份教學感覺是舊的吧。我有空寫一份新的安裝教學。你的做法雖然不太正規，但也應該沒有問題。
> > > 除了證書之外，也要記得設定 Proxy 喔
> > 
> > 
> > 你好，不知道你能不能解答一下我的这个疑惑呀，感谢感谢：我自己对docker里面8080和8081两个port有点疑惑：我自己的理解是8080对应的是http，8081对应的是https，因为pac代理用的是http所以只能对接8080？我尝试了https://<synology ip: 8081port>/proxy.pac并不能work，我目前使用的是http://<synology ip: 8080port>/proxy.pac，但是见到docker的log里面都是TUNNEL > localhost:8081，不知道是不是我哪里设置的不对
> 
> 你设置的没有问题，dcoekr显示的端口是docker容器的端口你的外部端口8080（http）映射到了docker内部的8080端口

感谢感谢，看来真的不知道是什么问题导致只有排行榜看不了哈哈哈，歌曲解锁什么的一切正常

**Comment by 1715173329** [comment]
iOS 网易云音乐版本号 8.2.21，目前可以正常查看排行榜。

**Comment by hwbai** [comment]
> iOS 网易云音乐版本号 8.2.21，目前可以正常查看排行榜。

谢谢，看来是网易云更新了的问题，我的app自动更新了现在版本是8.5.20

**Comment by 1715173329** [comment]
大约是设定问题，不太清楚 PAC 如何工作。
我是在路由器上面实现的劫持，目前更新到了 8.5.30，可以正常使用。

**Comment by yangyang0223** [comment]
解决了吗
