### ISSUE TITLE
非CN服务器，部署本项目，仍然存在歌曲无法提示需要会员的情况。

### ISSUE THREAD

**Issue by PoetryU** [1715173329/UnblockNeteaseMusic#1496]
### 需求描述

在非CN服务器通过docker部署了本项目
```
docker run  -d -p 12345:8080  -m 300M --memory-swap -1 -e ENABLE_LOCAL_VIP=true -e NO_CACHE=true -e ENABLE_FLAC=true -e NODE_ENV=production --restart=always --log-opt max-size=10m --name=win_music pan93412/unblock-netease-music-enhanced:latest -e https://music.163.com
```
会员歌曲仍然无法解决。`LOCAL_VIP` 是可以的。
![image](https://github.com/user-attachments/assets/a445a193-a082-4e1f-9dda-6d041f9ffbf6)

----

请问国外机是不是无解？

### 操作系统

all

**Comment by luoxingran** [comment]
需要自己修改请求头用X-Forwarded-For IP伪装为国内IP解决海外地区版权受限问题

**Comment by PoetryU** [comment]
大佬能够进一步指点一下吗？如何修改呢？用nginx？

```shell
server {
        listen 12345;
        server_name  music.example.com;
        access_log /www/wwwroot/music/music.log;
        error_log /www/wwwroot/music/music.error;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For {fake-ip} ;
            proxy_pass http://127.0.0.1:5163;
        }

    }
  ```
  
  其中`5163`端口为本项目服务，通过nginx转发到12345端口
  
  可是我通过12345还是不行

**Comment by luoxingran** [comment]
修改项目源码，在api的请求头上面加ip伪装，比如kuwo  request('GET', url, { 'user-agent': 'okhttp/3.10.0' }) 改成  request('GET', url, { 'user-agent': 'okhttp/3.10.0','X-Forwarded-For':'ip' })

**Comment by pk49800** [comment]
是不是所有的解锁方法都失效了？我试过git下载用node运行或者docker搭建都无法解锁变灰的歌曲

**Comment by sktkyo** [comment]
> 修改项目源码，在api的请求头上面加ip伪装，比如kuwo request('GET', url, { 'user-agent': 'okhttp/3.10.0' }) 改成 request('GET', url, { 'user-agent': 'okhttp/3.10.0','X-Forwarded-For':'ip' })
这个源码在哪里修改呢？
