### ISSUE TITLE
ios最新版无法解锁

### ISSUE THREAD

**Issue by DieJob** [1715173329/UnblockNeteaseMusic#157]
ipad最新版也不行，请问大佬们有无解决方案？

**Comment by 1715173329** [comment]
even without logs...
追新的代价。

**Comment by pan93412** [comment]
> ipad最新版也不行，请问大佬们有无解决方案？

- 有設定 Proxy 嗎？
- 有安裝過憑證了嗎？
- UnblockNeteaseMusic 用得是哪個版本？

**Comment by 1715173329** [comment]
升级到了最新的 8.5.30，目前正常工作。

**Comment by DieJob** [comment]
> > ipad最新版也不行，请问大佬们有无解决方案？
> 
> * 有設定 Proxy 嗎？
> * 有安裝過憑證了嗎？
> * UnblockNeteaseMusic 用得是哪個版本？


之前能正常解锁，已信任证书。Mac端能正常解锁。
UnblockNeteaseMusic版本为v0.27.0-beta.2，配合https://github.com/immortalwrt/luci-app-unblockneteasemusic使用。

手机系统版本为iOS 15 RC，不确定是否为iOS系统的问题。

**Comment by 1715173329** [comment]
iOS 14.6 正常工作。

**Comment by DieJob** [comment]
试了一下改为PAC 自动代理，可以解锁了。之前一直是ipset劫持。
