### ISSUE TITLE
Mac OS X 无法正常使用UnblockNeteaseMusic

### ISSUE THREAD

**Issue by SayuRanger** [1715173329/UnblockNeteaseMusic#158]
之前一直可以用这个软件解锁音乐，但是最近突然不能使用。
之前使用的方法是 修改```/etc/hosts/``` ，并且使用 ```node app.js -p 80:433 -f 103.126.92.132``` 运行。现在遇到的问题是程序可以启动，可以在终端中显示下面的信息
```shell
INFO: (app) HTTP Server running @ http://0.0.0.0:80
INFO: (app) HTTPS Server running @ http://0.0.0.0:433
```
但是从网页端无法打开music.163.com， 通过app也无法连接服务器和播放音乐，终端没有输出其他信息。
尝试生成新的签名并且在系统中信任新生成的签名，但是仍然无法使用。

**Comment by 1715173329** [comment]
http code?

**Comment by 4860575** [comment]
> 之前一直可以用这个软件解锁音乐，但是最近突然不能使用。
> 之前使用的方法是 修改`/etc/hosts/` ，并且使用 `node app.js -p 80:433 -f 103.126.92.132` 运行。现在遇到的问题是程序可以启动，可以在终端中显示下面的信息
> 
> ```shell
> INFO: (app) HTTP Server running @ http://0.0.0.0:80
> INFO: (app) HTTPS Server running @ http://0.0.0.0:433
> ```
> 
> 但是从网页端无法打开music.163.com， 通过app也无法连接服务器和播放音乐，终端没有输出其他信息。
> 尝试生成新的签名并且在系统中信任新生成的签名，但是仍然无法使用。

估计是你食用方法问题,目前我的正常。我的方法如下：
1、node环境：v14.16.0
2、客户端：版本2.3.6 (862)
3、启动方式：
MIN_BR=320000 node /root/UnblockNeteaseMusic/app.js -p 6200:6201 -o pyncmd kuwo -s >>/tmp/mp3.log 2>&1 &
ENABLE_FLAC=true node /root/UnblockNeteaseMusic-b/app.js -o kuwo -p 5200:5201 -o pyncmd kuwo -s >>/tmp/flac.log 2>&1 &
4、客户端使用pac代理。
运行日志如下：
INFO: (app) HTTP Server running @ http://0.0.0.0:6200
INFO: (app) HTTPS Server running @ http://0.0.0.0:6201
INFO: (provider/match) Replaced: [20707442] It's You
    audioId: 20707442
    songName: "It's You"
    url: "http://m7.music.126.net/20210917162545/404e3ac78919d1290b2e3f8a1a115e9a/ymusic/f26c/89ce/2cf1/1534fa0fba33560b32d66f79b4ba6179.mp3"
WARN: (request) The request timed out.
    url: "http://kuwo.cn/search/list?key=It%27s%20YouWestlife"
INFO: (provider/match) Replaced: [4152994] Angel Heart (Unplugged)
    audioId: 4152994
    songName: "Angel Heart (Unplugged)"
    url: "http://m801.music.126.net/20210917162617/99b489313faeca66d98a4311dacbdcd7/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/10116344125/a23c/990d/e362/71e124799ebfcfca0ab4535a3e1e9bb5.mp3"
INFO: (provider/match) Replaced: [20707442] It's You
    audioId: 20707442
    songName: "It's You"
    url: "http://m7.music.126.net/20210917162545/404e3ac78919d1290b2e3f8a1a115e9a/ymusic/f26c/89ce/2cf1/1534fa0fba33560b32d66f79b4ba6179.mp3"
WARN: (request) The request timed out.
    url: "http://kuwo.cn/search/list?key=Angel%20Heart%20(Unplugged)Lovebugs"
INFO: (provider/match) Replaced: [519096111] Crawling (One More Light Live)
    audioId: 519096111
    songName: "Crawling (One More Light Live)"
    url: "http://m7.music.126.net/20210917162707/3b6b714099a4fed0d9452c7c1a8fb60e/ymusic/2239/9c08/b5cd/4d34ce3ca988e2e186c18f6d5a165ec1.mp3"
WARN: (request) The request timed out.
    url: "http://kuwo.cn/search/list?key=Crawling%20(One%20More%20Light%20Live)Linkin%20Park"
^C
[root@VM-0-4-centos ~]# cat music-start.sh 
MIN_BR=320000 node /root/UnblockNeteaseMusic/app.js -p 6200:6201 -o pyncmd kuwo -s >>/tmp/mp3.log 2>&1 &
ENABLE_FLAC=true node /root/UnblockNeteaseMusic-b/app.js -o kuwo -p 5200:5201 -o pyncmd kuwo -s >>/tmp/flac.log 2>&1 &
[root@VM-0-4-centos ~]# node -v
v14.16.0
[root@VM-0-4-centos ~]# tail -F /tmp/mp3.log 
    songName: "Crawling (One More Light Live)"
    url: "http://m7.music.126.net/20210917162707/3b6b714099a4fed0d9452c7c1a8fb60e/ymusic/2239/9c08/b5cd/4d34ce3ca988e2e186c18f6d5a165ec1.mp3"
WARN: (request) The request timed out.
    url: "http://kuwo.cn/search/list?key=Crawling%20(One%20More%20Light%20Live)Linkin%20Park"
INFO: (provider/match) Replaced: [20200849] Marchin' On
    audioId: 20200849
    songName: "Marchin' On"
    url: "http://m7.music.126.net/20210917163038/b9372a38e9c8f4dac3f098e2d6b209d2/ymusic/543f/9a12/5960/0ad698bc255b29a3946a2768a7e4f5fb.mp3"
WARN: (request) The request timed out.
    url: "http://kuwo.cn/search/list?key=Marchin%27%20OnOneRepublic"

**Comment by pan93412** [comment]
> 之前一直可以用这个软件解锁音乐，但是最近突然不能使用。
> 之前使用的方法是 修改```/etc/hosts/``` ，并且使用 ```node app.js -p 80:433 -f 103.126.92.132``` 运行。现在遇到的问题是程序可以启动，可以在终端中显示下面的信息
> ```shell
> INFO: (app) HTTP Server running @ http://0.0.0.0:80
> INFO: (app) HTTPS Server running @ http://0.0.0.0:433
> ```
> 但是从网页端无法打开music.163.com， 通过app也无法连接服务器和播放音乐，终端没有输出其他信息。
> 尝试生成新的签名并且在系统中信任新生成的签名，但是仍然无法使用。
> 
> 

HTTPS 標準連線埠是 443，不是 433 喔。

**Comment by SayuRanger** [comment]
> > 之前一直可以用这个软件解锁音乐，但是最近突然不能使用。
> > 之前使用的方法是 修改`/etc/hosts/` ，并且使用 `node app.js -p 80:433 -f 103.126.92.132` 运行。现在遇到的问题是程序可以启动，可以在终端中显示下面的信息
> > ```shell
> > INFO: (app) HTTP Server running @ http://0.0.0.0:80
> > INFO: (app) HTTPS Server running @ http://0.0.0.0:433
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是从网页端无法打开music.163.com， 通过app也无法连接服务器和播放音乐，终端没有输出其他信息。
> > 尝试生成新的签名并且在系统中信任新生成的签名，但是仍然无法使用。
> 
> HTTPS 標準連線埠是 443，不是 433 喔。

好像是这个问题，改成443以后就可以了。。。
