### ISSUE TITLE
设置-o qq时 无法解析

### ISSUE THREAD

**Issue by CloverOS** [1715173329/UnblockNeteaseMusic#160]
如题，如果单一设置qq音源时，无法进行解析，目前只有kuwo可以解析到，qq我也配置了 uin=; qm_keyst= ，可是还是不行捏
![20210918133115](https://user-images.githubusercontent.com/3244971/133874027-bdb31de4-d5b4-423a-9425-b96b59a3108f.png)

**Comment by pan93412** [comment]
QQ 那個 uin 和 qm_keyst 是要填你自己用瀏覽器登入 QQ 後的 Cookie 資料啦⋯⋯

**Comment by CloverOS** [comment]
> QQ 那個 uin 和 qm_keyst 是要填你自己用瀏覽器登入 QQ 後的 Cookie 資料啦⋯⋯

对呀，我就是chrome登入之后，然后开发者工具里面拿到的uin 和 qm_keyst 然后我直接修改的qq.js里面的cookies，以防环境变量不生效，然后就还是酱紫。。。

**Comment by CloverOS** [comment]
> QQ 那個 uin 和 qm_keyst 是要填你自己用瀏覽器登入 QQ 後的 Cookie 資料啦⋯⋯
![20210918164333](https://user-images.githubusercontent.com/3244971/133882800-ea078f5f-3d33-4eb4-b52d-196c0aefe174.png)
代码是酱紫的
