### ISSUE TITLE
UnblockNeteaseMusic目前使用中的几个问题

### ISSUE THREAD

**Issue by DoveBoy** [1715173329/UnblockNeteaseMusic#164]
Android下如果使用wifi连接搭配本地的termux能正常使用，但是使用移动网络，在接入点设置了代理和端口后没法使用（因为没法设置pac地址了），原作者仓库的是可以使用的，只是因为停更了而不能用了。
环境变量具体怎么设置？可以通过修改哪个文件达到效果？

**Comment by 1715173329** [comment]
This is the solution for you: https://github.com/nining377/dolby_beta/releases/tag/v3.0.0

**Comment by DoveBoy** [comment]
> This is the solution for you: https://github.com/nining377/dolby_beta/releases/tag/v3.0.0

这个用不了，手机没有root，没有框架

**Comment by pan93412** [comment]
> > This is the solution for you: https://github.com/nining377/dolby_beta/releases/tag/v3.0.0
> 
> 这个用不了，手机没有root，没有框架

好像沒有比較好的解方⋯⋯原版應該也沒有對這方面作出什麼改善。

順帶一提，這個是我之前看到，可以免 root 對應用程式加上 Xposed patch 的工具：https://github.com/LSPosed/LSPatch

或許對你有幫助～
