### ISSUE TITLE
音源为QQ时报错

### ISSUE THREAD

**Issue by CloverOS** [1715173329/UnblockNeteaseMusic#167]
![20210919124714](https://user-images.githubusercontent.com/3244971/133915819-16e89bb5-1ee2-4bf1-8c5e-e02b207cf06a.png)
好像是因为解析的问题捏？
qq.js我配置了cookie的，和昨天的一样
启动方式是 node app.js -o qq，开发环境，没有使用precompiled的app.js
![20210919124936](https://user-images.githubusercontent.com/3244971/133915834-9b3ecff9-0164-434d-b2df-b56b414aa1be.png)
cookie是刚登录获取的所以没有过期

ps:感谢作者的付出！

**Comment by pan93412** [comment]
那個是新版本的問題，我先看看怎麼修。

**Comment by CloverOS** [comment]
> 那個是新版本的問題，我先看看怎麼修。

好好~
我还以为和我的node版本有关系
![20210919125543](https://user-images.githubusercontent.com/3244971/133915916-edb20f63-e54a-415c-8c10-dfca001b8202.png)

**Comment by pan93412** [comment]
> > 那個是新版本的問題，我先看看怎麼修。
> 
> 好好~
> 我还以为和我的node版本有关系
> ![20210919125543](https://user-images.githubusercontent.com/3244971/133915916-edb20f63-e54a-415c-8c10-dfca001b8202.png)

還真有關係 orz

`Promise.any()` 目前只支援 Node.js 16 之後的版本喔 owo
你可以用 `yarn build` 讓 Rollup 幫你注入 Polyfill，然後用新編譯的 precompiled 版本。

**Comment by pan93412** [comment]
`song is undefined` 的 request 問題初步解決了。
