### ISSUE TITLE
hook.js 的 hook.connect.before 有bug

### ISSUE THREAD

**Issue by yelochick** [1715173329/UnblockNeteaseMusic#241]
```
hook.connect.before = (ctx) => {
	const { req } = ctx;
	const url = parse('https://' + req.url);
	if (
		[url.hostname, req.headers.host].some((host) =>
			hook.target.host.has(host)
		)
	) {
		if (url.port === 80) {
			req.url = `${global.address || 'localhost'}:${global.port[0]}`;
			req.local = true;
		} else if (global.port[1]) {
			req.url = `${global.address || 'localhost'}:${global.port[1]}`;
			req.local = true;
		} else {
			ctx.decision = 'blank';
		}
	} else if (url.href.includes(global.endpoint)) ctx.decision = 'proxy';
};
```
因为我是部署在云端，为了安全我加了一层v2ray转发
最近更新到最新版，发现网易云报网络连接失败
经过调试和对比三个月前的代码发现原来的 `url.port == 80` 更新成 `url.port === 80` 了
由于 url.port 是string类型，用 === 判断会导致 port=80 连接被reject掉

**Comment by pan93412** [comment]
> ```
> hook.connect.before = (ctx) => {
> 	const { req } = ctx;
> 	const url = parse('https://' + req.url);
> 	if (
> 		[url.hostname, req.headers.host].some((host) =>
> 			hook.target.host.has(host)
> 		)
> 	) {
> 		if (url.port === 80) {
> 			req.url = `${global.address || 'localhost'}:${global.port[0]}`;
> 			req.local = true;
> 		} else if (global.port[1]) {
> 			req.url = `${global.address || 'localhost'}:${global.port[1]}`;
> 			req.local = true;
> 		} else {
> 			ctx.decision = 'blank';
> 		}
> 	} else if (url.href.includes(global.endpoint)) ctx.decision = 'proxy';
> };
> ```
> 
> 
>      
>   
> 
> 因为我是部署在云端，为了安全我加了一层v2ray转发
> 最近更新到最新版，发现网易云报网络连接失败
> 经过调试和对比三个月前的代码发现原来的 `url.port == 80` 更新成 `url.port === 80` 了
> 由于 url.port 是string类型，用 === 判断会导致 port=80 连接被reject掉

應該改成 `parseInt(url.port) === 80`，對吧？我晚點處理。

**Comment by pan93412** [comment]
你確認一下 #242

**Comment by byludy** [comment]
我用xray直接反代       
unm配置     开了音源转发(endpoint)
app.js -a 0.0.0.0 -p 19999:20001 -o kuwo -e https://我的域名/neteasemusic

nginx配置
80端口和443端口都加下面的配置
`        location /neteasemusic
        {
            proxy_pass http://127.0.0.1:19999;
        }
`

xray增加如下配置
outbounds加一段
`    {
      "protocol": "freedom",
      "settings": {
        "redirect":"127.0.0.1:19999",
        "userLevel": 0
      },
      "tag": "netease"
    }
`
routing的rules加一段
`      {
        "type": "field",
        "inboundTag": [
          "VLESS-in"           //改成你的入站tag名
        ],
        "domain": [
          "music.163.com",
          "music.126.net"
        ],
        "outboundTag": "netease"
      },
`

**Comment by wherehome** [comment]
@alexchanchan 有完整的配置文件吗？谢谢了
