### ISSUE TITLE
strict mode不允许音乐云盘upload的URL，导致无法进行上传

### ISSUE THREAD

**Issue by GrayXu** [1715173329/UnblockNeteaseMusic#288]
打开strict mode后无法上传音乐到“音乐云盘”，关闭strict mode后正常。  
应该是因为strict mode不允许`musicupload.netease.com`的请求，如下添加域名后工作正常

```
hook.target.host = new Set([
    'music.163.com',
    'interface.music.163.com',
    'interface3.music.163.com',
    'apm.music.163.com',
    'apm3.music.163.com', // 'mam.netease.com',

    'musicupload.netease.com', // support upload

]);
```

不太熟悉github action的流程，就没有提PR了 :)

**Comment by StandGreat** [comment]
我依旧无法上传本地歌曲到“音乐云盘”中，但是我查看了了当前版本的hook.js中的hook.target.host，内容如下：

hook.target.host = new Set([
	'music.163.com',
	'interface.music.163.com',
	'interface3.music.163.com',
	'apm.music.163.com',
	'apm3.music.163.com',
	'musicupload.netease.com', // support uploading
	// 'mam.netease.com',
	// 'api.iplay.163.com', // look living
	// 'ac.dun.163yun.com',
	// 'crash.163.com',
	// 'clientlog.music.163.com',
	// 'clientlog3.music.163.com'
]);

这个内容应该是和上面的解决方案是一样的，但是目前依旧无法上传音乐到“音乐云盘”中
网易云ver：2.10.10
