### ISSUE TITLE
新的match好像和原作者提供的"按歌曲时长匹配提升精度"的select不兼容?

### ISSUE THREAD

**Issue by SpeedPartner** [1715173329/UnblockNeteaseMusic#81]
- 如将kuwo指定为第一个源,kugou为第二个.

在原版,修复曲源接口的情况下,搜"溯 (Reverse)",3分12秒版本,匹配的不是3分12秒版本(从kuwo的源获取).

不过按原作者提供的"按歌曲时长匹配提升精度"的方法:https://github.com/nondanee/UnblockNeteaseMusic/issues/372#issuecomment-583751043
即可匹配到3分12秒版本(也是从kuwo的源获取,音质320K).

- 使用您维护的这个版本,同样将kuwo指定为第一个曲源,kugou为第二个,匹配的同样不是3分12秒版本(从kuwo的源获取);

但是在同样使用原作者提供的"按歌曲时长匹配提升精度"的方法:https://github.com/nondanee/UnblockNeteaseMusic/issues/372#issuecomment-583751043
却不会在首个kuwo源的列表中按歌曲时长匹配,而是直接跳到指定的第二个kugou源去搜索了,从kugou匹配到的歌曲时长是正确的(因为在kugou搜到的第一首版本时长正好是3分12秒的,所以不清楚原作者的"按歌曲时长匹配提升精度"的方式是否在您维护的版本还有效),但是从kugou获取的音质只有128K还是192K(忘了).

**Comment by SpeedPartner** [comment]
或者说原作者的"按歌曲时长匹配提升精度"的select方式是有效,但是新的match只保留了一个曲源的结果,而不是将列表保留,让select去匹配,导致在第一个曲源中select不到kuwo的这首3分12秒版本,直接跳到了下一个曲源去搜索.

**Comment by 1715173329** [comment]
据我所知现在本项目应该是使用的并行查询，指定的音源顺序相对不再那么重要
如果查询时酷狗比酷我先返回了有效数据，那么会直接采用酷狗的数据。

**Comment by pan93412** [comment]
> 或者说原作者的"按歌曲时长匹配提升精度"的select方式还是有效的,但是新的match只保留了一个曲源的结果,而不是将列表保留,让select去匹配,导致在第一个曲源中select不到kuwo的这首3分12秒版本,直接跳到了下一个曲源去搜索.
> 
> 可能是match.js中
> `return songs[0]`
> 只返回搜到的第一首曲子链接导致?
> 
> 不太懂编程,搞错了请别笑话,哈哈

應該說，目前的機制就像是賽車，誰回傳的快就用誰的。至於賽車裡面的貨物是不是壞掉的，我們並沒有做類似的處理。這部分我先標成 `help wanted`，也歡迎有興趣的工程師一同解決這個問題。

**Comment by SpeedPartner** [comment]
原来是这样,感谢两位解惑;

目前主要问题是回传快的音源,能获取到的音质不一定高,比如我示例的这首曲子,在酷狗是收费的,接口不能获取320K或无损.
而其他音源回传慢,又或者需要加匹配方法(匹配需要时间),其他音源或者首选音源匹配到的歌曲就不会被采用.

目前我还是用的原作者的match方法,加上select匹配方法,按照原来音源顺序的逻辑来提升匹配精度.

我个人认为如果非要从效率和质量中二选一的话,我还是会选择质量.
当然也希望能有两者兼得的方法~希望有更多感兴趣本项目的工程师能一起解决.

**Comment by 1715173329** [comment]
质量问题其实很难说，因为每个平台的版权都有一些细微的出入
这将取决于您个人的歌曲喜好

**Comment by pan93412** [comment]
應在 2148f4f1efbd0d01f780c9b1cfd1935bfed7ea28 解決。

**Comment by pan93412** [comment]
已經修正囉～你能幫我測試看看這個版本嗎：

https://github.com/1715173329/UnblockNeteaseMusic/runs/3378401477

需要先登入 GitHub 帳戶，然後照著圖片操作。如果你不用預編譯版，也能直接 `git pull`。

<img width="1552" alt="截圖 2021-08-20 上午11 49 27" src="https://user-images.githubusercontent.com/28441561/130176324-b2b6219e-c065-4437-a742-b8a069505489.png">

---

新版要求 Node.js 至少要 7.6.0 版本。

**Comment by Heporis** [comment]
> 

用YPM有些歌曲匹配不准确怎么办？比如田馥甄的《不醉不会》，备选音源换了kugou，kuwo，bilibili，migu都一样，2个音源搜索模式切换过也都没用，是不是用qq的会准确一点？
