### ISSUE TITLE
大佬，程序启动后node占用内存一直在增加是什么情况？

### ISSUE THREAD

**Issue by 5axf** [1715173329/UnblockNeteaseMusic#86]
![image](https://user-images.githubusercontent.com/46812012/125269377-36fc1d80-e33b-11eb-97c8-66aa1f43d4f1.png)
如图，占用内存一直在增加。过不了几天就要重新启动一次

**Comment by pan93412** [comment]
> ![image](https://user-images.githubusercontent.com/46812012/125269377-36fc1d80-e33b-11eb-97c8-66aa1f43d4f1.png)
> 如图，占用内存一直在增加。过不了几天就要重新启动一次

我晚點 profiling 看看。

**Comment by 5axf** [comment]
> > ![image](https://user-images.githubusercontent.com/46812012/125269377-36fc1d80-e33b-11eb-97c8-66aa1f43d4f1.png)
> > 如图，占用内存一直在增加。过不了几天就要重新启动一次
> 
> 我晚點 profiling 看看。

大佬回复真及时，幸苦大佬了

**Comment by pan93412** [comment]
能提供一下你的 Node.js 版本跟使用的 commit 嗎？

我在 Node.js v16.4.1 (ARM64) 和 commit a3abdc191f98 這裡做了點記憶體檢查，不過每次請求多出來的部分都是 Node.js 自己的東西⋯⋯

如果 Node.js 還在舊版的話，或許更新會有所改善。

**Comment by 5axf** [comment]
> 能提供一下你的 Node.js 版本跟使用的 commit 嗎？
> 
> 我在 Node.js v16.4.1 (ARM64) 和 commit [a3abdc1](https://github.com/1715173329/UnblockNeteaseMusic/commit/a3abdc191f986f3cf618ee8c250c9291bbde09a8) 這裡做了點記憶體檢查，不過每次請求多出來的部分都是 Node.js 自己的東西⋯⋯
> 
> 如果 Node.js 還在舊版的話，或許更新會有所改善。

Node.js版本 v14.16.1

**Comment by 5axf** [comment]
> 能提供一下你的 Node.js 版本跟使用的 commit 嗎？
> 
> 我在 Node.js v16.4.1 (ARM64) 和 commit [a3abdc1](https://github.com/1715173329/UnblockNeteaseMusic/commit/a3abdc191f986f3cf618ee8c250c9291bbde09a8) 這裡做了點記憶體檢查，不過每次請求多出來的部分都是 Node.js 自己的東西⋯⋯
> 
> 如果 Node.js 還在舊版的話，或許更新會有所改善。

我把之前的项目删了，重新拉取最新的代码还是有这个问题
![image](https://user-images.githubusercontent.com/46812012/125571072-758cac87-800e-4c95-a7c3-af9952dd7071.png)

使用网易云听几首歌就这样

**Comment by 1715173329** [comment]
目前我用的版本是 Node.js 14.17.1 on ARMv8，暂时未发现问题。
不过 UNM 会造成内存泄漏也是老问题了（nondanee#363 nondanee#456 nondanee#644）。

**Comment by 5axf** [comment]
> 目前我用的版本是 Node.js 14.17.1 on ARMv8，暂时未发现问题。
> 不过 UNM 会造成内存泄漏也是老问题了（[nondanee#363](https://github.com/nondanee/UnblockNeteaseMusic/issues/363) [nondanee#456](https://github.com/nondanee/UnblockNeteaseMusic/issues/456) [nondanee#644](https://github.com/nondanee/UnblockNeteaseMusic/issues/644)）。

我把缓存给去掉了，我试试还会不会有这种情况

**Comment by 1715173329** [comment]
> 我把缓存给去掉了，我试试还会不会有这种情况

Any improvements?

**Comment by 1715173329** [comment]
Closed due to stale.

**Comment by 1715173329** [comment]
现在这个问题似乎有点严重。。

**Comment by 1715173329** [comment]
> > 现在这个问题似乎有点严重。。
> 
> 用環境變數停用快取呢？我記得他的 cache 有點問題 ，會產生好幾個 setInterval。

谢谢，我试试 emmm

**Comment by 1715173329** [comment]
Great, it works!

**Comment by pan93412** [comment]
@1715173329 那就 todo：重構 cache 好了

**Comment by 1715173329** [comment]
> @1715173329 那就 todo：重構 cache 好了

好吧，看起来只是让泄漏变得缓慢了
但实际还是在泄漏🌚
