### ISSUE TITLE
如何设定默认最佳质量

### ISSUE THREAD

**Issue by goodtogood** [1715173329/UnblockNeteaseMusic#87]
如题，谢谢！
原来用[go版](https://github.com/cnsilvan/UnblockNeteaseMusic)可以默认设置默认质量，但最近失效了，
试了下本repo下的版本确实可用，但默认下载质量如何设定呢
谢谢！

**Comment by pan93412** [comment]
試試看 `export ENABLE_FLAC = "true"` 之後 `node app.js` ？這樣會下載無損版。

如果要下載標準音質，把 `ENABLE_FLAC` 改成 `false` 或者是留空。

**Comment by pan93412** [comment]
```bash
ENABLE_FLAC=true node app.js
```

**Comment by pan93412** [comment]
預設就是詳細日誌模式了。如果有任何問題，把與之相關的 log 傳給我們，我們就會處理了。謝謝您對於 UnblockNeteaseMusic 的熱心協助！ :-)

**Comment by 1715173329** [comment]
> 网易云客户端显示404，此时日志并看不出什么异样

这有可能是当前歌曲无法在指定的平台中检索到任何信息，请尝试调整音源。

> 另外刚试了下用环境变量设置默认下载质量，但重启后试了几首是不生效的

环境变量在 Linux 环境下测试通过，我会于今日晚些时候确认 Windows 平台的情况。

**Comment by goodtogood** [comment]
@1715173329 
目前看win下用环境变量一直是下128k mp3
原来用酷我音源，之前GO版本是可以下无损的

**Comment by 1715173329** [comment]
> 又多测了些歌曲，目前看是可以的，可能之前试的几首都没有无损文件

Fine.
