### ISSUE TITLE
Simple modify to transplant this repo to luci-app-UnblockNeteaseMusic in OpenWRT 

### ISSUE THREAD

**Issue by AoAoAoLion** [1715173329/UnblockNeteaseMusic#88]
cp /usr/share/UnblockNeteaseMusic/update_core.sh /usr/share/UnblockNeteaseMusic/update_core.sh.bak
cat /usr/share/UnblockNeteaseMusic/update_core.sh | sed 's/nondanee/1715173329/g' | sed 's/master/enhanced/g' > /usr/share/UnblockNeteaseMusic/update_core.sh

**Comment by 1715173329** [comment]
We have a luci-app for it, checkout here: https://github.com/immortalwrt/luci-app-unblockneteasemusic.

**Comment by AoAoAoLion** [comment]
Thanks a lot!
