### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN music.httpdns.c.163.com

### ISSUE THREAD

**Issue by cryzlasm** [1715173329/UnblockNeteaseMusic#89]
用的这个 commit
commit 694e2fa59b9df5b04fdb3ef5a80f054604cfb5f8 (HEAD -> enhanced, origin/enhanced, origin/HEAD)
Author: Tianling Shen <i@cnsztl.eu.org>
Date:   Tue Jul 13 16:43:41 2021 +0800

报错了:

unblockneteasemusic    | Error: getaddrinfo EAI_AGAIN music.httpdns.c.163.com
unblockneteasemusic    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
unblockneteasemusic    |   errno: -3001,
unblockneteasemusic    |   code: 'EAI_AGAIN',
unblockneteasemusic    |   syscall: 'getaddrinfo',
unblockneteasemusic    |   hostname: 'music.httpdns.c.163.com'
unblockneteasemusic    | }

**Comment by 1715173329** [comment]
Check your DNS.

**Comment by pan93412** [comment]
> 用的这个 commit
> commit [694e2fa](https://github.com/1715173329/UnblockNeteaseMusic/commit/694e2fa59b9df5b04fdb3ef5a80f054604cfb5f8) (HEAD -> enhanced, origin/enhanced, origin/HEAD)
> Author: Tianling Shen [i@cnsztl.eu.org](mailto:i@cnsztl.eu.org)
> Date: Tue Jul 13 16:43:41 2021 +0800
> 
> 报错了:
> 
> unblockneteasemusic | Error: getaddrinfo EAI_AGAIN music.httpdns.c.163.com
> unblockneteasemusic | at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
> unblockneteasemusic | errno: -3001,
> unblockneteasemusic | code: 'EAI_AGAIN',
> unblockneteasemusic | syscall: 'getaddrinfo',
> unblockneteasemusic | hostname: 'music.httpdns.c.163.com'
> unblockneteasemusic | }

`EAI_AGAIN` 是 `DNS` 相關的錯誤。你應該是用 `docker-compose`，試試看 https://stackoverflow.com/a/61955468 的解方？

此外，防火牆要放行 docker。

**Comment by cryzlasm** [comment]
是 docker  找到原因了,  我给 docker 的 iptables 权限给下了,  给回去就好了.

应该是 iptables 禁止出站啥的
