### ISSUE TITLE
启动之后：播放失败，网络错误

### ISSUE THREAD

**Issue by syymo** [1715173329/UnblockNeteaseMusic#92]
![image](https://user-images.githubusercontent.com/26571594/126785193-5afe0852-29da-46e8-89eb-312dda730032.png)

**Comment by 1715173329** [comment]
- No log
- No runtime env

**Comment by syymo** [comment]
> * No log
> * No runtime env

![image](https://user-images.githubusercontent.com/26571594/126786454-13e293da-c6a7-4c18-849a-9019f818557b.png)

**Comment by 1715173329** [comment]
我假设你运行在 MacOS，证书信任了吗？

**Comment by syymo** [comment]
> MacOS

我是在macos运行的，两个证书都信任了

**Comment by 1715173329** [comment]
我不使用 MacOS，也许 @pan93412 会有一些建议。

**Comment by pan93412** [comment]
> > MacOS
> 
> 我是在macos运行的，两个证书都信任了

你試試在 Safari 打開 [https://music.163.com](https://music.163.com)，出現「不是安全連接」時直接信任，再重新打開 NeteaseMusic 應該就能用了。

**Comment by syymo** [comment]
> https://music.163.com

![image](https://user-images.githubusercontent.com/26571594/126923159-32e07155-bb4a-4d55-abbc-6b29a7aa32aa.png)
没有信任界面

**Comment by pan93412** [comment]
> > https://music.163.com
> 
> ![image](https://user-images.githubusercontent.com/26571594/126923159-32e07155-bb4a-4d55-abbc-6b29a7aa32aa.png)
> 没有信任界面

看起來是你憑證沒設定好⋯⋯假如你的憑證是自己產的，請務必匯入 ca.crt 並調整信任。

<img width="625" alt="截圖 2021-07-26 上午11 13 05" src="https://user-images.githubusercontent.com/28441561/126928055-e3986890-3f85-4f07-b791-866f4691ccf6.png">

**Comment by pan93412** [comment]
此外，假如你用的是 Docker 版本，請改成直接執行 (`node app.js`)。我之前在 macOS 測試過 Docker，似乎也會遇到類似的網路問題。

**Comment by syymo** [comment]
> 此外，假如你用的是 Docker 版本，請改成直接執行 (`node app.js`)。我之前在 macOS 測試過 Docker，似乎也會遇到類似的網路問題。

ok了，thanks

**Comment by wendingp** [comment]
mac docker可以听网易的 但是灰色歌曲听不了 怎么配置代理呢
