### ISSUE TITLE
不能听周杰伦？（已解决）

### ISSUE THREAD

**Issue by redn3ck** [1715173329/UnblockNeteaseMusic#98]
使用最新0.26.1版本，周杰伦一律无法播放？我自己改的版本都正常的，是使用姿势问题？

**Comment by pan93412** [comment]
> 使用最新0.26.1版本，周杰伦一律无法播放？我自己改的版本都正常的，是使用姿势问题？

我們剛好有改動預設來源。你把它改回去看看？

https://github.com/1715173329/UnblockNeteaseMusic/commit/076a0c22dcabc4315d1732e5ba6383337088468c

**Comment by redn3ck** [comment]
嗨呀，不好意思，是姿势问题，加上端口转发和-e程序正常的，周可以听
`-p 4000:89 -e http://music.163.com`

**Comment by redn3ck** [comment]
看到这边一直有维护，本人也对原项目做了很多修改，请问可否加入你们一起维护呢？求个联系方式

**Comment by pan93412** [comment]
> 看到这边一直有维护，本人也对原项目做了很多修改，请问可否加入你们一起维护呢？求个联系方式

歡迎貢獻呀～夠活躍的話我們再幫你拉進去協作者裡面
